### ISSUE TITLE
Kindly request an update to Azure's GPT 3.5 Turbo 16k model

### ISSUE THREAD

**Issue by Drmiaomiao** [logancyang/obsidian-copilot#101]
This plugin is incredibly useful! Thank you to the developers for the dedication. It's exciting to hear that Azure now supports the GPT 3.5 Turbo 16k model. I'm looking forward to being able to utilize this model within the plugin.

**Comment by logancyang** [comment]
@Drmiaomiao Thanks for the kind words! Will add that option soon!

But keep in mind, the Azure model you are using is the one you deploy in Azure, so even if your selection is Azure GPT-4, when your deployment is GPT-3.5, it won't result in an error, it will continue to work but it's actually not GPT-4. The actual model in use is set in your Azure instance and deployment settings. Just wanna point that out to avoid any confusion.
