### ISSUE TITLE
Option to open chat window in content area instead of sidebar

### ISSUE THREAD

**Issue by VOOM108** [logancyang/obsidian-copilot#102]
I would prefer to always open the chat window as a tab in the content area. There really is not much room in the sidebar. I know I can drag the icon, but I don't see a point to have a hotkey to toggle that chat window in the sidebar, as I can pin it as a tab there anyway.

**Comment by logancyang** [comment]
Not sure I understand you correctly, you want a command to open the chat window in the note area directly right?

**Comment by VOOM108** [comment]
Yes, for the regular conversation mode.

**Comment by logancyang** [comment]
Added a new command to toggle in the note area, release v2.3.5.
