### ISSUE TITLE
Double breaks (empty lines) between paragraphs when generating text

### ISSUE THREAD

**Issue by VOOM108** [logancyang/obsidian-copilot#103]
There are double line between paragraphs in the text generated by the AI. Could that be avoided?

**Comment by logancyang** [comment]
@VOOM108 It's a CSS thing, there are several spacing settings for `p` and `li` items. It would be helpful for me to further adjust with a concrete example. Can you post an example with both the screenshot and the copied text here, with a description of your desired styling? That way I can experiment more with it.

**Comment by VOOM108** [comment]
Here is a screenshot of a list. The same whitespace is between all paragraphs: 
<img width="698" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/16562946/c026bc37-08ee-4610-aa98-9e61053cac0e">

And here the copied text: 
Text Editor: A good text editor such as Visual Studio Code or Sublime Text is essential for writing CSS3. These editors offer syntax highlighting, auto-completion, and other helpful features that make writing CSS3 code easier.


CSS3 Documentation: Familiarize yourself with the official CSS3 documentation provided by Mozilla Developer Network (MDN) or the World Wide Web Consortium (W3C). These resources provide detailed information on CSS3 properties, values, and usage.


Browser Developer Tools: Use the developer tools available in modern web browsers like Chrome or Firefox. These tools allow you to inspect and modify CSS styles in real-time, helping you understand how different CSS3 properties affect your web page.


CSS Preprocessors: Consider using CSS preprocessors like Sass or Less to enhance your CSS development experience. These preprocessors offer features like variables, mixins, and nested rules, which can help you write cleaner and more maintainable CSS3 code.


Flexbox: Learn how to use the CSS3 Flexbox layout module, which provides a flexible way to create responsive layouts. Understanding Flexbox will enable you to easily create complex and responsive page structures.
