### ISSUE TITLE
System prompt not overridden

### ISSUE THREAD

**Issue by enricoros** [logancyang/obsidian-copilot#104]
Hi, thanks for the plugin!

When changing the system prompt through Advenced Settings > User custom system prompt (to, let's say, "AI programming assistant"), the Chat functionality does not use that system prompt.

I've restarted, rebooted, tried all permutations, but this is the output:
![image](https://github.com/logancyang/obsidian-copilot/assets/32999/ee23e2d3-be8f-4f0e-8cc7-c5ebb5c5bf52)

**Comment by bichlepa** [comment]
I found the bug:
https://github.com/logancyang/obsidian-copilot/blob/b06dba58ef87d0588793c9f93f945c261dec075f/src/main.ts#L442

A temporary manual fix is possible in [YourVault]\.obsidian\plugins\copilot\main.js.
![image](https://github.com/logancyang/obsidian-copilot/assets/8576321/f406356e-b04d-4ceb-a341-89edce2109a2)

**Comment by logancyang** [comment]
> I found the bug:
> 
> https://github.com/logancyang/obsidian-copilot/blob/b06dba58ef87d0588793c9f93f945c261dec075f/src/main.ts#L442
> 
> A temporary manual fix is possible in [YourVault].obsidian\plugins\copilot\main.js. ![image](https://user-images.githubusercontent.com/8576321/252144253-f406356e-b04d-4ceb-a341-89edce2109a2.png)

Haha thanks for the catch. Will fix in the next release!

**Comment by logancyang** [comment]
It should work now in v2.3.4. Feel free to reopen if it's still not working for you.
