### ISSUE TITLE
Request: Chat with highlighted text as part of the context

### ISSUE THREAD

**Issue by Neuro-Dynamics** [logancyang/obsidian-copilot#106]
It would be really useful, and really a copilot, if you could interact with a selection from the active note. 

- Useful for performing operations on selected text
- Allows discussion of points and ideas by giving the chatbot relevant context. 

These actions cannot be done via the QA mode because it always performs an embeddings search first and does not seem to have memory of the conversation. So iteration over ideas is not possible; it just wants to answer a question and only from the embeddings, not including the current conversation.

At the moment, it has to be done manually by copying the text, pasting it, explaining to the LLM that this is the context and then finally prompting the action to be taken given the copied context.

**Comment by logancyang** [comment]
Have you tried the user custom prompt in conversation mode? The 16k model should work for very long highlighted text.

**Comment by Neuro-Dynamics** [comment]
Can you describe how one would use a custom prompt to this effect? 

What I am suggesting is the following:

1. Select/highlight some text in a note
2. Write something down on the copilot message box
3. The LLM responds to the user taking the selected/highlighted text as part of the context

I don't think this functionality is currently present in obsidian-copilot.

Copilot would have to extract the currently selected text in the note when the user clicks on the message box before typing, then add it to the current chat context with an appropriate system or user prompt, so that the LLM takes that selected text as part of the input.

**Comment by logancyang** [comment]
@Neuro-Dynamics i think you just described how every copilot command works. Here's how to create your own copilot command https://youtu.be/apuV1Jz6ObE

**Comment by Neuro-Dynamics** [comment]
Aha! I had not seen that video and I thought you were describing the custom system prompt from the plugin options. Ok,so this takes us closer.

So to achieve something similar to what I described I would use a prompt like "Using the following text, respond to the query at the end: {}". The to use it I would type my task/question at the end of the section, highlight it and then call Apply custom prompt, and select it from the menu.

I just tried it and it works, but it is not ideal. Some extra steps even with a hotkey you need to select the prompt from the list, plus I have to later delete the written task form the note. So I still think there is room for just automatically picking up the highlighted text to include it in the context during a chatting session (without the need for calling a custom prompt and writing directly on the note.) Maybe this is not technically possible.

Thank you for the heads up, I will be using the custom prompt method.
