### ISSUE TITLE
输入法输入英文的时候点击回车会直接发出去

### ISSUE THREAD

**Issue by cao93821** [logancyang/obsidian-copilot#108]
<img width="414" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/13725617/80602826-2943-48bf-87a8-39dd8deba1df">
使用中文输入法进行英文输入需要使用回车，点击回车就直接发送了
系统mac os

**Comment by logancyang** [comment]
可以习惯一下用数字键选中。Enter发送，Shift Enter换行。
