### ISSUE TITLE
【Error】LangChain error:context_length_exceeded

### ISSUE THREAD

**Issue by Timehsw** [logancyang/obsidian-copilot#112]
when i use azure openai GPT-3.5,the book send me LangChain error:context_length_exceeded

**Comment by logancyang** [comment]
Are you in QA mode or using commands? In conversation mode. GPT-3.5 has a context length of 4096, it's expected to see this error. Pls use a model with a longer context length.

**Comment by Timehsw** [comment]
> Are you in QA mode or using commands? In conversation mode. GPT-3.5 has a context length of 4096, it's expected to see this error. Pls use a model with a longer context length.

I see. I set the token limit to more than 4096, so it will prompt related errors。
Thank you for developing such a useful plugin。
