### ISSUE TITLE
Local API Key Issue

### ISSUE THREAD

**Issue by BradGaddis** [logancyang/obsidian-copilot#121]
I was setting the LocalAI up verbatim from the README, when I ran into a small issue.

I was attempting to set this up entirely locally without using OpenAI at all  when I ran into the issue of "API key not provided for model: LocalAI"  "Error creating model: LocalAI" 

Turns out the work around around was just added an Open AI API key. I was just hoping to bring this to attention. Perhaps the instructions to create the local can be updated to include that as well?

**Comment by logancyang** [comment]
@BradGaddis Oh yes this is one thing that should be improved, right now it still requires an OpenAI key, a fake one should work. Will remove this requirement next.
