### ISSUE TITLE
GPT-3/4 Model Selection

### ISSUE THREAD

**Issue by adastroe** [logancyang/obsidian-copilot#135]
-In copilot settings, Default Model: GPT-4
-Community plugins: toggle off and on to reload plugin
-Restart Obsidian

Prompt "is this gpt-3 or gpt-4?"
Output "As an AI developed by OpenAI, I am based on GPT-3 technology. As of now, GPT-4 has not been released."

Obsidian console: Set chain: llm_chain
Setting model to GPT-4: gpt-4

The paid API account should have GPT-4 access, but it seems my prompts are being handled by their GPT-3 model

**Comment by Sokole1** [comment]
Hi @adastroe This appears just to be a gpt-4 thing. I tried in the OpenAI playground and it also says it is  "based on gpt-3" (image below). If you turn on debug mode in the Copilot settings and check the console logs, it should show gpt-4 which is what is sent in the request.
<img width="1007" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/68660379/c1af15b6-1317-452d-bd95-3fd9ad5e0b41">
<img width="1045" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/68660379/afb9b238-dd7e-49dd-abd7-634ee171ae03">

**Comment by logancyang** [comment]
Yeah this is a known issue for GPT-4 API. OpenAI's web UI used to also have this issue but now they've fixed it only for the web UI and not for the API (probably by a simple prompt prefix). You can tell by latency as well, GPT-4 is much slower.
