### ISSUE TITLE
LocalAI seems running, but Copilot won't connect (macOS M2)

### ISSUE THREAD

**Issue by enzyme69** [logancyang/obsidian-copilot#137]
I tried installing and running the Copilot. With openAI, everything runs okey no problem. But when I setup to work with LocalAI, I cannot seems to get response expected:
[127.0.0.1]:49632  405  -  OPTIONS  /v1/chat/completions
[127.0.0.1]:49632  405  -  OPTIONS  /v1/chat/completions
[127.0.0.1]:49632  405  -  OPTIONS  /v1/chat/completions
[127.0.0.1]:49632  405  -  OPTIONS  /v1/chat/completions

And I also get "network error".

I wonder where I did wrong.

**Comment by enzyme69** [comment]
Maybe I missed the steps of installing proper model, but I got error:

curl http://localhost:8080/models/available | jq '.[] | select(.name | contains("llama2"))'

zsh: command not found: jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2 3810k    2   99k    0     0  98968      0  0:00:39  0:00:01  0:00:38 99447
curl: (23) Failure writing output to destination

**Comment by enzyme69** [comment]
Instead of copying and pasting whole chunk of this "model download curl commands", I use them line by line and I think it's downloading llama model now. Seems almost working...

**Comment by enzyme69** [comment]
All good, I point into llama model.bin etc and working now! I will test with document in context and report if there is any issue. Cheers!

**Comment by etlweather** [comment]
@enzyme69 Thank you! Your LocalAI Docker command gave me the solution for those 405 -- adding `--cors` to the start up params
