### ISSUE TITLE
Local AI setup requires filling out irrelevant fields

### ISSUE THREAD

**Issue by ArcNoctris** [logancyang/obsidian-copilot#138]
Since I was not using this plugin before, nothing was set up. Just filling in the fields described in https://github.com/logancyang/obsidian-copilot/blob/master/localai_setup.md  led to an array of errors:
![image](https://github.com/logancyang/obsidian-copilot/assets/21691720/a636db5c-03a4-4581-b0df-275fa4dfaa90)

I solved this issue by filling in arbitrary strings into blank fields like the "Your OpenAI API key" field. After restarting, everything went as expected.

**Comment by logancyang** [comment]
@ArcNoctris thanks for reporting, it's also reported here https://github.com/logancyang/obsidian-copilot/issues/121. Will push a change to not require the OpenAI key next.

**Comment by classicrob** [comment]
This is still an issue! Before it said error creating LocalAi model, but now it's working once I put a random string in that OpenAI API key area
