### ISSUE TITLE
I cannot select "QA: Active Note" for some reason

### ISSUE THREAD

**Issue by machado-t** [logancyang/obsidian-copilot#142]
When I click it, it just displays and works as Conversation. Not always though.

**Comment by logancyang** [comment]
Can you show your console messages when this happens? I'll need more info to reproduce

**Comment by machado-t** [comment]
Seem to be working with no problems today. I'll let you know if it happens again.

**Comment by logancyang** [comment]
Feel free to reopen this with detailed info on how to reproduce it when you see it again. Close for now.
