### ISSUE TITLE
Active note doesn’t work in Azure gpt 3.5 model

### ISSUE THREAD

**Issue by benjam1nryan** [logancyang/obsidian-copilot#144]
1. it does shows "OK Feel free to ask me questions about [[xxx]].", but when i continue, it says "I'm sorry, but I need more information about which article you are referring to. Can you please provide me with the name of the article or a link to it?". It seems like it doesn’t build the connection with the active note.
2. the "rebuild index for active note" button doesn’t work as well.

**Comment by benjam1nryan** [comment]
<img width="404" alt="Screenshot 2023-09-13 at 00 06 09" src="https://github.com/logancyang/obsidian-copilot/assets/49480577/874d6ac3-6cbb-4a10-9c50-826b1f1f39f3">

**Comment by Sokole1** [comment]
I think it depends on the contents of your note. Technically if you use words such as "this note", "this article", "this paper" etc. If those words aren't in the active note itself, then the GPT model isn't receiving those buzzwords, just the relevant parts of your note content. So it doesn't have a concept of what an "article" is. Maybe try changing your prompt to "What is mentioned here", or "Summarize the key points."

**Comment by logancyang** [comment]
As of now, "QA: Active Note" works as "Retrieval Augmentation" so it requires your query to be something similar to what's in your note. For "summarize this note" type of query, it's easier to just use a Copilot command (you can create your own) with a large context window such as GPT-3.5-16K in Conversation mode.

I'm planning on a bigger update that will consolidate these use cases to offer a better experience. Please stay tuned!
