### ISSUE TITLE
LangChain error: ERR_NETWORK (when using LocalGPT, and sending a message)

### ISSUE THREAD

**Issue by Reno0vacio** [logancyang/obsidian-copilot#145]
plugin:copilot:10337 
 POST http://localhost:8080/v1/chat/completions net::ERR_FAILED
index.html:1 Access to fetch at 'http://localhost:8080/v1/chat/completions' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
plugin:copilot:10337 
 POST http://localhost:8080/v1/chat/completions net::ERR_FAILED
plugin:copilot:60958 
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: Request, …}

**Comment by weihong0827** [comment]
i have the same problem, the preflight OPTION did not pass, stop after 4 trys

**Comment by Sokole1** [comment]
If by LocalGPT you mean LocalAI (https://github.com/go-skynet/LocalAI) then make sure you have the CORS flag enabled when you start the API server: https://github.com/logancyang/obsidian-copilot/blob/master/localai_setup.md.

**Comment by Reno0vacio** [comment]
"LocalAI".
Engedélyeztem, és ugyan az. Valamint azt találtam hogy ha megnyitom a proxy-t akkor ezt az üzenetet adja ki: **{"error":{"code":404,"message":"Cannot GET /v1","type":""}}**
Ez nomrális? A sima OpenAi-os megoldás müködött.
(És igen, fut a Docker.) (Windows-t használok)

**Comment by Sokole1** [comment]
Hi @Reno0vacio, can you turn on Debug mode inside Copilot and share the full logs? I get a similar error if I misspell `http://localhost:8080/v1` for OpenAI Proxy Base URL, but from your original message, it seems like your URL is correct. 
Can you clarify what you mean by "The simle OpenAi solution worked"?
Also, can you share the LocalAI debug logs by uncommenting `DEBUG=true` inside the `.env` file. Thanks.

**Comment by Reno0vacio** [comment]
Hi @Sokole1 here is the debug message:
`New chain created:  llm
plugin:copilot:60789 Set chain: llm_chain
plugin:copilot:60758 Setting model to LocalAI: Luna-AI-Llama2-Uncensored-GGML
plugin:copilot:69946 *** DEBUG INFO ***
user message: Hello
model: Luna-AI-Llama2-Uncensored-GGML
temperature: 0.7
maxTokens: 1000
system message: You are Obsidian Copilot, a helpful assistant that integrates AI to Obsidian note-taking.
chat context turns: 3
plugin:copilot:60914 chain: 
ConversationChain {lc_serializable: true, lc_kwargs: {…}, verbose: false, callbacks: undefined, tags: Array(0), …}
plugin:copilot:60915 Chat memory: 
BufferWindowMemory {chatHistory: ChatMessageHistory, returnMessages: true, inputKey: 'input', outputKey: undefined, humanPrefix: 'Human', …}
plugin:copilot:10337 
 POST http://localhost:8080/v1/chat/completions net::ERR_CONNECTION_REFUSED
plugin:copilot:10337 
 POST http://localhost:8080/v1/chat/completions net::ERR_CONNECTION_REFUSED
plugin:copilot:10337 
 POST http://localhost:8080/v1/chat/completions net::ERR_CONNECTION_REFUSED
plugin:copilot:10337 
 POST http://localhost:8080/v1/chat/completions net::ERR_CONNECTION_REFUSED
plugin:copilot:60958 
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: Request, …}`

I mean by ("The simle OpenAi solution worked") that if i remove the Custome proxy (left it blank), and set the model to "GPT-3.5 16K" then i get a response.

**Comment by Sokole1** [comment]
Hi @Reno0vacio just double checking, are you on the latest version of Copilot (v2.4.3)? Are your requests reaching the LocalAI server at all? (Do you see any logs inside Docker?)

**Comment by Reno0vacio** [comment]
Yes @Sokole1 ! Yes here is the Docker log: 

> 2023-09-16 21:41:10 localai-api-1  | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:34637: connect: connection refused"

**Comment by Sokole1** [comment]
Hi @Reno0vacio can you run LocalAI with DEBUG=true and share the logs? For Docker, you need to edit the `.env` file and uncomment the line `DEBUG=true`. I don't know what your Copilot settings are, but one way you could get that connection error is if you are trying to use a model that you don't have or misspelled. Double-check that you can call the LocalAI server from the command line with curl: https://localai.io/basics/getting_started/. Also double check that you followed all the steps inside https://github.com/logancyang/obsidian-copilot/blob/master/localai_setup.md

**Comment by Reno0vacio** [comment]
I deleted and reinstalled but same thing.. tried this code: (in powershell)

`curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "llama-2-uncensored-q4ks",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9
   }'` 

but it gets an error:

> Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the "Content-Type: application/json" value of type "System.String" to type "System
.Collections.IDictionary".
At line:1 char:51
+ ... st:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeWebRequestCommand


Amikor beirom simán hogy : 
`http://localhost:8080/models/`

Response:

> {"object":"list","data":[{"id":"luna-ai-llama2-uncensored.ggmlv3.q4_K_S.bin","object":"model"}]}


Then who recognizes that there is a model, but when I write "v1" next to it, it writes this: 

> {"error":{"code":404,"message":"Cannot GET /v1","type":""}}

**Comment by trdischat** [comment]
I am experiencing the same problem in Copilot 2.4.3.  I am running the latest version of LocalAI with `CORS=true` in my .env file.  I can chat with it without a problem from the command line in WSL using the Getting Started instructions from the website.  In the settings for Copilot, I input the name of the LocalAI model that I specified in the model YAML file (same as what I used at the command line) and set the OpenAI Proxy to `http://localhost:8080/v1`.  When I try to chat with LocalAI from Copilot I get these error messages:

![Obsidian_ywWI3XdMlD](https://github.com/logancyang/obsidian-copilot/assets/52774325/0c661698-bc02-4c82-9ade-f66fa456c71e)

The debug window in Docker shows this:

![Docker_Desktop_qmtapBjjkZ](https://github.com/logancyang/obsidian-copilot/assets/52774325/8d9ba457-8111-47dc-9f07-75d7c92ad84c)

**Comment by trdischat** [comment]
I have it running now.  I am running LocalAI in Docker Desktop on Windows.  I kept getting the CORS errors above.  So ran `docker-compose up -d --pull always` again from a WSL prompt.  After that, it seems to be working.  I even rebooted, brought up Docker Desktop to launch the LocalAI container and it still works.  I guess rerunning docker-compose fixed the CORS flag.
