### ISSUE TITLE
Add support for code block syntax highlighting

### ISSUE THREAD

**Issue by waynehoover** [logancyang/obsidian-copilot#149]
Obsidian formats code in code (```) blocks very nicely: https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Code

But the syntax highlighting is not present in the copilot chat window.

Example:
<img width="1428" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/115143/19e6f3f5-f92f-4a59-a01e-d6eb10160302">

**Comment by logancyang** [comment]
@waynehoover Yeah this is one of the cosmetic things that didn't work on my last try. Will try again.
