### ISSUE TITLE
add option to customize the file name

### ISSUE THREAD

**Issue by anglee0323** [logancyang/obsidian-copilot#154]
Can you add an option to customize the file name, similar to how you can change the file name in the excalidraw plug-in settings?

Too much time accuracy is sometimes not a good thing (at least for me), it makes people feel messy.

**Comment by logancyang** [comment]
You mean for saved conversations? The plan is to have a summarized short title about what the conversation is about, just like ChatGPT web UI. Does that sound good?

**Comment by anglee0323** [comment]
Yeah that’s a good idea,hope for update 👀

Logan Yang ***@***.***>于2023年9月28日 周四04:38写道：

**Comment by logancyang** [comment]
https://github.com/logancyang/obsidian-copilot/issues/119
