### ISSUE TITLE
In QA: Active Note mode it returns "LangChain error: context_length_exceeded" to the very first question

### ISSUE THREAD

**Issue by paulispaulis** [logancyang/obsidian-copilot#155]
Here is some more context from the console on the error:

code : "context_length_exceeded"
message : "This model's maximum context length is 8192 tokens. However, you requested 8780 tokens (780 in the messages, 8000 in the completion). Please reduce the length of the messages or completion."

I tried changing max_tokens but I think that only affects conversation mode, not QA mode (QA mode max_tokens might be hard coded?)

Using OpenAI models for everything

**Comment by logancyang** [comment]
There is no token limit for the active note itself in QA mode, it's broken down and vectorized. What's your example exactly? Do you have a super long message, or applied a Copilot command on a long selection? Not sure how you can get `context_length_exceeded` in QA mode, can you provide more info?

Please refer to the FAQ for what `max_token` means https://platform.openai.com/docs/api-reference/chat/create#max_tokens

The token count of your prompt **plus** `max_tokens` cannot exceed the model’s context length. So effectively a bigger `max_token` leads to 2 things given a constant context window:
1. less space (tokens) for your prompt
2. more space (tokens) for the completion

It's a bit confusing. I should add it to the FAQ section.
