### ISSUE TITLE
happen langchain error

### ISSUE THREAD

**Issue by EroyalBoy** [logancyang/obsidian-copilot#159]
The same setting ,including api and OpenAl Proxy Base URL (3rd-party providers), were effect in other Obsidian Plugin (text generator), but in copilot show error: 
LangChain error: Error: Expected content-type to be text/event-stream, Actual: application/ json ; charset=utf-8

**Comment by logancyang** [comment]
Seems your 3rd-party provider does not support streaming? Can you show some screenshots with debugging mode?

Does text-generator have the ability to set proxy? Didn't know that

**Comment by ZHN202** [comment]
I had this problem too, you can try adding '/v1' after your URL, I solved the problem this way
![image](https://github.com/logancyang/obsidian-copilot/assets/76200017/7c640c2e-34fd-4ddc-a29d-593af80b9f9d)
When I change my URL to 'https://3rd-party.api/v1/v1' through the console's error report, you can see that the spliced address is incomplete @EroyalBoy
