### ISSUE TITLE
Chat seems to point at 3x model, even when 4x is specified

### ISSUE THREAD

**Issue by hekasq** [logancyang/obsidian-copilot#160]
Q: What version of chatgpt am I interacting with

A: As an AI developed by OpenAI, I'm based on the GPT-3 model, which is the latest available version as of our interaction. Please note that specific versioning details may depend on the deployment and updates by the software or service you're using to interact with me.

Console indicates v4 is passed correctly, but the response seems to indicate v3

<img width="1013" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/19271084/46899a33-f4d9-4d3a-9291-025bbf740eb6">

Note this persists through restarts of Obsidian.

same question answers v4 when asked in thechat.openai.com

What version of chatgpt am I interacting with
ChatGPT
You are interacting with ChatGPT based on the GPT-4 architecture. If you have any more questions or need assistance, feel free to ask!

Thanks! :)

**Comment by logancyang** [comment]
Hi @hekasq , this is actually a known behavior from the GPT-4 API, it likes to say it's GPT-3. You can tell by comparing the speed of the streaming response. GPT-4 response is noticeably slower than GPT-3.5. You could also see the chain parameters in the console like you've shown here which confirms the model type. No worries there :)
