### ISSUE TITLE
APi key not provided and Error Creating Model

### ISSUE THREAD

**Issue by Arkhonian** [logancyang/obsidian-copilot#161]
Hi, I installed the plugin and inserted the openAi API Key, but once I try to start a conversation it gives me two errors "API Key is not provided for the model: GPT 3.5" and "Error creating Model: GPT 3.5".

**Comment by JesseNaser** [comment]
You need to make sure the option in the settings is set to Open AI if you provided the Open AI key, or Azure if you provided an Azure key.

Any time you change the settings, restart obsidian, to restart the plugin. Then it should work.

**Comment by Rohan-es** [comment]
I'm having the exact same issue!!!

**Comment by logancyang** [comment]
Most of the time a reset in settings, restarting the plugin and re-entering the API keys should work, sometimes the cached keys and settings may be in a wrong state. If you use Azure and don't have an OpenAI key, just enter something random as OpenAI key and try again.
