### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by dukeofgaming** [logancyang/obsidian-copilot#162]
It would be nice to have this available in the mobile mode of Obsidian

**Comment by NickDevoctomy** [comment]
+1 for this, it would be awesome to be able to use this across all of my devices!

**Comment by nickfixit** [comment]
Need a method for this. You could easily implement with JavaScript solely as a plugin.

**Comment by logancyang** [comment]
Please refer to #532 to follow along. Closing this as duplicate.
