### ISSUE TITLE
Disable Default prompts?

### ISSUE THREAD

**Issue by 7k50** [logancyang/obsidian-copilot#164]
There seems to be around ~22 default prompts included with Copilot (as seen in the Command Palette).

Is there a way to disable the ones I don't need?

Apologies if this has been answered already, I did not find a note of this.

**Comment by logancyang** [comment]
@7k50 sorry for the late reply. There's currently no way to hide them. What's the main reason you want to hide them? I can reduce the number of default prompts and go for a more "custom prompt" based experience if the current long list is too much of a clutter.

**Comment by 7k50** [comment]
No worries, thanks for getting back to me.

When I type "Copilot" into the Command Palette, I'd prefer to quickly be able to find the ones I use (most of the default ones are not relevant for me). The long list makes it difficult. It would be great if e.g. Options had a method of toggling them On/Off, or similar.

Some of the default ones seem useful, but my assumption is that most users will mostly use custom prompts.

**Comment by logancyang** [comment]
There's a setting now where you can disable these builtin prompt commands in 2.5.4.
