### ISSUE TITLE
TypeError after sending messages in the chat

### ISSUE THREAD

**Issue by sopyb** [logancyang/obsidian-copilot#167]
**Version:** 2.4.3
```
Setting model to LocalAI: llama-2-uncensored-q4ks
[Error: No chat model set] { isTrusted: [Getter] }
*** DEBUG INFO ***
user message: test
model: llama-2-uncensored-q4ks
temperature: 0.7
maxTokens: 1500
system message: You are Obsidian Copilot, a helpful assistant that integrates AI to Obsidian note-taking.
chat context turns: 3

Model request failed: [TypeError: Cannot read properties of undefined (reading 'llm')]
```

Let me know if I need to provide additional information

**Comment by logancyang** [comment]
Looks like this one and https://github.com/logancyang/obsidian-copilot/issues/176 are related. Somehow the chain was undefined and not initialized properly. I haven't personally reproduced this. Can you describe the steps you took?

**Comment by logancyang** [comment]
LocalAI has been updated to LM Studio and Ollama. Please try those options!
