### ISSUE TITLE
😊How to select the corresponding promt template in the plugin according to the folder📁?

### ISSUE THREAD

**Issue by 541864509proton** [logancyang/obsidian-copilot#169]
If there are too many promt templates, they need to be managed through folder classification. So the problem comes, choosing the promt template in the plugin becomes difficult because the display list is too long and inefficient. Can you select through folder classification.

**Comment by logancyang** [comment]
@541864509proton You seem like a power user, it's great to have power users suggesting new features!

Can you describe the experience you want step-by-step in more detail? Currently in "Apply custom prompt" command we have a fuzzy suggest modal that lists all custom prompts, but it filters down as you type. So if you name them with some common prefix you could "classify" your prompts and avoid scrolling over a long list.

I was thinking if I could dump these prompts as notes and load them at command time. Or get rid of the local PouchDB for custom prompts and directly read from notes. That way you can just organize your prompts the same way as notes.
