### ISSUE TITLE
Error at Step build the binary

### ISSUE THREAD

**Issue by kennygokh** [logancyang/obsidian-copilot#175]
Hi, I am trying to setup LocalAI using [How to setup LocalAI on Apple Silicon](https://github.com/logancyang/obsidian-copilot/blob/master/localai_setup.md#how-to-setup-localai-on-apple-silicon). At step **_#build the binary make BUILD_TYPE=metal build_**, I encountered the following error. Please help

**_kennygo@SG-F90RFW34WG LocalAI % make BUILD_TYPE=metal build
go mod edit -replace github.com/nomic-ai/gpt4all/gpt4all-bindings/golang=/Users/kennygo/LocalAI/gpt4all/gpt4all-bindings/golang
make: go: No such file or directory
make: *** [replace] Error 1_**

**Comment by logancyang** [comment]
Looks like you don't have Go installed. You can install Go from their website and check if you have Go by running `go version`.
