### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'llm')

### ISSUE THREAD

**Issue by icarus-00** [logancyang/obsidian-copilot#176]
recently installed it and once I wanted to test it, it gave no response, with a quick message popup appearing.

![image](https://github.com/logancyang/obsidian-copilot/assets/147264641/9e1e9633-cd9a-44ed-a74e-19003fe4e7f0) 

when checking the console i found this error.

![image](https://github.com/logancyang/obsidian-copilot/assets/147264641/d47a7fce-14d5-4993-a683-add7e22d2727)

**Comment by logancyang** [comment]
Were you able to make it work?

**Comment by Einsteinerly** [comment]
I try to set api key with random characters and restart, it loads model successfully, TypeError also disappear.

**Comment by Einsteinerly** [comment]
Here are some hints might be helpful. I encountered the same bug when using local model. 
I try to set api key with random characters and restart, it loaded model successfully, TypeError also disappeared.

**Comment by threeq** [comment]
I am using OpenAI and encountering the same error. How did you resolve it? Can you share the method?

**Comment by icarus-00** [comment]
I opted away from using obsidian, but tried to make a new vault with only the copilot extension, just to see if it works, and it finally did.
I really don't know what might have caused the issue first time, and now probably the only issue is that responses are a bit slow to generate.
other than that everything is working fine.

![image](https://github.com/logancyang/obsidian-copilot/assets/147264641/3f8546e9-00bd-43a7-83dc-da3416923ca3)
