### ISSUE TITLE
OpenRouter's API doesn't work

### ISSUE THREAD

**Issue by intari** [logancyang/obsidian-copilot#178]
I entered base url as https://openrouter.ai/api/v1 and configure api key. 
Attempt to use OpenRouter results in "Please set an "HTTP-Referer" header with the URL of your app"
It doesn't matter if I select LocalAI as model or leave regular OpenAI.
According to OpenRouter's docs at https://openrouter.ai/docs#format - HTTP-referer could https://localhost but it must be set.

**Comment by intari** [comment]
fix provide in https://github.com/logancyang/obsidian-copilot/issues/179

**Comment by logancyang** [comment]
I closed the PR but will have a solution for openrouter.ai. According to their [doc](https://openrouter.ai/models/cognitivecomputations/dolphin-mixtral-8x7b?tab=api), It seems the way to go is

1. put `https://openrouter.ai/api/v1` at OpenAI Proxy Base URL in the setting
2. pass a custom model name

The 2nd point probably needs a custom model name input in the settings. I'll repurpose the current LocalAI one for this then.

**Comment by logancyang** [comment]
OpenRouter is added as a separate option in the model dropdown and settings in v2.4.9, please try it out!
