### ISSUE TITLE
chat with current note

### ISSUE THREAD

**Issue by 1of13** [logancyang/obsidian-copilot#18]
This functionality needs to be fixed. I keep getting "I'm sorry, I cannot summarize the note without further information. Please provide me with more details about the note you are referring to."

**Comment by writtenfool** [comment]
To troubleshoot and reproduce the issue, provide an example of a note that causes the symptom.

**Comment by logancyang** [comment]
@1of13 Can you update your plugin to 1.2.4 and try again?

**Comment by 1of13** [comment]
Nice. It works. Thank you so much for the quick fix.

**Comment by 1of13** [comment]
Logan,

Thanks for the great work on Copilot. I have one suggestion: change the image on the current button “Use Active Note as Context” to “QA Note” and change the floater to “QA: Active Note”. That way, users don’t have to switch back and forth. As is, the fifth button only directs you to use the sixth—which is inefficient.

**Comment by logancyang** [comment]
> Logan, Thanks for the great work on Copilot. I have one suggestion: change the image on the current button “Use Active Note as Context” to “QA Note” and change the floater to “QA: Active Note”. That way, users don’t have to switch back and forth. As is, the fifth button only directs you to use the sixth—which is inefficient.

@1of13 Thanks for the feedback! The new dropdown for chain selection is an essential new component that will determine the mode in which the bot operates. "QA: Active Note" mode is actually the key, the old "Use Active Note as Context" is actually "rebuild index for active note". I should rename it. For chatting with the current note, you can just directly switch to "QA: Active Note" in the dropdown without clicking the button. Let me know if this makes sense.

I'm gonna rename the old button now.
