### ISSUE TITLE
Enable GPT4-Turbo preview

### ISSUE THREAD

**Issue by marcelpallares** [logancyang/obsidian-copilot#180]
Yesterday OpenAI presented GPT4-Turbo. Could we enable accessing the new model in the plugin?

[More info here](https://openai.com/blog/new-models-and-developer-products-announced-at-devday)

**Comment by ChrisJefferson** [comment]
In general, would it be possible to let me specify the model by name, so it's easy to add new models like this? (I realise that might not work if you need more information about the model than just it's name).

**Comment by uPagge** [comment]
+1

**Comment by logancyang** [comment]
Just enabled it in v2.4.4. Let me know if it works for you! I noticed that it's super fast and those older models are slower now, even GPT 3.5 is slow. Not sure if it's just me.

**Comment by uPagge** [comment]
Yes, everything works, thank you))
