### ISSUE TITLE
Would it be possible to add a direct insert into document button

### ISSUE THREAD

**Issue by lithStudy** [logancyang/obsidian-copilot#185]
Would it be possible to add a direct insert into document button next to the message copy button? The primary use case is to insert AI-generated text into a document or replace selected text within the document. While copying and pasting using the copy button is feasible, having a dedicated insert button would greatly enhance convenience. Thank you!

**Comment by logancyang** [comment]
I see, it would require the plugin to remember the last cursor position in the note even when you are focused in the chat window. Adding this to the feature plan next.

**Comment by lithStudy** [comment]
> I see, it would require the plugin to remember the last cursor position in the note even when you are focused in the chat window. Adding this to the feature plan next.

If it is challenging to remember the last cursor position, maybe we could consider implementing a feature where, after selecting some text in the editor, we can activate a command that directly writes OpenAI's response at the current cursor location. There could be an option to either replace the selected text or append the response.

**Comment by wwjCMP** [comment]
It can refer to the implementation of the txt generator. One-time command-based dialogue can directly generate answers under the cursor and add callout syntax.
