### ISSUE TITLE
GPT-4 Turbo model not referenced correctly?

### ISSUE THREAD

**Issue by jazzwall2** [logancyang/obsidian-copilot#188]
Seems that the GPT-4 turbo model is not working properly.  The answers are not as good as GPT-4.  The model, on OpenAI's site is referred as gpt-4-1106-preview, and not "gpt-4-turbo" as I am seeing in the source code here.  Maybe I am missing something?

<img width="806" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/24684816/3ba88e7e-8438-4377-97ca-d6c29383a3d6">

**Comment by logancyang** [comment]
hi @jazzwall2, you can toggle on debug mode and double-check the console for the model being used
<img width="367" alt="Screenshot 2023-11-18 at 10 05 53 AM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/ef998daf-7df5-4d6a-ad63-f73f39716b67">

GPT-4 turbo is just a display name, it wouldn't have returned anything if it were passed to OpenAI. If you feel the quality is not as good as GPT4, many others feel the same and have shared on social media. To me personally, it has been almost on par with GPT4 but with much faster response and a much larger context window. Intuitively it should take a toll on the quality, so I'm not sure whether it really has superior quality over the old GPT-4 as OpenAI claimed.
