### ISSUE TITLE
How to add API parameters?

### ISSUE THREAD

**Issue by Einsteinerly** [logancyang/obsidian-copilot#190]
I am trying to use APl together with text generation webui. Right now the obsidian copilot only supports setting parameter like "temperature", and I want to add more, like "top_p" or "repetition_penalty". I also notice that "top_p" is already show in the network payload, like `{"model":"local model","temperature":0.5,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"max_tokens":4000,"n":1,"stream":true,"messages":[]}`, but it has been set to constant 1. 

So I try to modify the code. Starting from adding constant parameter in `\src\openAiStream.ts:58`
```
const options = {
model,
messages:formattedMessages
max.tokens:maxTokens,
temperature:temperature,
top_p: 0.7,
repetition_penalty: 1.1,
stream: true,
```
also code around `\src\openAiStream.ts:160`
But it didn't works, there is no change in network payload.

My question is, how does API request work? Since I am not familiar with longchain, if someone could offer any help, it would be greatly appreciated.

And a futher discussion, can we have a regenerate button in copilot?

**Comment by logancyang** [comment]
@Einsteinerly `openAiStream.ts` isn't being used as of now, the call is made through LangChain in `src/aiState.ts: runChain`. You could modify them there.

A regenerate button would be nice, could be a good first issue too if anyone is interested in contributing. I'm currently working on something else and will get back to Copilot soon with some major updates.

**Comment by logancyang** [comment]
Created another issue for the regenerate button, closing this one.
