### ISSUE TITLE
Only GPT-3.5 is working

### ISSUE THREAD

**Issue by augustocamargo** [logancyang/obsidian-copilot#193]
I am getting "Lang_Chain error: model_not found"

Anyone else?

:-(

Augusto

**Comment by logancyang** [comment]
hmm that's weird, another user also reported this. GPT-4 and turbo still work for me. Anyone else experiencing this?

Recently OpenAI hasn't been very stable, sometimes they are down and it takes a while for them to update their [status page](https://status.openai.com/).
