### ISSUE TITLE
Save to note does not work

### ISSUE THREAD

**Issue by GdeJoode** [logancyang/obsidian-copilot#198]
For some reason, the "save to note" option does not work. I thought it had to do with specifying a specific target folder, but the default folder also does not work when trying to save a conversation to a note.

**Comment by logancyang** [comment]
Does it show any error message in the console? Have you tried resetting the Copilot settings and try again?

**Comment by GdeJoode** [comment]
Thanks for your quick response. I think I made an error in the path where a
wanted to save the conversations. Some plugins use autocomplete to direct
to the correct path. So maybe a feature request? :-)
Overall great functionality! speeds up my workflow

best!

Geert


Op di 5 dec 2023 om 23:58 schreef Logan Yang ***@***.***>:
