### ISSUE TITLE
I have to pay?

### ISSUE THREAD

**Issue by symonxdd** [logancyang/obsidian-copilot#199]
Do I need to add cash to my OpenAI account so the API key works, because I'm confused?
I can use ChatGPT on their site for free, but when I want to use it with an API token elsewhere I need credits?

**Comment by logancyang** [comment]
@symonxdd  Yes, using their APIs is not free and you need money in your OpenAI account. You can use local models for free. Or if you find any free providers online you can use it with the setting `OpenAI Proxy Base URL`.

I'm also planning to add some free API options soon.
