### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Benniongithub** [logancyang/obsidian-copilot#2]
Amazing app, but to become really useful I think there are a few low hanging fruits you can integrate! I would recommend using langchain as a framework as it makes it really easy to work with LLMs. langchain is more powerful in python, but there is also a typescript integration.

1. Full control over the chat and context like in the openAI playground (delete, create or edit chat messages and continue conversations at a later time)
2. Slice and index notes and save locally using a local vector database server (for example https://weaviate.io/) This makes it possible to search across the whole vault semantically and use context from anywhere at any time. For slicing there are several options built into langchain. https://docs.langchain.com/docs/components/indexing

**Comment by michox** [comment]
For context awareness of the copilot, you could use the langchain contextual compression retriever. With that you can first find the closest documents in your vault, compress their knowledge into relevant packs of knowhow and then use that as prompt context. https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/contextual-compression.html

**Comment by michox** [comment]
I just saw that langchain also has an obsidian loader. It also has pretty much any other loader you can imagine and an automated loader, but besides that langchain is way more powerful in general. I was actively looking for obsidian AI plugins :)

**Comment by logancyang** [comment]
Will be addressed by https://github.com/logancyang/obsidian-copilot/issues/16
