### ISSUE TITLE
UI Seems Broken

### ISSUE THREAD

**Issue by hisaac** [logancyang/obsidian-copilot#201]
Hello,

I just tried to use Copilot for the first time, and the UI seems broken.

![CleanShot 2023-12-07 at 09 22 43@2x](https://github.com/logancyang/obsidian-copilot/assets/923876/ffbf5300-d4e7-460e-92ae-670c63e03a22)

Any idea why that might be happening? I don't have any other plugins installed, and the only UI tweak I've made is to change the font for notes.

**Comment by logancyang** [comment]
Hi @hisaac , thanks for reporting. Have you tried using the default themes and settings? Does it work in that case? Let me know, it may help narrow down the investigation.

From this screenshot, the Copilot CSS doesn't seem to be working at all. Anybody else seeing this?

**Comment by hisaac** [comment]
Same issue with all the UI settings set to defaults 😞

![CleanShot 2023-12-08 at 09 09 12@2x](https://github.com/logancyang/obsidian-copilot/assets/923876/2d17ef00-75a0-4bd3-83fd-b0698bb82e16)

And I can confirm I don't have any custom CSS enabled.

Is there a way I can see some debug logging for the plugin somehow?

**Comment by logancyang** [comment]
Hmm this is a first. Is this a fresh Obsidian and plugin install? You could open the dev console and inspect the elements to check if there's anything overridden. Normally it should load the plugin's styles.css. Not sure what conflict was introduced somehow. I just tried a fresh obsidian and plugin install and the plugin chat panel looks fine to me 🧐

**Comment by hisaac** [comment]
I tried to poke around to see if anything was amiss, but nothing stuck out to me. I haven't done web dev in a long time, so it definitely could just be that I don't know what I'm looking at.

I don't see any errors in the console, and nothing obvious looks wrong in the element inspector. The one thing I see is that the only CSS being loaded comes from `app.css`, nothing directly Copilot related. Is that expected?

![CleanShot 2023-12-13 at 04 22 05@2x](https://github.com/logancyang/obsidian-copilot/assets/923876/4e1df6d5-04e5-45f5-acc1-27d14c1c0855)
