### ISSUE TITLE
Build Type Error

### ISSUE THREAD

**Issue by Srimaan215** [logancyang/obsidian-copilot#204]
I keep running this error when trying to to build:

In file included from /Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.grpc.pb.cc:5:
In file included from /Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:26:
In file included from /opt/homebrew/include/google/protobuf/generated_message_bases.h:18:
In file included from /opt/homebrew/include/google/protobuf/message.h:105:
In file included from /opt/homebrew/include/google/protobuf/descriptor.h:44:
In file included from /opt/homebrew/include/absl/container/btree_map.h:56:
In file included from /opt/homebrew/include/absl/container/internal/btree.h:72:
/opt/homebrew/include/absl/types/compare.h:56:22: warning: 'enable_if' is a clang extension [-Wgcc-compat]
      __attribute__((enable_if(n == 0, "Only literal `0` is allowed."))) {}
                     ^
In file included from /Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.grpc.pb.cc:5:
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:41:1: error: unknown type name 'PROTOBUF_NAMESPACE_OPEN'
PROTOBUF_NAMESPACE_OPEN
^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:42:1: error: expected unqualified-id
namespace internal {
^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:45:1: error: unknown type name 'PROTOBUF_NAMESPACE_CLOSE'
PROTOBUF_NAMESPACE_CLOSE
^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:51:16: error: no member named 'PROTOBUF_NAMESPACE_ID' in the global namespace
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_backend_2eproto;
             ~~^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:99:1: error: unknown type name 'PROTOBUF_NAMESPACE_OPEN'
PROTOBUF_NAMESPACE_OPEN
^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:100:1: error: expected unqualified-id
template<> ::backend::EmbeddingResult* Arena::CreateMaybeMessage<::backend::EmbeddingResult>(Arena*);
^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:101:45: error: use of undeclared identifier 'Arena'
template<> ::backend::GenerateImageRequest* Arena::CreateMaybeMessage<::backend::GenerateImageRequest>(Arena*);
                                            ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:102:38: error: use of undeclared identifier 'Arena'
template<> ::backend::HealthMessage* Arena::CreateMaybeMessage<::backend::HealthMessage>(Arena*);
                                     ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:103:40: error: use of undeclared identifier 'Arena'
template<> ::backend::MemoryUsageData* Arena::CreateMaybeMessage<::backend::MemoryUsageData>(Arena*);
                                       ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:104:64: error: use of undeclared identifier 'Arena'
template<> ::backend::MemoryUsageData_BreakdownEntry_Dtemplate<> ::backend::MemoryUsageData_BreakdownEntry_Dtemplate<> ::backend::MemoryUsageData_BreakdownEntry_DoNotUse* Arena::CreateMaybeMessage<::backend::MemoryUsageData_BreakdownEntry_DoNotUse>(Arena*);
                                                               ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:105:37: error: use of undeclared identifier 'Arena'
template<> ::backend::ModelOptions* Arena::CreateMaybeMessage<::backend::ModelOptions>(Arena*);
                                    ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:106:39: error: use of undeclared identifier 'Arena'
template<> ::backend::PredictOptions* Arena::CreateMaybeMessage<::backend::PredictOptions>(Arena*);
                                      ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:107:30: error: use of undeclared identifier 'Arena'
template<> ::backend::Reply* Arena::CreateMaybeMessage<::backend::Reply>(Arena*);
                             ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:108:31: error: use of undeclared identifier 'Arena'
template<> ::backend::Result* Arena::CreateMaybeMessage<::backend::Result>(Arena*);
                              ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:109:39: error: use of undeclared identifier 'Arena'
template<> ::backend::StatusResponse* Arena::CreateMaybeMessage<::backend::StatusResponse>(Arena*);
                                      ^
/Users/Srimaan/LocalAI/LocalAI/backend/cpp/llama/llama.cpp/build/examples/grpc-server/backend.pb.h:110:35: error: use of undeclared identifier 'Arena'
template<> ::backend::TTSRequest* Arena::CreateMaybeMessage<::backend::TTSRequest>(Arena*);
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
7 warnings and 20 errors generated.
make[4]: *** [examples/grpc-server/CMakeFiles/hw_grpc_proto.dir/backend.grpc.pb.cc.o] Error 1
make[3]: *** [examples/grpc-server/CMakeFiles/hw_grpc_proto.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [grpc-server] Error 2
make: *** [backend/cpp/llama/grpc-server] Error 2
zsh: command not found: #
zsh: no such file or directory: ./local-ai

Anytime I try to run this in terminal:

make BUILD_TYPE=metal build

I get the error as shown above. Thanks for any help/advice, really appreciate it.

**Comment by logancyang** [comment]
Hi @Srimaan215, I recommend LM Studio instead of LocalAI now, it's much more user-friendly for our use case, no need to do those terminal gymnastics. Here's how to do it by @m0d02x https://github.com/logancyang/obsidian-copilot/discussions/191#discussioncomment-7794071

**Comment by Srimaan215** [comment]
Hey, thanks for the suggestion. Im much closer to actually getting the model to work, but I think this is the last step before it works. That said, Im not entirely sure the installation process for the model, and if I did it properly. Thanks for the help.

<img width="353" alt="issue" src="https://github.com/logancyang/obsidian-copilot/assets/89894459/48b64488-6b5e-49c5-b160-2eb61e89e62c">


<img width="1646" alt="server log" src="https://github.com/logancyang/obsidian-copilot/assets/89894459/1ebb8fe5-b704-4b4a-b490-21b98cfeb95e">
