### ISSUE TITLE
Turn off boiler plate response text after first run.

### ISSUE THREAD

**Issue by schwab** [logancyang/obsidian-copilot#206]
I admit, this is only a small announance, but in chat mode, the AI always prepends it's response with the boiler-plate code:
👋 Hi there! I'm Obsidian Copilot, a helpful assistant that integrates AI to Obsidian note-taking. 🧠📝 I can help you find information, create links, and even insert emojis to your content.

It would be nice if this would go away after the first prompt, both for brevity and for ease of copy pasting of results into your notes.  Since the copy feature always grabs that text, it's just one more thing that has to be manually deleted when you want to copy the response.

**Comment by logancyang** [comment]
Hi @schwab, do you see this in your every conversation? It shouldn't unless you explicitly ask what it can do. It's set in the system prompt and you can use whatever system prompt you like in the settings.
