### ISSUE TITLE
LangChain Error: model_not_found

### ISSUE THREAD

**Issue by reimic32** [logancyang/obsidian-copilot#21]
Hey, I get this error all the time. I have a subscription with ChatGPT, API Code is copied to Obsidian. Any ideas what the problem could be?

Thanks,
Mike

**Comment by logancyang** [comment]
@reimic32 Can you paste the full console error as well? Which model are you using, is it GPT4?

A common misunderstanding I see is that people think they have access to GPT-4 API when they get ChatGPT plus subscription. That is not true. You still need to get access to GPT-4 API to use the GPT-4 model in this plugin. Can you check if you can successfully use your model in the OpenAI playground? https://platform.openai.com/playground?mode=chat&model=gpt-4
