### ISSUE TITLE
cannot read properties of undefined(reading 'text')

### ISSUE THREAD

**Issue by acforu** [logancyang/obsidian-copilot#211]
用的是azure api，无法将笔记作为context，并提示报错
![image](https://github.com/logancyang/obsidian-copilot/assets/3379984/36f612fe-1969-443e-90e1-110510f3efa2)

**Comment by cfx2020** [comment]
I encountered the same problem. In the console, I found that it was because the vector library was pointing to the official "https://api.openai.com/v1/embeddings" instead of my API base url.
![image](https://github.com/logancyang/obsidian-copilot/assets/60496874/974c7feb-c7af-4f7e-97b3-d8defa6d99bc)

**Comment by logancyang** [comment]
This should be fixed next. @cfx2020 May i ask what 3rd party API you are using? It may help me debug in the future.

**Comment by logancyang** [comment]
@acforu Hey I'd like to understand your case more. Did you use Azure as chat model, or did you use the `OpenAI Proxy Base URL` setting? If you select Azure as chat model instead of using the proxy, did you also select Azure OpenAI as embedding provider?
<img width="796" alt="Screenshot 2023-12-29 at 2 07 15 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/489e992f-5dc2-4f7e-8e4a-36f6b65b5737">

In your case I guess you used `OpenAI Proxy Base URL` @cfx2020

**Comment by cfx2020** [comment]
> This should be fixed next. @cfx2020 May i ask what 3rd party API you are using? It may help me debug in the future.
oh，i am Chinese，so i have to use 3rd party API. Maybe you can try to sign up for this[https://ngedlktfticp.cloud.sealos.io/](site), it will be free for 20 USD.If you can't or don't want to register,You can provide the email address, I will send my APIkey to you

**Comment by logancyang** [comment]
@cfx2020 thanks for the link, looks like it's not free to use? 

BTW the embedding model should also use proxy now if it is set in the setting, just released v2.4.5, let me know if you still have an issue!

**Comment by cfx2020** [comment]
> @cfx2020 thanks for the link, looks like it's not free to use? 
> 
> BTW the embedding model should also use proxy now if it is set in the setting, just released v2.4.5, let me know if you still have a problem

You have to sign up to get $20. There will be a $20 credit to the wallet after signing up. You have to add a token to the token page to use it.

Thanks for the release, I will try now there are no bugs

**Comment by acforu** [comment]
> @acforu Hey I'd like to understand your case more. Did you use Azure as chat model, or did you use the `OpenAI Proxy Base URL` setting? If you select Azure as chat model instead of using the proxy, did you also select Azure OpenAI as embedding provider? <img alt="Screenshot 2023-12-29 at 2 07 15 PM" width="796" src="https://private-user-images.githubusercontent.com/4860545/293430145-489e992f-5dc2-4f7e-8e4a-36f6b65b5737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MjY2NzUsIm5iZiI6MTcwMzkyNjM3NSwicGF0aCI6Ii80ODYwNTQ1LzI5MzQzMDE0NS00ODllOTkyZi01ZGMyLTRmN2UtOGU0YS0zNmY2YjY1YjU3MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMDg1MjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVjNWVlOTZhOWViZDg5YWE5MmQwNzdlYzhkZTI3ZjRlY2Q2YjAzNjY0NDcwZjY0Mzk4NTQyZWQyMThjN2EzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pbEFt4OI135cFXLjvAcP6qMsrMgm959Pwu4AYenxZ8w">
> 
> In your case I guess you used `OpenAI Proxy Base URL` @cfx2020

I use Azure as chat model, and has never modified openai proxy base URL (Should I leave it blank? ),   I has selected the Azure Openai as embedding provider.

**Comment by logancyang** [comment]
@acforu yes you should leave it blank. But make sure you have all the Azure credentials correct. 
<img width="735" alt="Screenshot 2024-01-02 at 2 14 32 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/abcbe8e3-a94f-4dd7-a106-ebbc3857ecbc">

you can first test using a curl command like this
```
curl "https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=YOUR_API_VERSION \
 -H "Content-Type: application/json" \
 -H "api-key: YOUR_API_KEY" \
 -d "{
 \"messages\": [{\"role\":\"system\",\"content\":\"You are an AI assistant that helps people find information.\"}],
 \"max_tokens\": 800,
 \"temperature\": 0.7,
 \"frequency_penalty\": 0,
 \"presence_penalty\": 0,
  \"top_p\": 0.95,
  \"stop\": null
}"
```

**Comment by acforu** [comment]
> @acforu yes you should leave it blank. But make sure you have all the Azure credentials correct. <img alt="Screenshot 2024-01-02 at 2 14 32 PM" width="735" src="https://private-user-images.githubusercontent.com/4860545/293799063-abcbe8e3-a94f-4dd7-a106-ebbc3857ecbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzIzOTYsIm5iZiI6MTcwNDM3MjA5NiwicGF0aCI6Ii80ODYwNTQ1LzI5Mzc5OTA2My1hYmNiZThlMy1hOTRmLTRkZDctYTEwNi1lYmJjMzg1N2VjYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTI0MTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZmNTk5ZjU5ZWZhMWJiNTNmYzI3NjFmOWY2YThlODcwYjEwZGVmY2Q2NGIwY2UzNDNmNmZhOGEwMDdhM2Y4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9oTQcTKoiEASQgniKcyQPwzrkCUQPL9g5uEXlb3ie4g">
> 
> you can first test using a curl command like this
> 
> ```
> curl "https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=YOUR_API_VERSION \
>  -H "Content-Type: application/json" \
>  -H "api-key: YOUR_API_KEY" \
>  -d "{
>  \"messages\": [{\"role\":\"system\",\"content\":\"You are an AI assistant that helps people find information.\"}],
>  \"max_tokens\": 800,
>  \"temperature\": 0.7,
>  \"frequency_penalty\": 0,
>  \"presence_penalty\": 0,
>   \"top_p\": 0.95,
>   \"stop\": null
> }"
> ```

I can use it in conversation mode, it seems like Azure credentials is all right, but I did not provide embedding model deployment name, does  QA mode need it?
![image](https://github.com/logancyang/obsidian-copilot/assets/3379984/d11e6976-bcd2-490c-ae70-4fd47061c6ec)

**Comment by logancyang** [comment]
> > @acforu yes you should leave it blank. But make sure you have all the Azure credentials correct. <img alt="Screenshot 2024-01-02 at 2 14 32 PM" width="735" src="https://private-user-images.githubusercontent.com/4860545/293799063-abcbe8e3-a94f-4dd7-a106-ebbc3857ecbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzIzOTYsIm5iZiI6MTcwNDM3MjA5NiwicGF0aCI6Ii80ODYwNTQ1LzI5Mzc5OTA2My1hYmNiZThlMy1hOTRmLTRkZDctYTEwNi1lYmJjMzg1N2VjYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTI0MTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZmNTk5ZjU5ZWZhMWJiNTNmYzI3NjFmOWY2YThlODcwYjEwZGVmY2Q2NGIwY2UzNDNmNmZhOGEwMDdhM2Y4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9oTQcTKoiEASQgniKcyQPwzrkCUQPL9g5uEXlb3ie4g">
> > you can first test using a curl command like this
> > ```
> > curl "https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=YOUR_API_VERSION \
> >  -H "Content-Type: application/json" \
> >  -H "api-key: YOUR_API_KEY" \
> >  -d "{
> >  \"messages\": [{\"role\":\"system\",\"content\":\"You are an AI assistant that helps people find information.\"}],
> >  \"max_tokens\": 800,
> >  \"temperature\": 0.7,
> >  \"frequency_penalty\": 0,
> >  \"presence_penalty\": 0,
> >   \"top_p\": 0.95,
> >   \"stop\": null
> > }"
> > ```
> 
> I can use it in conversation mode, it seems like Azure credentials is all right, but I did not provide embedding model deployment name, does QA mode need it? ![image](https://private-user-images.githubusercontent.com/3379984/294183354-d11e6976-bcd2-490c-ae70-4fd47061c6ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODA3NzEsIm5iZiI6MTcwNDM4MDQ3MSwicGF0aCI6Ii8zMzc5OTg0LzI5NDE4MzM1NC1kMTFlNjk3Ni1iY2QyLTQ5MGMtYWU3MC00ZmQ0NzA2MWM2ZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTUwMTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU2OTNhYjY0OTE1MmVlZDM5NTY1NjBhZmZmNDk0NzQ0ZWRmNjU0MzU3NDc4MDEwMTcxMjk0ZTgyOWM2NjVjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.elIVQyknFDzxpp0ExbwW5qVAzJx97U5oj0kOrSCNrtY)

Yes. When you set Embedding Provider to Azure OpenAI, you need the embedding deployment name. As of v2.4.6 it should show this error in the console: 

```
Uncaught (in promise) Error: Azure OpenAI API deployment name not found
    at new OpenAIEmbeddings (plugin:copilot:69906:15)
```

I still need to show a better error message here. Created a new issue tracking it https://github.com/logancyang/obsidian-copilot/issues/221

**Comment by logancyang** [comment]
Let me know if this is still an issue with v2.4.14. Closing for now.
