### ISSUE TITLE
Open API Key not working

### ISSUE THREAD

**Issue by omullings** [logancyang/obsidian-copilot#214]
Steps to reproduce:
- Install plugin
- Enable plugin
- Go to options ( Plugin Settings )
- Login to Open AI API dashboard and create new secret key
- Copy Key to Your Open AI API key field
- Open Copilot in new note area ( Notice red font indicating error )
- Go to community plugins and reload plugins
- Go back to Copilot settings and confirm that key is still there
- Open new copilot in note area ( Notice red font indicating error )
- Go to file explorer to check .obsidian/plugins/copilot/data.json to check if JSON is valid and "openAIApiKey" property is filled in correctly and the JSON file is valid
- Check usage to see if credits have expired or if there are available credits ( Credit Grants $0.01/ $28.00 and Usage limit $0 / $10
- test api key in playground chat and get response
- turn on obdisian copilot debug setting
- open copilot ( text still red for error )
- Enter Hello
- Open the console
Console log
*** DEBUG INFO ***
user message: Hello
model: gpt-3.5-turbo-16k
temperature: 0.7
maxTokens: 1000
system message: You are Obsidian Copilot, a helpful assistant that integrates AI to Obsidian note-taking.
chat context turns: 3

Error
```
plugin:copilot:69969 Model request failed: TypeError: Cannot read properties of undefined (reading 'llm')
    at isLLMChain (plugin:copilot:58547:16)
    at isSupportedChain (plugin:copilot:58553:10)
    at AIState.runChain (plugin:copilot:60904:10)
    at getAIResponse (plugin:copilot:69961:19)
    at handleSendMessage (plugin:copilot:70051:11)
    at handleKeyDown (plugin:copilot:70064:7)
    at HTMLUnknownElement.callCallback2 (plugin:copilot:36020:22)
    at Object.invokeGuardedCallbackDev (plugin:copilot:36045:24)
    at invokeGuardedCallback (plugin:copilot:36079:39)
    at invokeGuardedCallbackAndCatchFirstError (plugin:copilot:36082:33)
```
Screenshots
![Screenshot 2023-12-29 at 2 28 52 AM](https://github.com/logancyang/obsidian-copilot/assets/1619081/d46837aa-1d42-4779-87a6-35f17d7b87d4)
![Screenshot 2023-12-29 at 2 28 58 AM](https://github.com/logancyang/obsidian-copilot/assets/1619081/49dba278-0415-4878-ace8-2324b8e84104)

**Comment by logancyang** [comment]
hmm, if anyone else met with this issue please let me know. Can you try 2 things @omullings 

1. Test using curl in your terminal following this instruction and see if you get a response back: https://platform.openai.com/docs/quickstart?context=curl
2. If 1 works, try resetting the Copilot settings, restart the plugin, and enter the API key again. 

If the above still doesn't work, try switching between Conversation and QA mode and show me what the console says

**Comment by logancyang** [comment]
Closing this one after v2.4.6 with better error handling. If there's new errors feel free to open a new issue.
