### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by kurko** [logancyang/obsidian-copilot#216]
Installed 2.4.5 and the plugin is not working at all. Just random code errors in the console. Screenshot below.

<img width="916" alt="Screenshot 2023-12-30 at 15 53 45" src="https://github.com/logancyang/obsidian-copilot/assets/70312/5ab894fe-6594-4c01-93f7-8235fcecdeca">

---

Here I'm changing the model set to see if that helps, but nope:

<img width="916" alt="Screenshot 2023-12-30 at 15 54 10" src="https://github.com/logancyang/obsidian-copilot/assets/70312/aea115b9-9e96-4199-9f57-e1f07278049e">

You can see the API Key is present.
<img width="620" alt="Screenshot 2023-12-30 at 15 54 24" src="https://github.com/logancyang/obsidian-copilot/assets/70312/e9684d50-1794-4f6f-8021-8223d9ced779">

I'm not using Azure, so no idea why the error about Azure key missing.

**Comment by logancyang** [comment]
Hmm that's weird, I did a clean reinstall and it worked for me, not sure what's different. Have you tried resetting the settings and restarting the plugin? @kurko Let me know!

**Comment by igrybkov** [comment]
@logancyang I had the same issue after installing the plugin and setting up the API key. Restarting Obsidian indeed helped to resolve it, but it's weird that it didn't work from the clean start (I didn't have this plugin until today).

**Comment by logancyang** [comment]
Closing this one after v2.4.6. If new errors occur feel free to open a new issue.
