### ISSUE TITLE
Sending empty body in local llm

### ISSUE THREAD

**Issue by crislerwin** [logancyang/obsidian-copilot#223]
## Steps to reproduce
- Start a server on Local LM
- Set a local model on  Copilot Obsidian
- Sent a prompt
![empty_body](https://github.com/logancyang/obsidian-copilot/assets/82983797/146a60b7-aad3-4527-a9c7-e680713c30b5)

**Comment by logancyang** [comment]
Hi @crislerwin, I'm not sure what you mean by "set a local model". To use LM Studio, the only thing you need to do is start the local LM studio server with CORS on, and put that local server URL such as `http://localhost:1234/v1` into OpenAI Proxy Base URL in Advanced copilot settings. Keep any OpenAI model in the model dropdown and it works without doing anything else.
<img width="1673" alt="Screenshot 2024-01-07 at 7 58 44 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/5366a98e-04a0-4565-a68d-9e80895a5bb3">

I'm going to move away from LocalAI and toward LM Studio and Ollama next. The settings will be less confusing.

**Comment by crislerwin** [comment]
@logancyang Sorry, I was a little confused in the explanation, what I meant by: "set local llm", was to select the local llm on plugin.
