### ISSUE TITLE
You do not have access to this model

### ISSUE THREAD

**Issue by crainbf** [logancyang/obsidian-copilot#227]
Hi, 
I'm trying to use the plugin, but unfortunately, I keep getting this error:

> You do not have access to this model or the model does not exist, please check with your API provider.

Note, that I have chatGPT plus. I created the API keys and entered them in the plugin and reloaded. It also shows on the openAI that the API was actually used. So it does seem like the plugin is calling the API. I also tried a bunch of stuff like set new API keys, restart Obsidian, etc.

Appreciate any guidance.

**Comment by logancyang** [comment]
Hi @crainbf, can you check here to see if it works in your openai playground: https://github.com/logancyang/obsidian-copilot?tab=readme-ov-file#-faq-please-read-before-submitting-an-issue

If it works in your playground, can you turn on debug mode, screenshot the entire chat panel and the dev console, I can take a look.

**Comment by logancyang** [comment]
Closing this now. Feel free to reopen if the issue persists.
