### ISSUE TITLE
allow token limit > 8000 tokens

### ISSUE THREAD

**Issue by rushikb** [logancyang/obsidian-copilot#232]
HI there, 
I absolutely love this plugin (discovered it too late) and the way you've approached the design.  Is there a way to increase the context length to >8000 words given GPT 4 turbo's allowable length?

**Comment by logancyang** [comment]
hi @rushikb, absolutely! Will update this in the next release!

**Comment by logancyang** [comment]
I've bumped the max token limit to 10000 in the [latest release](https://github.com/logancyang/obsidian-copilot/releases/tag/2.4.9). Since this controls the **output** token limit, I think this should be plenty for most use cases. Setting it too high will limit the length of the prompt.
