### ISSUE TITLE
LM Studio error: " 'messages' field is required"  [m1 mac and windows 11]

### ISSUE THREAD

**Issue by pale2hall** [logancyang/obsidian-copilot#233]
I tried setting up obsidian-copilot plugin in obsidian 1.5.3 on W11, and I'm not sure the versions on M1 Macbook Pro.

Same error, lmk if I can help with more debugging.  Cors is OFF, I tried to follow directions.

```
[2024-01-11 15:36:11.420] [INFO] [LM STUDIO SERVER] Processing queued request...
[2024-01-11 15:36:11.420] [INFO] Received OPTIONS request to /v1/chat/completions with body: {}
[2024-01-11 15:36:11.420] [ERROR] 'messages' field is required
```

_P.S. if You would like obsidian debug logs, lmk how to get them.  I can't figure out where to find logs or console or inspect element, etc in Obsidian._

**Comment by logancyang** [comment]
Hi @pale2hall, you can open the dev console by `ctrl + shift + i` on windows or `cmd + opt + i` on mac. You can turn on debug mode in the Copilot setting and check what's in the console.

For LM Studio's local server you need CORS on, or Obsidian won't be able to access it. Here's a setup guide: https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md

**Comment by pale2hall** [comment]
Thank you.  My mistake entirely.  I thought CORS = OFF meant the enforcing CORS was OFF. 
Thank you again.

**Comment by logancyang** [comment]
Glad you got it working! 🎉
