### ISSUE TITLE
"To answer your question, I would need to access the information in your Obsidian vault."

### ISSUE THREAD

**Issue by truszko1** [logancyang/obsidian-copilot#235]
Is this broken or I'm doing something wrong? I thought setting up this plugin would be this simple?

<img width="766" alt="Screenshot 2024-01-12 at 17 03 14" src="https://github.com/logancyang/obsidian-copilot/assets/10970127/da2fd575-7aaf-4940-8a8a-f4975c22a659">

<img width="959" alt="Screenshot 2024-01-12 at 17 04 04" src="https://github.com/logancyang/obsidian-copilot/assets/10970127/b2d30f2a-0f2b-401e-95ae-75db3e5631d2">

**Comment by logancyang** [comment]
Hi @truszko1 thanks for trying it out, I just tried this and it worked. What embedding provider did you use?

![SCR-20240112-ohqw](https://github.com/logancyang/obsidian-copilot/assets/4860545/3254459a-0ec3-4b16-ba36-74fc0b85a82f)

My guess is the embeddings are not good enough so the note content is not properly retrieved in your case. I'm still in search of a good local embedding service, Ollama's local embedding looked promising but didn't perform well enough. For now I'm still sticking to OpenAI or Cohere embeddings, but TogetherAI looks good so I might add that soon.

Plus, I'm adding a feature to directly stuff multiple notes into the prompt directly in Chat mode without the need of a vector search. It will behave in a much more predictable way.

**Comment by truszko1** [comment]
Thanks for responding! Did I miss a note in a readme? I did not touch any embedding options. If I use inning embedding services, doesn’t that defeat the purpose of offline obsidian and offline llm? I feel like I’m missing something! 😂

**Comment by truszko1** [comment]
@logancyang 
I see that LocalAI embedding was available before but it’s been removed in recent versions. I don’t really want to use an online embedding service. I wish there was a local alternative even if I have to run my own service.

**Comment by logancyang** [comment]
@truszko1 right, I removed it since the setup was too involved for most people and the performance was also a huge issue. In all existing browser/electron supported local embedding providers I've tried, there's no apparent winner so far. I'm trying to make transformer.js work in Obsidian's electron environment but have hit some major roadblocks. Will report back if I get that working.

**Comment by truszko1** [comment]
@logancyang 
gotcha! So... right now, the only option is online-based embeddings? I am a very technical dev, so if you happen to have any docs or notes I could use, I'd be willing to try it out, I wouldn't mind!
Or if you want help, I'm down for that, too, although don't call me an AI expert 🤣 

Either way, thanks for the clarification, and thanks for making this plugin!! nice work!

**Comment by logancyang** [comment]
@truszko1 thanks for offering help! Will document some specific issues and link back here if you are interested in working on them 🙏

**Comment by truszko1** [comment]
I tried running with `HuggingFaceTransformersEmbeddings` locally, instead of `HuggingFaceInferenceEmbeddings`, but _wow_ I ran into Node/Electron/env issues... =/

**Comment by logancyang** [comment]
> I tried running with `HuggingFaceTransformersEmbeddings` locally, instead of `HuggingFaceInferenceEmbeddings`, but _wow_ I ran into Node/Electron/env issues... =/
> 
> I figured `HuggingFaceTransformersEmbeddings` should be easy lol

@truszko1 yeah this is the issue I was facing, couldn't make `HuggingFaceTransformersEmbeddings`'s dependency `Xenova/transformers` work with Obsidian's esbuild, and always got this error

```
// node_modules/@xenova/transformers/src/env.js
var __dirname = RUNNING_LOCALLY ? import_path.default.dirname(import_path.default.dirname(import_url.default.fileURLToPath(import_meta.url))) : "./";

Error:
Plugin failure: copilot TypeError: The "path" argument must be of type string or an instance of URL. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at Object.fileURLToPath (node:internal/url:1491:11)
    at anonymous (plugin:copilot:89293:110)
    at e.<anonymous> (app.js:1:2026677)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
```

**Comment by logancyang** [comment]
Linking the draft PR: https://github.com/logancyang/obsidian-copilot/pull/245

Opened issues for help on both langchainjs and transformers.js.

**Comment by truszko1** [comment]
It's so funny how you and I both arrived at the exact same place!
