### ISSUE TITLE
The Gemini Pro model cannot engage in a conversation with notes

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#236]
Whether using the CohereAI trial API key or the Hugging Face Inference API key

**Comment by logancyang** [comment]
It's probably because your embeddings are not created properly, it could be errors from Cohere or Huggingface, you can doublecheck in the dev console if there's any error.

Here's an example when it works. Usually it's the embedding. For now, the best and most stable embedding provider is still OpenAI.
<img width="1725" alt="SCR-20240116-nlsy" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/5f01e82e-feb8-4c5c-9796-edf3e1229e80">

**Comment by wwjCMP** [comment]
Please note that this is a retrieval-based QA for notes longer than the model context window. Specific questions are encouraged. For generic questions like 'give me a summary', 'brainstorm based on the content', Chat mode with Send Note to Prompt button used with a long context model is a more suitable choice.


(This mode will be upgraded to work on the entire vault next)

**give me a summary**

Sure, here is a summary of Obsidian Copilot, a helpful assistant that integrates AI to Obsidian note-taking:


Obsidian Copilot is an AI-powered assistant that helps you take notes, organize your thoughts, and generate new ideas. It integrates seamlessly with Obsidian, a popular note-taking app, to provide you with a range of features that can help you be more productive and creative.


Key Features:



AI-Powered Note Completion: Obsidian Copilot can help you complete your notes by suggesting relevant information and insights. As you type, it will provide suggestions based on your previous notes, the context of your current note, and your research.
Intelligent Summarization: Obsidian Copilot can summarize your notes, helping you to quickly identify the key points and insights. This can be especially useful when you are reviewing your notes or preparing for a presentation.
Idea Generation: Obsidian Copilot can help you generate new ideas by providing you with prompts and suggestions. This can be helpful when you are brainstorming or trying to come up with new solutions to problems.
Seamless Integration with Obsidian: Obsidian Copilot is designed to work seamlessly with Obsidian. It is a plugin that you can install in Obsidian, and it will then be available to you whenever you are taking notes.

Benefits:



Increased Productivity: Obsidian Copilot can help you to be more productive by providing you with intelligent suggestions and insights. This can help you to take better notes, organize your thoughts more effectively, and generate new ideas more easily.
Improved Creativity: Obsidian Copilot can help you to be more creative by providing you with new perspectives and ideas. This can help you to come up with new solutions to problems, develop new products or services, and create new works of art.
Enhanced Learning: Obsidian Copilot can help you to learn more effectively by providing you with summaries and insights. This can help you to retain information more easily, understand complex concepts more deeply, and apply your knowledge to new situations.

Overall, Obsidian Copilot is a powerful tool that can help you to take better notes, organize your thoughts more effectively, generate new ideas, and learn more efficiently.


I hope this summary is helpful. Please let me know if you have any other questions.

**Comment by logancyang** [comment]
@wwjCMP this is because the retrieval didn't retrieve anything. As the bot mentioned:

> Please note that this is a retrieval-based QA for notes longer than the model context window. Specific questions are encouraged. For generic questions like 'give me a summary', 'brainstorm based on the content', Chat mode with Send Note to Prompt button used with a long context model is a more suitable choice.

So for now, questions like "give me a summary" should be asked in Chat mode after clicking the little up button to send the active note to prompt. But as the QA bot mentioned, the QA mode will be upgraded soon.

**Comment by logancyang** [comment]
Closing this for now as it's covered by the note context in the new Chat mode. New QA mode is also coming soon.
