### ISSUE TITLE
QA: ACTIVE NOTE Not Working, Paritcularly not being able to access and answer question about active note despite saying that it can answer questions about the active note. 

### ISSUE THREAD

**Issue by flowingblaze** [logancyang/obsidian-copilot#239]
I am on windows ten and using LM studio with the copilot plugin. I have set up LM studio according to the documentation and I tried ot use QA Active Note with two notes: one for 2024-01-16 and my 2023 yearly note. I figured that maybe the yearly note might've been too big for the plugin as it kept saying that "okay, ask me questions about [[2023]]" and then proceeding to say that It didn't have access to my personal notes and instead just started putting up random points unrelated to my yearly note. so I tired it with my small daily note for that day and it didn't say anything about not having access the first time I asked by then it stared summarizing 2024-01-17 (before that date) stating "**Apple Announces New Products**: Apple Inc. held an event where they introduced several new products including the iPhone SE (3rd generation), a new MacBook Pro, and updates to the iPad Air and iPad Mini. (Source: Apple)" before I stopped it. I didn't mention anything about any kind of Apples (tech or the food) in my daily note. I tried again and it said "To summarize the data from your notes on January 16, 2024 (Tuesday), I would need to access and analyze the content of those specific notes. However, based on the general context of a Tuesday in January 2024, here's a potential summary"

**Comment by flowingblaze** [comment]
i tried to use the summarize selection prompt on something that has nothing to do with anarchism, reddit, or protonmail but rather a note about a food i like. I'm saying this because this result is extremely confusing and probably a glitch or some kind. 
![image](https://github.com/logancyang/obsidian-copilot/assets/107226733/461bee97-7324-45c1-bd50-7ad2d5218940)

**Comment by logancyang** [comment]
Is it possible for you to record your screen for a couple of seconds to show how you get this and share here? I don't get how that could happen.

If you can, turn on debug mode in Copilot setting and open the dev console in your screenshot too.

**Comment by flowingblaze** [comment]
Unfortunately it isn't, sorry.  I will try to get a screenshot of the dev console today.

**Comment by logancyang** [comment]
Hi @flowingblaze , I've released a new version, can you see if this is still reproducible?

**Comment by logancyang** [comment]
Closing this now. Feel free to reopen if the issue persists.
