### ISSUE TITLE
Use Ollama on remote machine

### ISSUE THREAD

**Issue by jeremiahsb** [logancyang/obsidian-copilot#247]
I may have missed something, but from what I can tell of the documentation and the parameters, Obsidian Copilot is expecting the Ollama instance to be local to the machine running Obsidian. It would be fantastic to have the option to specify the location of the Ollama instance.

**Comment by logancyang** [comment]
Let me add this in the next release.

**Comment by logancyang** [comment]
Just released v2.4.11 with this setting
