### ISSUE TITLE
[FR] Support ChatGLM3  local models

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#249]
ChatGPT-3 is an outstanding open-source model suitable for local deployment. It would make Copilot more powerful if calls to it were supported.

https://github.com/THUDM/ChatGLM3

**Comment by logancyang** [comment]
@wwjCMP I can't sign up somehow. Any instructions for running it locally? I do see some small chatglm3 options in LM Studio, you can run those there. But the new GLM4 must be via their API and I couldn't sign up without a Chinese phone number. Their sign up with foreign phone number option didn't work.

**Comment by wwjCMP** [comment]
Is the following link what you need?
https://github.com/THUDM/ChatGLM3/blob/main/README_en.md

https://www.bilibili.com/video/BV1c34y1w75K/?spm_id_from=333.337.search-card.all.click&vd_source=4da716c2c9e733b14045d5c5b12eb8c1 （Simple one-click deployment；in Chinese）

**Comment by logancyang** [comment]
@wwjCMP thanks! Will look into these soon
