### ISSUE TITLE
Langchain max 4096 completion tokens error when using GPT-4 Turbo (128k) on custom prompt

### ISSUE THREAD

**Issue by oscaromsn** [logancyang/obsidian-copilot#256]
When trying to apply a custom prompt to a selected text, the error "LangChain error: Error: 400 max_tokens is too large: 10000. This model supports at most 4096 completion tokens, whereas you len provided 10000" is returned. However, the API selected in the settings is GPT-4 Turbo, with a context window of 128k. I've tried changing the API to the regular GPT-4 and then reverting back to GPT-4 Turbo, reapplying the settings, but the problem persists.

ps: congratulations for your amazing work!

**Comment by logancyang** [comment]
Hi @oscaromsn, thanks for using the plugin! GPT-4-TURBO indeed only has a [max 4096 output tokens](https://community.openai.com/t/gpt-4-128k-only-has-4096-completion-tokens/515790), it's 128K context window is mostly for input tokens. So unfortunately, this error is expected.

**Comment by oscaromsn** [comment]
oh, I understand now - you are absolutely right! thank you for the clarification!
