### ISSUE TITLE
[FR] Explore potential bi-directional link

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#257]
As the QA mode will be upgraded to work on the entire vault, please add a function that discovers and analyzes the potential related files of the selected text or article through semantic analysis.

**Comment by logancyang** [comment]
Thanks for the suggestion, I've been thinking about how to make the experience simple and seamless. In any case this is a necessary component for whole vault QA.

**Comment by logancyang** [comment]
Relevant issues:
- https://github.com/logancyang/obsidian-copilot/issues/331
- https://github.com/logancyang/obsidian-copilot/issues/326
