### ISSUE TITLE
AzureOpenAI API doesn't work in version 2.4.13

### ISSUE THREAD

**Issue by thinkthinking** [logancyang/obsidian-copilot#259]
AzureOpenAI API doesn't work in version 2.4.13

![image](https://github.com/logancyang/obsidian-copilot/assets/61035602/cdea45e1-bb44-4a13-84ac-9dce35c5bca5)

**Comment by logancyang** [comment]
@thinkthinking I have a GPT-4-32K deployment in Azure and it's working correctly for me. Can you 

1. double-check your Azure credentials in settings, correct the deployment name, then save and reload
2. if 1 did not work, reset copilot settings to default and enter them again

**Comment by logancyang** [comment]
ok so you have Azure OpenAI as embedding provider. Looking into it

**Comment by logancyang** [comment]
can you try the new release v2.4.14 and see if it fixes your issue? @thinkthinking

**Comment by logancyang** [comment]
Closing this now. Feel free to reopen if the issue persists.

**Comment by thinkthinking** [comment]
> can you try the new release v2.4.14 and see if it fixes your issue? @thinkthinking

@logancyang thanks, it works well in v2.4.15.
