### ISSUE TITLE
LM Studio local is not called on Windows

### ISSUE THREAD

**Issue by bietiekay** [logancyang/obsidian-copilot#260]
**Describe the bug**
I selected LM Studio (local) as the model yet the console output in obsidian keeps saying that an OpenAI key is not set/invalid. The LM Studio server is started and can be called with commandline. It does not show any requests coming in from copilot. 

**To Reproduce**
Installed freshly, set model to LM Studio and Port to 1234. 

**Expected behavior**
I expect Copilot to call the LM Studio server, instead it seems to try to call OpenAI.

**Screenshots**
added screenshots showing console and settings of obsidian copilot plugin.
![Pasted image 20240126100443](https://github.com/logancyang/obsidian-copilot/assets/219032/c4f48e48-65e2-4922-8dc9-0c18b66322f6)
![Pasted image 20240126100422](https://github.com/logancyang/obsidian-copilot/assets/219032/2f6944a1-1c85-45d4-98d8-4cc4470b6f88)
![Pasted image 20240126100411](https://github.com/logancyang/obsidian-copilot/assets/219032/7c13f970-6b2c-4636-adfd-d872f53a3d34)
![Pasted image 20240126100355](https://github.com/logancyang/obsidian-copilot/assets/219032/a24915f9-993c-460a-92b0-c230bd59832c)

**Additional context**

**Comment by bietiekay** [comment]
using windows 10, all current versions

**Comment by logancyang** [comment]
@bietiekay I can reproduce, can you try putting a random string in OpenAI API key? I'm fixing this issue in the next patch.

**Comment by bietiekay** [comment]
hmm I did try the random string in openapi key and it did not change the behaviour - will try again.

**Comment by logancyang** [comment]
@bietiekay can you try the new release v2.4.14 and see if it fixes your issue?

**Comment by logancyang** [comment]
Closing this now. Feel free to reopen if the issue persists.

**Comment by bietiekay** [comment]
sorry for the delay - I can confirm the bug to be fixed - I am just now back to the computer.
