### ISSUE TITLE
[FR] In QA mode, add the ability to ask questions about multiple selected files.

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#262]
Although the QA mode will be upgraded to work on the entire vault later, I hope to retain the function of asking questions about specific files because for LLM, more accurate input means more accurate answers. I hope to keep this function so that users have greater control over choosing the input reference content.

Also, I hope to add the ability to ask questions about multiple files. Currently, questions are asked about a single file, but typically in Obsidian notes, content on the same topic tends to be distributed across multiple files. Asking questions about a single file has significant limitations.

**Comment by logancyang** [comment]
Thanks for the suggestion! In the new modes I'm cooking,

- Chat: the "up" button defaults to sending the active note to prompt, but the context can be set with a Copilot command modal where you can provide a folder of notes (or filter by tags if possible)
- QA Vault: similar to the above, there's a modal where you can set the context you index, default to the entire vault

So then you have the ability to

1. Filter notes with your own criteria
2. Pass those filtered notes to either directly pass them to prompt (Chat), or do RAG over them (QA)

**Comment by wwjCMP** [comment]
There's another issue, it seems like LLM doesn't receive the information in block quotes? I use block quotes a lot in Obsidian to organize my notes.

**Comment by logancyang** [comment]
@wwjCMP block quote with `>`, and in Chat mode? Yeah it does, you can turn on debug mode and see the full prompts for everything.

<img width="1026" alt="SCR-20240127-jxhv" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/4e0f68f3-6652-45a5-8b23-5f7e172bbfdd">

**Comment by wwjCMP** [comment]
I'm sorry I didn't describe it correctly, what I meant is the block embed . 

![[file#^jskjfkfaj]]

**Comment by logancyang** [comment]
@wwjCMP gotcha, that it does not support right now but there's actually a PR for embedded pdf and txt files sitting there for a while. I will add it after finishing the new modes. Let me know what else you'd like to include.

**Comment by logancyang** [comment]
BTW I'm releasing the feature to send multiple notes directly to prompt in Chat mode today https://github.com/logancyang/obsidian-copilot/pull/265

You can specify the folder path with a command. This is the first version of a specifiable note context for Chat mode, potentially addition will come later such as filter by tags, or even by note links if people think that's a good idea.

**Comment by luketech85** [comment]
I also hope that you will retain the function of asking questions about specific files. I work with a lot of public domain books (as single notes) and using the QA search is an incredibly amazing feature. Hopefully won't lose the ability to do that when you add different modes. 

Sounds like there will be two QA mode options:

1) QA (we can use with a single note or collection of notes)
2) QA Vault

If I understand correctly?

Thanks!

**Comment by logancyang** [comment]
@luketech85 yes, we will have 3 modes: Chat, Long Note QA, Vault QA

**Comment by logancyang** [comment]
As we now have Chat mode with context setting, Long Note QA and Vault QA, closing this one now. Index exclusion list is coming.
