### ISSUE TITLE
[FR] Add prompt templates functionality in the Chat Window

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#267]
The current prompt templates ask questions based on the selected content, hoping to provide prompt templates functionality in the Chat Window for quick conversation based on the current context of the dialogue.

**Comment by logancyang** [comment]
@wwjCMP Do you mean something like

1. Pick saved custom prompts from a modal
2. One click to send it to chat input field for you to type out more stuff below it before sending to LLM?

If this is what works, perhaps just adding a command `Add Custom Prompt to Chat` with the existing list of custom prompts for selection could be enough?

Let me know if you have some specific UX in mind!
