### ISSUE TITLE
Add ability to save and load chat sessions easily

### ISSUE THREAD

**Issue by archvalmiki** [logancyang/obsidian-copilot#268]
What: Ability to save and load sidebar chat sessions.  

Potential solution: the ability to load a chat transcript MD that was previously saved and continue later. 

Nice to have: the ability to have multiple chat instances open at the same time (sometimes as I am conversing with the model, I need to do a side lookup/convo and currently it's not possible and requires me to use other tools.)

**Comment by logancyang** [comment]
Yes this has been on my roadmap for a while. Will prioritize this after I ship the new modes.

**Comment by archvalmiki** [comment]
Thank you.  Keep up the good work!!!!  Appreciate what you are doing.

**Comment by peterlionelnewman** [comment]
Thanks Logan, potentially as well, an option in the plugin's menu/config that would 'autosave' each note in your 'copilot-conversations' (or whatever you renamed it to), when you click new chat

**Comment by jkjoker** [comment]
感觉聊天记录中也应该保存时间戳，因为时间戳是很重要的一部分信息，谢谢
