### ISSUE TITLE
[EPIC FR] Using canvas to create a flowchart for automated questioning

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#271]
Obsidian already has some plugins that utilize canvas for flowchart creation to achieve (semi) automated execution. Examples include:

- Cannoli: https://github.com/DeabLabs/cannoli
- ZettelFlow: https://github.com/RafaelGB/Obsidian-ZettelFlow
- Chat Stream: https://github.com/rpggio/obsidian-chat-stream
Some locally deployed large models also provide modular programming assistance for users to implement simple automation through questioning. I wonder if it's possible to add similar functionality to Copilot.

For instance, using canvas to create a simple flowchart. Due to token limitations, it's not possible to send a large number of files to LLM all at once. Here's a proposed workflow:

1. Have the large model read a portion of information and provide a preliminary response to the questions.
2. Read in another set of information and incorporate the response from the previous step. Combine the two sets of information to generate a comprehensive answer.
3. Repeat the process until all provided file contents are read.

While such questioning can be done manually, having a modularized canvas workflow could save a significant amount of effort. This is just a simple example, and with effective modules, users can unleash their creativity to create customized questioning workflows. I believe this could make large models a valuable assistant for managing a large volume of notes.

**Comment by logancyang** [comment]
@wwjCMP Thanks for providing those plugins, I'll look into them. If I understand correctly, you want to use Canvas as a no-code tool to build an arbitrary "langchain-like" chain? What you described looks like a Summary chain that does incremental summaries at each step and provides answers.

I think this is super interesting, looks like an epic feature for power users, and may have some learning curve. Adding it to the roadmap for further discussions.

Coming back to the exact use case you described, I think it can be achieved with a "conversation summary memory" and some manual back-and-forth chatting. I've been wanting to add this "summary memory" for a while, it basically summarizes the previous chat messages to compress the info at each turn. This way you can manually send subsets of files at a time and achieve what you described in Chat mode. It is a lossy compression though, so some important points may get lost in this process. I'm thinking of add it as a toggle in Copilot settings `Enable summarization of previous messages and avoid reaching the context window limit`, something like that.

**Comment by wwjCMP** [comment]
Yes, it's like langchain or even more like the new langgraph

**Comment by logancyang** [comment]
Linking a relevant discussion https://github.com/logancyang/obsidian-copilot/discussions/300

**Comment by wwjCMP** [comment]
https://github.com/benjycui/bisheng
https://github.com/FlowiseAI/Flowise
https://www.bilibili.com/video/BV1pu4y1k72Z/?spm_id_from=333.337.search-card.all.click&vd_source=4da716c2c9e733b14045d5c5b12eb8c1
Some related implementations

**Comment by wwjCMP** [comment]
https://github.com/langflow-ai/langflow
