### ISSUE TITLE
[FR]Support AzureOpenAI gpt-4-1106-preview and gpt-4-vision-preview

### ISSUE THREAD

**Issue by thinkthinking** [logancyang/obsidian-copilot#273]
@logancyang Could you please support gpt-4-1106-preview and gpt-4-vision-preview?

<img width="589" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/61035602/c10169fd-03f6-478a-a824-67999c487611">

**Comment by logancyang** [comment]
@thinkthinking this looks like azure, in that case once you set your deployment name in the setting, it doesn't matter what azure model you pick in the dropdown, it's all just using that model from your deployment name. It's quite misleading to set all those different azure models in the dropdown. I'll remove them next and only leave one `Azure OpenAI`.
