### ISSUE TITLE
Please support mobile device

### ISSUE THREAD

**Issue by chisungbae** [logancyang/obsidian-copilot#275]
**Is your feature request related to a problem? Please describe.**
This plugin is really useful to enhance productivity.
Please support mobile device too.

**Comment by logancyang** [comment]
Hey @chisungbae , thanks for the FR, this is on my roadmap. I'll prioritize it once the revamp is released. Stay tuned!

**Comment by loerzi** [comment]
Hey @logancyang great to hear that mobile support is coming! Thanks for the great plugin!

**Comment by nickfixit** [comment]
Moviley!🙏

**Comment by hughlett** [comment]
Thanks for your work @logancyang!

#8, #52, and #162 could be closed as duplicates now

**Comment by logancyang** [comment]
Please refer to #532 to follow along. Closing this as duplicate.
