### ISSUE TITLE
[Feature] ability to rename prompts

### ISSUE THREAD

**Issue by crypdick** [logancyang/obsidian-copilot#279]
**Is your feature request related to a problem? Please describe.**

It's possible to edit a prompt, but it is not possible to rename a prompt. You have to delete the note and create it again with a new name.

**Describe the solution you'd like**

Ability to rename a prompt in the edit page.

**Describe alternatives you've considered**

I tried to rename the prompts manually, but I can't find where they are actually stored.

**Comment by logancyang** [comment]
Hi @crypdick, thanks for the FR. Currently it's a simple schema where id is the title, so you can't rename them and have to recreate them. Ofc adding an editable title is possible but it will require schema migration for all users, and it needs to make sure all titles are unique with separate logic. 

There are currently higher priority tasks so I'll come back to this one after. Putting this one up as a good first issue if anyone is interested.

**Comment by nicolas-g** [comment]
+1

**Comment by logancyang** [comment]
Now that custom prompts are in markdown, editing title works. Reopen it you see errors.
