### ISSUE TITLE
[FR] Model name text input field

### ISSUE THREAD

**Issue by kctdfh** [logancyang/obsidian-copilot#294]
**Is your feature request related to a problem? Please describe.**
Some users have access to more models than others. 

**Describe the solution you'd like**
Allowing a free-form text input field for the "model" selector would allow those people to use the models they have access to and not have to wait for those models to be widely available. It'd also allow us to purposefully continue using an older version of a model.

**Comment by logancyang** [comment]
So probably a `model` should be added in Advanced Setting under `OpenAI Proxy Base URL`

**Comment by logancyang** [comment]
@kctdfh new release 2.4.18 added these overrides below, just make sure your model picker has OpenAI models, and these values will be used. Let me know if this works. Closing for now.

<img width="889" alt="SCR-20240221-tesh" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/708afab6-841a-46bb-9ea5-94ed3db3e469">
