### ISSUE TITLE
400 invalid model ID after switching from OpenRouter to other models

### ISSUE THREAD

**Issue by logancyang** [logancyang/obsidian-copilot#295]
**Describe the bug**
After switching from OpenRouter to OpenAI models in the dropdown, it sometimes trigger this error
<img width="885" alt="SCR-20240216-nknm" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/c9c789c4-d387-4286-918d-4f0da164ca9f">

**Comment by petery789** [comment]
Can't reproduce it when switching models.. Might just close it if we aren't able to constantly reproduce it. 
![Screen Shot 2024-02-22 at 2 20 09 PM](https://github.com/logancyang/obsidian-copilot/assets/8389897/7b1b9fb5-7b4c-4d21-a040-bede882be47a)

**Comment by logancyang** [comment]
@petery789 oh forgot to close this one, I fixed it.
