### ISSUE TITLE
Plugin not working 

### ISSUE THREAD

**Issue by arozehnal** [logancyang/obsidian-copilot#3]
Obsidian v1.2.7
Copilot  v.1.2
Valid API key, newly acquired GPT+

**First try - GPT-4**
**Console output.**
Failed to load resource: the server responded with a status of 404 ()
plugin:copilot:37818 Error in streamManager.streamSSE: 
CustomEvent
data: "{\n    \"error\": {\n        \"message\": \"The model: `gpt-4` does not exist\",\n        \"type\": \"invalid_request_error\",\n        \"param\": null,\n        \"code\": \"model_not_found\"\n    }\n}\n"
isTrusted: false
source: SSE2 {INITIALIZING: -1, CONNECTING: 0, OPEN: 1, CLOSED: 2, url: 'https://api.openai.com/v1/chat/completions', …}
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
detail: null
eventPhase: 0
path: []
returnValue: true
srcElement: null
target: null
timeStamp: 89358.5
type: "error"
[[Prototype]]: CustomEvent
getAIResponse	@	plugin:copilot:37818

**Second try - GPT 3.5
Console output**
Error in streamManager.streamSSE: 
CustomEvent {isTrusted: false, data: '{\n    "error": {\n        "message": "You exceeded …     "param": null,\n        "code": null\n    }\n}\n', source: SSE2, detail: null, type: 'error', …}
data: "{\n    \"error\": {\n        \"message\": \"You exceeded your current quota, please check your plan and billing details.\",\n        \"type\": \"insufficient_quota\",\n        \"param\": null,\n        \"code\": null\n    }\n}\n"
isTrusted: false
source: SSE2 {INITIALIZING: -1, CONNECTING: 0, OPEN: 1, CLOSED: 2, url: 'https://api.openai.com/v1/chat/completions', …}
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
detail: null
eventPhase: 0
path: []
returnValue: true
srcElement: null
target: null
timeStamp: 29311
type: "error"
[[Prototype]]: CustomEvent
detail: (...)
initCustomEvent: ƒ initCustomEvent()
constructor: ƒ CustomEvent()
Symbol(Symbol.toStringTag): "CustomEvent"
bubbles: (...)
cancelBubble: (...)
cancelable: (...)
composed: (...)
currentTarget: (...)
defaultPrevented: (...)
eventPhase: (...)
path: (...)
returnValue: (...)
srcElement: (...)
target: (...)
timeStamp: (...)
type: (...)
get detail: ƒ detail()
[[Prototype]]: Event

**Comment by logancyang** [comment]
From your error messages it seems you don't have access to GPT4 yet? The gpt3.5 error seems to read that there's something exceeded, could be that your message is too long or something, hard to tell without the full message.

Were you able to get a response from gpt 3.5 with a simple "hello"?

I'm currently traveling and don't have my computer with me. Let me know if you manage to get a response, or I can take a look when I get back.

**Comment by arozehnal** [comment]
The response with a simple "hello" message from gpt3.5 is OK now.

See an attachment/console log  for "hello" message. from gpt4.
[gpt4_helllo_console.txt](https://github.com/logancyang/obsidian-copilot/files/11424190/gpt4_helllo_console.txt)

**Comment by logancyang** [comment]
Thanks for providing the console messages. Can you please confirm that you have access to GPT-4 by going to https://platform.openai.com/playground?mode=chat&model=gpt-4 and get some response there? Let me know!

Also I've been seeing issues where GPT-4 API is simply down and returning 500. Currently I have to make the OpenAI failure messages better in this plugin to make it easier to troubleshoot.

**Comment by logancyang** [comment]
Just made a new release 1.2.1 with better error message like this, can you update the plugin and check the error message again? Let me know if more details are needed in troubleshooting OpenAI issues.

<img width="883" alt="Screenshot 2023-05-10 at 4 27 36 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/874a06c1-2a56-49ca-9530-c5b39253fc7d">

**Comment by arozehnal** [comment]
WWW page  https://platform.openai.com/playground?mode=chat&model=gpt-4  reports ->  The model: `gpt-4` does not exist
I misunderstood about the OpenAI subscription, I probably need to sign up for the whitelist, right?

**Comment by logancyang** [comment]
> WWW page https://platform.openai.com/playground?mode=chat&model=gpt-4 reports -> The model: `gpt-4` does not exist I misunderstood about the OpenAI subscription, I probably need to sign up for the whitelist, right?

Yes, you don't automatically get access to the GPT4 API by buying ChatGPT Plus, you still need to sign up for the waitlist afaik.
