### ISSUE TITLE
API Key should be stored crypted

### ISSUE THREAD

**Issue by davideriboli** [logancyang/obsidian-copilot#301]
**Is your feature request related to a problem? Please describe.**
API-Key is stored locally, but if I pull my vault to GitHub, is easily readable. It should be great to have it stored crypted in some way.

**Describe the solution you'd like**
Crypt the API-Key.

**Describe alternatives you've considered**
Delete plugin before pulling vault on line (not real a solution) or writing a git-ignore file (of course, this should work only in GitHub).

**Comment by alepez** [comment]
A different approach is to delegate storing keys to an external command. For instance, check how neovim chatgpt is doing: https://github.com/jackMort/ChatGPT.nvim

**Comment by logancyang** [comment]
New release 2.4.18 added encryption option in setting, toggle it on and your keys are encrypted. Let me know if anything breaks. Closing for now.
