### ISSUE TITLE
Request for Function: In QA mode, directly use long content without relying on the embedding technique.

### ISSUE THREAD

**Issue by uniartisan** [logancyang/obsidian-copilot#314]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

In local mode, QA still requires embedding API billing. Since open source large models now also support ultra-long context, it is possible to pass long text QA directly.

**Describe the solution you'd like**
Directly ask the artificial intelligence about the entire content of the document, or you can select part of the content

**Describe alternatives you've considered**

**Additional context**

**Comment by logancyang** [comment]
What you described is actually available in Chat mode without anything to do with embeddings. You have 2 ways to pass long content to the prompt:

1. Using the little "up" button `Send Note(s) to Prompt` in Chat mode. It by default passes the active note to the prompt and starts a QA session. You can also use the Copilot command `set note context in Chat mode` to filter out multiple notes by path or a list of tags to send all of them to the prompt with 1-click.

2. Using templating in user custom prompt. 
<img width="607" alt="SCR-20240225-ltsw" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/c60fb609-0df3-4178-a996-1d4678d062bc">

Looks like I should create a video tutorial on this. Will post it soon!

**Comment by logancyang** [comment]
Please refer to this video: https://youtu.be/VPNlXeCsH74?si=XhkpVDX-K-wPyAMv

Closing for now.
