### ISSUE TITLE
(LOGAN PLEASE HELP!!! )Despite high hopes for this plug-in, Multiple screenshots confirm the contrary :( 

### ISSUE THREAD

**Issue by ReliablyAwkward** [logancyang/obsidian-copilot#319]
I created an entirely new vault just to test this plug-in, I only have one note inside, and it has failed at every test to communicate accordingly. I am running Google advanced API w/ the embedding API from cohere. At one point it was saying cannot connect to the internet, another it was saying it cannot read my vault, and now it has all these in addition to those, what on earth is going on here?

 I really want to enjoy this feature, but lordy lord, this has gotten rather redundant now hasn't it. (Regarding time efficiency)
![Completely inaccurate](https://github.com/logancyang/obsidian-copilot/assets/135422842/7b32808f-e51f-4c26-af45-69b3f66cc94f)
![Randomly complete different language](https://github.com/logancyang/obsidian-copilot/assets/135422842/c6b5bdfa-3f68-4adc-83f9-cb132a27191e)
![Why 2 ](https://github.com/logancyang/obsidian-copilot/assets/135422842/b3e38930-c7a4-44e6-8f97-f85de727deba)
![Why 3](https://github.com/logancyang/obsidian-copilot/assets/135422842/d2a1f973-ec91-4824-8eda-7dec7ea53f88)

**Comment by logancyang** [comment]
Hi @ReliablyAwkward, thanks for reporting. Let me address your screenshots one by one.

1. Directly mentioning `[[note title]]` isn't support in Chat mode yet. You need to use the small "up" button to send your active note or a context with multiple notes (set with command) to the model.
2. Not sure why it replied in Spanish, does your note contain Spanish? Or it could just be Gemini hallucinating.
3. I can't see what the model said, but it shows you successfully passed the active note.
4. I see a 500 error, this is internal to Google's API and has nothing to do with the plugin. As directed, you may report it to Google using that link

In general the issue I see is with Gemini, can you try with another model? GPT-4-TURBO is the benchmark and can probably eliminate model-specific issues. If you don't have OpenAI access, you can also try OpenRouter for free models.

**Comment by ReliablyAwkward** [comment]
Yes I have been taking your first instruction but when I do that it says no context found. There is zero and I mean zero in my note regarding Spanish. And I don't understand regarding number four, I have a Gemini Advanced 2-month trial for which I see API key access, yet when I look at your model selection it says Gemini "PRO", are these not the same thing? I tried resetting my API key there, and I'm still dead in the water over here regarding just even trying to get your plug-in off the ground.

**Comment by ReliablyAwkward** [comment]
(crickets)

**Comment by logancyang** [comment]
@ReliablyAwkward In my previous reply point 1: it **does NOT support** mentioning a note like that in Chat directly, your screenshot is still a direct mention. You have to use the little up button or templating in Chat mode like shown in my videos. 

However, the new release Vault QA mode v2.5.0 should work for direct mentions. That new mode also supports completely offline QA with the ollama local embeddings. A new video on that will be up this week.

**Comment by ReliablyAwkward** [comment]
> @ReliablyAwkward In my previous reply point 1: it **does NOT support** mentioning a note like that in Chat directly, your screenshot is still a direct mention. You have to use the little up button or templating in Chat mode like shown in my videos.
> 
> However, the new release Vault QA mode v2.5.0 should work for direct mentions. That new mode also supports completely offline QA with the ollama local embeddings. A new video on that will be up this week.

Brother, I have been doing this, please see attachments in order, I have been using the little up button from the beginning, in both modes I have tried and tried, for Pete's Peppers, all I want is to communicate w/ my vault as a singular data set.

I made an isolated vault just to test your plug-in only, no other plug-in is clashing w/ it, literally zero friction is on this vault except for your plug-in, I only have one note in this vault and it cannot for some reason communicate whatsoever :( :(

![1](https://github.com/logancyang/obsidian-copilot/assets/135422842/667df3c5-bbae-4865-8eff-c4a0bbe44ce9)
![2](https://github.com/logancyang/obsidian-copilot/assets/135422842/9000e986-91cf-47ba-a85a-4be1ce33348b)
![3 1](https://github.com/logancyang/obsidian-copilot/assets/135422842/3a315df8-9a5e-41e1-bbb5-535d5b88c157)
![4](https://github.com/logancyang/obsidian-copilot/assets/135422842/c28a8d8e-fa8b-4265-b0b5-7bfde86ca70e)
![5](https://github.com/logancyang/obsidian-copilot/assets/135422842/1f6f30be-59d8-4b50-ba74-505240117418)

**Comment by logancyang** [comment]
- From your 2nd screenshot the AI did not response after you clicked the button, that means your call failed. Can you do this again but include your dev console in the screenshot too
- From your 3rd and 4th screenshots, it amazes me how Gemini said `[[ICI]]` out of nowhere. What's your temperature setting? It's purely hallucinating.

BTW, in QA mode, pls ask more specific questions as the bot mentioned. 

This kind of questions are bad 👎 : `talk to me about [[note title]]`, `summarize this article` 

These are better 👍 : `what does a cerebral vacation mean`, `what are the insane chain of bold claims`

**Comment by ReliablyAwkward** [comment]
*In order of advice*
![0](https://github.com/logancyang/obsidian-copilot/assets/135422842/b19d0622-c0d6-4e54-b64d-82a9e92ccdad)
![1](https://github.com/logancyang/obsidian-copilot/assets/135422842/46cc12f2-35aa-471c-aa98-067cf7965ac2)
![2](https://github.com/logancyang/obsidian-copilot/assets/135422842/a3390d33-a93c-4df4-81b1-0abf44000bf3)
![3](https://github.com/logancyang/obsidian-copilot/assets/135422842/d447de39-c404-4b5e-9f72-ae38a7ede5be)

**Comment by ReliablyAwkward** [comment]
Okay I did as you said, and yes indeed, I did have many of those three lines in a row, I replaced every single one w/ dots instead, so now there are zero of those dashes anywhere in the note, try it again and the snapshot shows the result.
![after subtraction of the 3 lines](https://github.com/logancyang/obsidian-copilot/assets/135422842/4024072f-67c3-4c34-b3aa-7162367f26b7)

**Comment by logancyang** [comment]
> Okay I did as you said, and yes indeed, I did have many of those three lines in a row, I replaced every single one w/ dots instead, so now there are zero of those dashes anywhere in the note, tried it again and the snapshot shows the result. ![after subtraction of the 3 lines](https://private-user-images.githubusercontent.com/135422842/311176557-4024072f-67c3-4c34-b3aa-7162367f26b7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MzMzODEsIm5iZiI6MTcwOTkzMzA4MSwicGF0aCI6Ii8xMzU0MjI4NDIvMzExMTc2NTU3LTQwMjQwNzJmLTY3YzMtNGMzNC1iM2FhLTcxNjIzNjdmMjZiNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQyMTI0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTRhYWEzNmY0OGFmMWQ1ZGQ2N2EwZGRiODc3ODA3YWNjMjY2YzZiNWJjOGE0YWU5MWE4ZDUzOTMxMDI4MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rR5EYnxa35mdN03_yXyh5OcRWjeE9gBgoVW2ugfVjxU)

This time it's 500 internal error from Google, not sure what's happening on their side. You could report to them using that link they provided. I believe I saw it once or twice before too but Gemini is working for me now. Could it be your account issue? But if it's because of payment or access they should really return 403 and not 500 🤷‍♂️

**Comment by ReliablyAwkward** [comment]
I believe you, but I have zero clue what you are saying. I grasp that it is an error on Google Gemini's part and not your plug-in, but, I did do exactly as you said and removed the lines, and it threw this code last time even before that adjustment. My account w/ them is in good standing, I just tried it again and this is the gibberish it gives me back. Why does it seem like the rest of the world is enjoying your plug-in except me, lol :( :( :(
![I WANT TO ENJOY YOUR PLUGIN](https://github.com/logancyang/obsidian-copilot/assets/135422842/458abe45-12a7-4ad1-a54e-01dd6ced5774)

**Comment by logancyang** [comment]
Have you tried OpenRouter? They have a big collection of models and a free quota. 

As for Google, make sure you can use Gemini in Google AI Studio first https://aistudio.google.com/app/u/1/prompts/new_chat

Find their support people and show them this 500 internal error message is your best bet.

I can't even use Google AI Studio without getting an error, huge bummer
<img width="2004" alt="SCR-20240308-mngn" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/3a82a4fe-c68d-4beb-8049-b817a6e00079">

**Comment by ReliablyAwkward** [comment]
> Have you tried OpenRouter? They have a big collection of models and a free quota.
> 
> As for Google, make sure you can use Gemini in Google AI Studio first https://aistudio.google.com/app/u/1/prompts/new_chat
> 
> Find their support people and show them this 500 internal error message is your best bet.
> 
> I can't even use Google AI Studio without getting an error, huge bummer <img alt="SCR-20240308-mngn" width="2000" src="https://private-user-images.githubusercontent.com/4860545/311379215-3a82a4fe-c68d-4beb-8049-b817a6e00079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MzU5NDksIm5iZiI6MTcwOTkzNTY0OSwicGF0aCI6Ii80ODYwNTQ1LzMxMTM3OTIxNS0zYTgyYTRmZS1jNjhkLTRiZWItODA0OS1iODE3YTZlMDAwNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMjIwNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY5MWViZWI2M2UxNzVmZWIwYWU4M2VkZmUwODdhY2MxODQ2YTNkNmFhNTVmM2U1YjA4OGE2ZTBjN2Y1YmEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9WFcWgc0iDAeRTgNRtOz83k7AfZCjBYrTMHl8_8M_Iw">

No I have never messed w/ open router because I got sick of the runaround a while ago trying to find something that my machine can handle.

I'm not about to start chasing my tail w/ Google support now, lol

I just tried that same window that your snapshot showed and got the exact same error. 

Are you in Los Angeles by any chance?

**Comment by ReliablyAwkward** [comment]
So you're telling me I can just copy paste this api's from open router (Claude 3) into your plugins box and, voila?

**Comment by ReliablyAwkward** [comment]
I did that, made the adjustments, Saved and reloaded, now this: 
![Screenshot 2024-03-08 144056](https://github.com/logancyang/obsidian-copilot/assets/135422842/de88db83-dd6e-4bd3-af24-622e8314734c)

**Comment by logancyang** [comment]
what model are you using for OpenRouter? Next time you see a 3-digit error code, just google it. 402 is "payment required". You are probably using a paid model, they have free ones, check their website https://openrouter.ai/docs#models

**Comment by ReliablyAwkward** [comment]
Claude Sonet....Oh my goodness their list is like infinite, I don't even know where to begin w/ something like this. (le' sigh)....Dude I will like pay you to remote set this up or something, I am so at my wit's end w/ all this run around.

**Comment by ReliablyAwkward** [comment]
SO CLOSE!!! I started using the free API key and drop it gives you, and voila, it's the first time I've seen it react positively whatsoever! It was completely understanding the note I was giving it, when I was in chat mode I was able to reference another note, phenomenal. I asked it to give me a particular note and a dissertation style and Claude III came through like a charm. 

Then I switched to the big boy, which if you remember I said I created a whole new vault just for this, and then I copy paste it over about 10 notes, and tried using the Vault QA Mode, And it threw me a bunch of error codes, mentioning openai again which I don't really understand since, the embedding API is cohere and the regular one is now Claude, so, I went back and deleted my API key from openai all together, refreshed everything, and these snapshots are what it comes back w/.

 At first it was just stuck at indexing, then I changed like I said above, and then it started working but now it's just stuck at that last snapshot, it says 10 out of 11 notes indexed, what's going on?
 
 
![Baby steps](https://github.com/logancyang/obsidian-copilot/assets/135422842/d2d50625-a953-4e02-9515-3873b46bed65)
![FEELS SO CLOSE!](https://github.com/logancyang/obsidian-copilot/assets/135422842/e80d5ac5-bcd6-4dc6-a8c6-d5525730c9f1)
![what changed](https://github.com/logancyang/obsidian-copilot/assets/135422842/155cca19-de74-49e6-ace5-21e13904c2d1)

**Comment by logancyang** [comment]
@ReliablyAwkward The answer is in the screenshot: your Cohere embedding API says it only allows 10 calls/minute for the free trial key (which is weird, my free Cohere API key allows much more than that, could be because I signed up very early and got a lot more quota?).

This means you can't use Cohere free key to index the whole vault. For your big vault, you either get a paid Cohere key, or go the OpenAI route. Free and local option is Ollama, just go through the Ollama setup guide:https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md#ollama

**Comment by ReliablyAwkward** [comment]
> Free and local option is Ollama, just go through the Ollama setup guide:https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md#ollama

""[Ollama](https://ollama.ai/) currently supports Mac and Linux, they mentioned that Windows is coming soon.""

I am on a 10 year old Toshiba Satellite laptop, running windows 10.

**Comment by logancyang** [comment]
@ReliablyAwkward 
<img width="1241" alt="SCR-20240310-nkcv" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/cbf7652b-b8b6-427d-a8b9-13a879a6813e">

But your machine probably can't handle Ollama unfortunately 😬

Your best bet is to pay for OpenAI or Cohere

**Comment by ReliablyAwkward** [comment]
Oh my goodness, okay, per your recommendation I will entertain the idea of this.  I was actually thinking about getting the full opus version of Claude for at least one month, I am curious though, would your vault mode negate the need to create one long file for macro context?  Is it literally no difference? Because for example, my big gripe is that I have over 2.5 million words that I need considered as One Singular data set, so I was thinking originally, since Claude has such a high token limit, I would copy paste a ton/merge a ton of notes into one file for it to communicate w/. But now I feel redundant since your vault mode would just sidestep this and make that obsolete altogether?

 Also, what do you consider best between cohere and openai? I personally would rather avoid openai altogether, but do you see a benefit/risk to this?

**Comment by logancyang** [comment]
@ReliablyAwkward there's no need to create one long file. You have 2 options

1. Use Chat mode with the command `Set note context for chat mode`, where you can set `/` as the folder, meaning including your entire vault in your single prompt (**this is ofc going to be expensive! I would only do this once for testing purposes**), then use the little up button to pass the context to the prompt. For real use cases, I recommend setting a specific folder with a few notes for this.
2. Use Vault QA mode. Keep in mind that all embedding providers have rate limiting (429 error code), meaning if you call them too frequently you'll get blocked for a while. Indexing a large vault can lead to this. If you get stuck with 429, just wait a bit and do "refresh index", it will resume the indexing process.

**Comment by ReliablyAwkward** [comment]
Okay I've been playing w/ it like crazy, from my experience, the best way to access the entire vault is by referencing it from chat mode instead, when I put it in vault mode it seems to choke. But I can't put my finger on exactly where that's coming from because it gives me a 429 error code from anthropic even though it's been an entirely full day since I last messed w/ it last. I have 79 cents left in my $5 free trial which should be more than enough for a simple prompt. I switched over to Gemini Pro which I really don't like in comparison to Claude, And tried using vault mode and long Q&A mode, and gave it a prompt of referencing other notes for contrast and it gets all types of confused. 

But when I just leave it in chat mode and then reference the other notes, it seems to do fine?

 I didn't really understand what you meant w/ the whole, "Command set note context for chat mode" And then using the /, if you remember I said I created an entirely new vault for this, And unlike the other similar plug-in called smart connections, when I would use a / or hit the bracket key it would automatically pull up a list of options that would be available for that particular syntax, But I think what you meant was, I can reference an entire folder that way if I have everything I want organize enough, so it's like a microvolt inside a vault because all I ever think about evolved is that it's one hell of a giant folder. Anyway....
 
Entertain the idea of cohere, I've been trying to look into the topic but I am just so far away from the axioms regarding definitions of many of the words this realm seems to utilize.  I am just so scared of spending the money and then all of a sudden I run into some similar hiccup, it's going to make my head explode if that's the case, I want to remember that I have a 2.5 million word vault that I would love to be represented as a singular data set, so you're saying cohere can both handle the task and  doesn't have the same 429 error code Jazz as The more popular boys like anthropic and openai?
![Compressed file couldn't handle it](https://github.com/logancyang/obsidian-copilot/assets/135422842/fac09f92-5ce9-4140-ba67-efff17195c9d)

**Comment by ReliablyAwkward** [comment]
Would it be possible to do like a 20 minute q&A virtual call with you at
some point? I can just like I don't know, venmo you or something like that
if you want to bill me for your time? I just have so many questions about
how to go about utilizing this plugin in the most efficient manner.

**Comment by ReliablyAwkward** [comment]
Regarding your advice about no need to put everything into one note because of your vault mode, I respectfully beg to differ. I have been testing and testing and, it seems to be yanking from sources arbitrarily, when I need it to yank from specific sources. So even though I have extended the source limit to 10, I have way more than 10 sources I wish for it to take into consideration. Therefore, it seems vault mode is something like negate it all together, When someone is attempting to address a larger than 10 sources?

**Comment by ReliablyAwkward** [comment]
???

**Comment by ReliablyAwkward** [comment]
Hello?
