### ISSUE TITLE
OLLAMA_ORIGINS=app://obsidian.md* ollama serve how does it  run in windows os 

### ISSUE THREAD

**Issue by blandcoder** [logancyang/obsidian-copilot#322]
**what  can i do**
the doc local_copilot.md that have  a  command:
`OLLAMA_ORIGINS=app://obsidian.md* ollama serve`
that is  a  shell command of  mac  or Linux.
so i can`t  used local  model in copilt-plgin.
I only  know that Linux or mac can access application   send arg.
I am using windows os. what can i do ?
thanks, have a good day!!!

**Comment by logancyang** [comment]
Hi @blandcoder, there's a section for the new windows preview https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md

<img width="1230" alt="SCR-20240229-lhuw" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/5bb3f89c-492e-4b8b-8c52-8eaff4fef105">

Let me know how it works!

**Comment by blandcoder** [comment]
It works very well ! thank you very  much! **Have a good day bro!**
