### ISSUE TITLE
Unable to Read Active Notes in QA mode

### ISSUE THREAD

**Issue by six-finger** [logancyang/obsidian-copilot#325]
**Describe the bug**
Always say sorry.

**To Reproduce**
win 11

**Screenshots**
![image](https://github.com/logancyang/obsidian-copilot/assets/34418117/cbb4ccc7-58e9-40dd-bf87-dba01129957b)

**Comment by logancyang** [comment]
Your vector store creation must have failed and it should have a notice popped up. You can open the console and check the error message.

**Comment by six-finger** [comment]
thanks a lot!(the notice popped up and disappeared very quickly)

**Comment by six-finger** [comment]
But it says **Error:401 Incorrect API key provided**. However, I can use Chat Mode.
![image](https://github.com/logancyang/obsidian-copilot/assets/34418117/f0c01058-b104-4f59-a6c6-d2d7727df8aa)

**Comment by logancyang** [comment]
This happened to me once as well but I couldn't reproduce it. Probably some hiccup on OpenAI API side. Can you retry.

**Comment by itribs** [comment]
I encountered the same error, and I am using the local OLLAMA.
