### ISSUE TITLE
Embedding is not using custom API proxy

### ISSUE THREAD

**Issue by ckt1031** [logancyang/obsidian-copilot#332]
**Describe the bug**

It uses OpenAI API even I have set custom OpenAI embedding host.

![image](https://github.com/logancyang/obsidian-copilot/assets/65409152/30b6e76b-da78-41c1-89b1-8154ef4991af)

**To Reproduce**

Set the embedding proxy UR in configuration tab.

**Expected behavior**

It should use proxy host.

**Comment by logancyang** [comment]
Any recommended provider for me to use in testing? It would be best if you guys could list the top API providers you use for all the LLMs, free is even better

**Comment by ckt1031** [comment]
> Any recommended provider for me to use in testing? It would be best if you guys could list the top API providers you use for all the LLMs, free is even better

Which model you need? I can provide some OpenAI Embeddings model and limited Anthropic/4 Turbo usage.

**Comment by logancyang** [comment]
> > Any recommended provider for me to use in testing? It would be best if you guys could list the top API providers you use for all the LLMs, free is even better
> 
> Which model you need? I can provide some OpenAI Embeddings model and limited Anthropic/4 Turbo usage.

That sounds great! The more the merrier

**Comment by logancyang** [comment]
Could you try new release v2.5.1 and see if it fixes your issue

**Comment by ckt1031** [comment]
> Could you try new release v2.5.1 and see if it fixes your issue

![image](https://github.com/logancyang/obsidian-copilot/assets/65409152/09c8f918-8f2d-46a5-bb66-90e680a2dbde)

It's fine now
