### ISSUE TITLE
plugin running on system windows reported error

### ISSUE THREAD

**Issue by szx-zhao** [logancyang/obsidian-copilot#333]
I'm running the Ollama service on Windows, and I'm wondering how to enable the Obsidian plugin to retrieve data correctly. I'm getting an error in the console that says `Access to fetch at 'http://127.0.0.1:11434/api/chat' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`, Meanwhile, requests received at ollama Server `[GIN] 2024/03/05 - 23:46:03 | 403 |            0s |       127.0.0.1 | OPTIONS  "/api/chat"` are .I'm not sure how to resolve it.

**Comment by logancyang** [comment]
@szx-zhao have you checked the setup guide https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md

**Comment by szx-zhao** [comment]
> @szx-zhao have you checked the setup guide https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md

Thanks, I ran the `setx OLLAMA_ORIGINS "app://obsidian.md*"` command in windows shell and the issue seems to be resolved now
