### ISSUE TITLE
LM Studio - Failed to create vector store, embedding API is not set correctly, please check your settings

### ISSUE THREAD

**Issue by aagha** [logancyang/obsidian-copilot#335]
**Describe the bug**
I'm using LM Studio and running zephyr beta 7B and get the following error in Obsidian when using Copilot:

"Failed to create vector store, embedding API is not set correctly, please check your settings"

**To Reproduce**
- Install LM Studio
- Download and select Zephyr Beta 7B model
- Select Local model in the Copilot plugin

**Expected behavior**
Able to query against entire Vault

**Screenshots**
![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/2874a9e8-027a-4e30-9bc3-f47c6441996b)
![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/b5501cb4-844c-4cb7-b77a-ae7504acfa91)
![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/145dc84c-344e-4847-b664-a24d7be266fd)
![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/70cc1869-ac7e-4952-a945-bac1057bdba5)

**Additional context**

**Comment by aagha** [comment]
I also just installed the latest version of Copilot (v 2.5.0)

![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/4b594eb8-9627-4326-b6af-ffe87124de3f)

And when selecting the vault and hitting "Index", it's not clear any indexing is happening

![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/12cd5493-cdc1-408c-878b-0fb8d06a9759)

**Comment by logancyang** [comment]
What you are missing is your embedding API. I don't see your QA settings, I guess you probably haven't set up your embedding. Indexing relies on embeddings.

The default is openai embedding small model and it's paid, you need your OpenAI key in settings. Or you can use Ollama for local embeddings. Check the local copilot setup guide for how to set it up.

**Comment by aagha** [comment]
Ah!

Since I had LM Studio going, I didn't even bother to put in an OpenAPI key--I've now done that:

![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/92672645-4577-4b7f-bd96-239386210aa0)

What do you recommend selecting from here?

![image](https://github.com/logancyang/obsidian-copilot/assets/5522103/f438049e-fe7f-485a-a75c-becefb8e6f64)

**Comment by logancyang** [comment]
small is a decent start, it's quite cheap too, $0.02/1M tokens. Ollama is not as good from my personal testing, but it's free and local. If you don't mind paying more to OpenAI, large is going to be the best.

**Comment by logancyang** [comment]
Closing this one. For people who see this, please go through the setup guide in this video: https://youtu.be/NSoKRYNlOls?si=-WFVEY_vWN08oJVn first. If there's still issue please include your chat and console in your screenshot.

**Comment by Arlorean** [comment]
In my case, even though I've set it to use **LM STUDIO (LOCAL)** it still seems to be trying use the Ollama server port number for embeddings. I watched your video but you didn't mention LM Studio in it, that I noticed or saw in the transcript.

![image](https://github.com/user-attachments/assets/c3305638-721d-45fa-9b11-6e7868407ef9)
![image](https://github.com/user-attachments/assets/7f12ff64-5d63-4df1-9fd9-45c82ae5922a)

```json
{
  "openAIApiKey": "",
  "huggingfaceApiKey": "",
  "cohereApiKey": "",
  "anthropicApiKey": "",
  "anthropicModel": "claude-3-sonnet-20240229",
  "azureOpenAIApiKey": "",
  "azureOpenAIApiInstanceName": "",
  "azureOpenAIApiDeploymentName": "",
  "azureOpenAIApiVersion": "",
  "azureOpenAIApiEmbeddingDeploymentName": "",
  "googleApiKey": "",
  "openRouterAiApiKey": "",
  "openRouterModel": "cognitivecomputations/dolphin-mixtral-8x7b",
  "defaultModelDisplayName": "LM STUDIO (LOCAL)",
  "embeddingModel": "ollama-nomic-embed-text",
  "temperature": 0.1,
  "maxTokens": 1000,
  "contextTurns": 15,
  "userSystemPrompt": "",
  "openAIProxyBaseUrl": "",
  "openAIProxyModelName": "",
  "openAIEmbeddingProxyBaseUrl": "",
  "openAIEmbeddingProxyModelName": "",
  "ollamaModel": "llama2",
  "ollamaBaseUrl": "",
  "lmStudioBaseUrl": "http://localhost:1234/v1",
  "stream": true,
  "defaultSaveFolder": "copilot-conversations",
  "indexVaultToVectorStore": "ON MODE SWITCH",
  "qaExclusionPaths": "",
  "chatNoteContextPath": "",
  "chatNoteContextTags": [],
  "debug": true,
  "enableEncryption": false,
  "maxSourceChunks": 3
}
```
