### ISSUE TITLE
Unable to use Vault QA - "An error occurred while re-indexing vault to vector store"

### ISSUE THREAD

**Issue by Welding-Torch** [logancyang/obsidian-copilot#340]
**Describe the bug**

Hi there. I'm trying to set up Vault QA. But after following the instructions in the [Local Copilot Setup Guide with LM Studio](https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md#lm-studio), I'm still not able to start chatting. When I open the chat and set it to `Vault QA (BETA)`, it gives me the message in IMAGE 1. So I click the _Refresh Index_ button and nothing happens. So I try to refresh it from the command palette as seen in IMAGE 2. Running either of the two commands gives me the following error: "**An error occurred while re-indexing vault to vector store**" as seen in IMAGE 3.

**Screenshots**
![image 1](https://github.com/logancyang/obsidian-copilot/assets/46340124/1db25204-f02a-450c-b762-f075637a2d3c)
_IMAGE 1 - What I see after following [these instructions](https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md#lm-studio)._

![image 2](https://github.com/logancyang/obsidian-copilot/assets/46340124/ec399c9c-0b2a-48fc-9fa7-618a4c05bcb3)
_IMAGE 2 - Command Palette._

![image 3](https://github.com/logancyang/obsidian-copilot/assets/46340124/2f826d66-6382-4f9c-9429-92bdbe0e1a8e)
_IMAGE 3 - The error._

I am unable to chat with my vault.

**Additional context**

Also, I read in a similar issue (#335) about something called embeddings?

> "Indexing relies on embeddings" - @logancyang 

I'm a noob but, what is that? Do I need to pay for an OpenAI API key for it? Or should I abandon using LM Studio and use only Ollama (for the local embeddings) for chatting with my vault?

Thanks.

**Comment by logancyang** [comment]
Hi @Welding-Torch, thanks for trying the plugin, could you check the new video? There's a setup walkthrough and explanation.

**Comment by Welding-Torch** [comment]
Can I use Ollama embedding even if I don't have Ollama installed?

Also, I'm getting stuck on this message. It isn't moving on from '4/70':
![image](https://github.com/logancyang/obsidian-copilot/assets/46340124/3f0f9c83-33e1-48da-9810-34368943fcdc)

**Comment by logancyang** [comment]
you need ollama installed to use it. Could you share a screenshot of your console with debug on, as the troubleshoot section of the video showed?

**Comment by Welding-Torch** [comment]
I see, so the LM Studio method isn't a complete solution? I followed the LM Studio method because it seemed easier than Ollama and also it was the first thing in the guide.

**Comment by logancyang** [comment]
Right, LM Studio is chat model only, QA needs an embedding model as well.

**Comment by pascalandy** [comment]
I just tried v2.5 with Ollama, nomic-embed-text:latest + dolphin-mixtral:8x7b-v2.7-q6_K. Works perfectly here!

**Comment by Welding-Torch** [comment]
Okay I set it up with Ollama. The speed is... really slow.
![image](https://github.com/logancyang/obsidian-copilot/assets/46340124/c8b1ef51-337d-41c1-8e65-06bd4229d214)

> Right, LM Studio is chat model only, QA needs an embedding model as well.

I think this should be clarified in the setup guide and Ollama should be treated as the default way to set this up. This can't be done entirely using LM Studio (yet).

---

Also, do you have any tips to speed it up? My specs are i5-9300H, 16GB Ram, GTX 1650 with 4GB VRAM.

**Comment by logancyang** [comment]
> Okay I set it up with Ollama. The speed is... really slow. ![image](https://private-user-images.githubusercontent.com/46340124/311044454-c8b1ef51-337d-41c1-8e65-06bd4229d214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDg2ODQsIm5iZiI6MTcwOTg0ODM4NCwicGF0aCI6Ii80NjM0MDEyNC8zMTEwNDQ0NTQtYzhiMWVmNTEtMzM3ZC00MWMxLThlNjUtMDZiZDQyMjlkMjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIxNTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTA2NjNlYjkwOTcxMTQxNzZkNGNkYjRmMjVhNzg2MWY4NzdjYjZhMGM2NzZjNjJiMWViN2E0ODNlMmQ4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.URZdMQHcIdg6uxyLa2IrRW06v8kOZSHfP5a1Kwa3mkE)
> 
> > Right, LM Studio is chat model only, QA needs an embedding model as well.
> 
> I think this should be clarified in the setup guide and Ollama should be treated as the default way to set this up. This can't be done entirely using LM Studio (yet).
> 
> Also, do you have any tips to speed it up? My specs are i5-9300H, 16GB Ram, GTX 1650 with 4GB VRAM.

Your specs are a bit low for running local LLMs tbh. Your best bet for Ollama is to deploy it on a remote server with a lot more VRAM, and use that url as an override.

**Comment by pascalandy** [comment]
<img width="752" alt="SCR-20240307-oqai" src="https://github.com/logancyang/obsidian-copilot/assets/6694151/19d76e34-1540-482c-a49b-9f3a37d58571">

This is an heavy RAM setup running LLM and vector db locally. 
@logancyang you should maybe run it via openai
