### ISSUE TITLE
Anthropic (Claude) API not working

### ISSUE THREAD

**Issue by tonypiper** [logancyang/obsidian-copilot#342]
Looking at my console log, it was trying to connect a local proxy, instead of the Anthropic endpoint.

I believe the url should be 

`https://api.anthropic.com/v1/messages`

but currently it's set to `http://localhost:${PROXY_SERVER_PORT}`

here

https://github.com/logancyang/obsidian-copilot/blob/c26490a6c54d1f1c7ddd21db8dad1dfd0cdeea51/src/LLMProviders/chatModelManager.ts#L75

Unfortunately I can't test and submit a PR today... hopefully someone else can!

**Comment by logancyang** [comment]
@tonypiper thanks for reporting. Can you share a screenshot of your chat and console? 

It is supposed to call that local proxy. Directly calling doesn't work cuz CORS.

**Comment by tonypiper** [comment]
oh ok! 

![CleanShot 2024-03-07 at 19 17 34](https://github.com/logancyang/obsidian-copilot/assets/206124/2ae14635-9b27-46cc-8d0c-39d572908d5f)

here's a screenshot of when I use a chat. I also tried various prompts and get the same message

**Comment by tonypiper** [comment]
I'm copilot plugin 2.5.0

**Comment by logancyang** [comment]
Could you try refreshing several times with the console open, switch to and from Claude 3 several times and see what happens. It's possible your local proxy isn't running correctly.

**Comment by tonypiper** [comment]
Problem solved (kind of) - 

It's not starting the proxy server when Obsidian (or the plugin) first launches.

The proxy server won't get started until I choose a different model and then choose Claude 3. 

![CleanShot 2024-03-08 at 09 38 06](https://github.com/logancyang/obsidian-copilot/assets/206124/c428b39d-1fff-47f9-9e4b-74c1657f06a1)

Hope this helps! Thanks for an amazing plugin

**Comment by logancyang** [comment]
I see the issue, right now if you set Claude as default without switching to it from another model, the proxy server doesn't start. Will fix this in the next release.

**Comment by tonypiper** [comment]
Ah that's great. Thank you so much! 🙏🏻

**Comment by logancyang** [comment]
Could you try new release v2.5.1 and see if it fixes your issue

**Comment by tonypiper** [comment]
Works perfectly now, thank you!

**Comment by tonypiper** [comment]
Works perfectly now, thank you!
