### ISSUE TITLE
Missing command: Count total tokens in your vault

### ISSUE THREAD

**Issue by macin** [logancyang/obsidian-copilot#353]
**Describe the bug**
Hi, I installed newest version of copilot 2.5.1 and am unable to see the command "Count total tokens in your vaule". Is there anything that needs to be done I might have missed that this is not available, or its just a bug?

**To Reproduce**
Install copilot, configure it.
Than CTRL+P
type in Count

No count command for counting vault tokens

**Expected behavior**
I'd expect there is a command there to count vault tokens

**Screenshots**
![image](https://github.com/logancyang/obsidian-copilot/assets/1422747/a6e5a6c6-d36b-4f3f-a34d-a816a5dea533)

**Comment by logancyang** [comment]
Hi @macin, thanks for reporting. My bad, I made this an editor command, so you need to focus your cursor on the note to see this command, just like `count token for selection`.

Will make it available as a non-editor command in the next release.

**Comment by macin** [comment]
And I just learned, that there is this distinction in Obsidian. Thanks @logancyang !

**Comment by logancyang** [comment]
This should be fixed in v2.5.2!
