### ISSUE TITLE
Indexing issue in Copilot plugin for vaults

### ISSUE THREAD

**Issue by oscarvdrgrgrgr** [logancyang/obsidian-copilot#359]
While attempting to use the GitHub Copilot plugin specifically to assist in managing my vault, I am encountering a persistent issue during the indexing process. After entering and saving my GPT API key, I proceed to select the option to index my vault so that Copilot can properly assist me. However, the indexing process is not completed satisfactorily.

### Expected result
The indexing process should complete, allowing all notes in my vault (411 in total) to be correctly indexed, thus enabling full Copilot support on my project.

### Current result
The indexing process is not completed, always stopping at 12 of the 411 notes that should be indexed. This behavior manifests itself in two ways: either I receive an error message without a detailed description, or the process appears to load indefinitely without completing the indexing of all notes.

![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/bacbd811-d321-42ea-a2d6-e5709cb9dc7a)
![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/17bed218-229b-4cc5-b339-038b7049005a)
![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/0e45b331-f19a-4e66-a648-8a9a97b04f2a)

**Comment by logancyang** [comment]
@oscarvdrgrgrgr hi, could you turn of other plugins, refresh your console, and try to reproduce this behavior again. Your current console is full of messages from other plugins.

**Comment by oscarvdrgrgrgr** [comment]
I already deactivated all the plugins and started Obsidian again when I hit index again the same errors come from copilot
![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/7d9fd87d-24b9-4cc7-9415-6e015b3ce885)

**Comment by oscarvdrgrgrgr** [comment]
> @logancyang I already deactivated all the plugins and started Obsidian again when I hit index again the same errors come from copilot
![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/9dea4803-d0e1-4883-ac73-4f1fe481f9bc)

**Comment by logancyang** [comment]
You need an account with payment method with OpenAI. You are being rate limited.

**Comment by oscarvdrgrgrgr** [comment]
like that and because yes I already saw the statistics and I still have a lot of credit, I also tried it with smart connections another plugin and it works correctly, I index the vault without problems and I can talk to my vaul

**Comment by logancyang** [comment]
Smart connections does not use openai embedding. If you'd like to use OpenAI, you need to have payment method with them not just credit.

You can also use Ollama for local embeddings. Please refer to the video walkthrough, it explains everything https://youtu.be/NSoKRYNlOls?si=Jw6Re-22aVdwRW5q

**Comment by oscarvdrgrgrgr** [comment]
Ok, I already paid the additional fees if I index it, but I've only asked 4 questions with gpt 4 turbo and I'm already spending half a dollar, it's a lot. A question, already indexed, can I use other API keys like Claude's without problem?

**Comment by logancyang** [comment]
@oscarvdrgrgrgr did you run total token count of your vault? Half a dollar for 4 questions sounds abnormally high.

Have you tried Claude 3 in the dropdown?

**Comment by oscarvdrgrgrgr** [comment]
watching the video I want to know something
1. How effective is gpt taking reference notes (the three notes of the vaul) and what is the process like, read the entire vaul or just take the three notes most relevant to my question and answer based on them. Without knowing more about the vaul?
2. Are the tokens you use only the question and answer tokens or are you also counting the analysis tokens of the note if you use 3 notes to answer the content of those three notes do I also pay for it when using it? (I ask why I am being charged too much for use, the only thing that would justify it is that they are charging the notes)

**Comment by oscarvdrgrgrgr** [comment]
In the first photo you can see that the biggest expense does not come from gpt but from small. small is independent of gpt-4. You said that your vaul having twice as many tokens as mine cost only two cents to index it. Well, I have pressed the refresh vaul button on the right of the panel an average of 7 times, and I think that has come at the highest cost. How exactly is this button used and when should I press it and if once the vault has been indexed I press it then does it go back to indexing the entire vault or does it only index the new notes to be better?

**Comment by oscarvdrgrgrgr** [comment]
![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/6e6bd233-077c-443b-87d2-da5316953a19)
![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/518bb1dc-3dd2-4457-9007-76ac49deb43c)
![image](https://github.com/logancyang/obsidian-copilot/assets/113726286/1e8909f3-b3a4-4741-9dbe-0c86e683b3de)
Is that expense normal for a question that I spend that amount of tookens in total? It is much higher than the one mentioned in the open.ai price list. According to you, how much should gpt-4 normally be spending for 1k tokens?
The above is the expense for just one question, I didn't ask more.
