### ISSUE TITLE
Refresh Index for Vault errors on OpenAI API Key instead of using enabled offline LM Studio

### ISSUE THREAD

**Issue by Kuiriel** [logancyang/obsidian-copilot#361]
**Describe the bug**
I have the server up and running. I can even get a test prompt responded to in Obsidian. I can't however Refresh Index for Vault while using LM Studio.

**To Reproduce**
Open Obsidian Sandbox. Change model to LM Studio. Save and Reload. Use test message in Copilot to verify it works. Click Vault QA (Beta). Click Refresh Index for Vault. Witness error in debug panel.

**Expected behavior**
Clicking refresh index for vault should create or refresh the index. Alternatively, install notes should say that LM Studio does not support Vault QA, maybe?

**Screenshots**
plugin:copilot:87019 OpenAI API key is not provided for the embedding model.
getEmbeddingsAPI @ plugin:copilot:87019
setChain @ plugin:copilot:91700
setChain @ plugin:copilot:92409
handleChainSelection @ plugin:copilot:92658
eval @ plugin:copilot:92660
commitHookEffectListMount @ plugin:copilot:59101
commitPassiveMountOnFiber @ plugin:copilot:60354
commitPassiveMountEffects_complete @ plugin:copilot:60322
commitPassiveMountEffects_begin @ plugin:copilot:60312
commitPassiveMountEffects @ plugin:copilot:60302
flushPassiveEffectsImpl @ plugin:copilot:61683
flushPassiveEffects @ plugin:copilot:61640
commitRootImpl @ plugin:copilot:61609
commitRoot @ plugin:copilot:61470
performSyncWorkOnRoot @ plugin:copilot:61088
flushSyncCallbacks @ plugin:copilot:51332
flushSync @ plugin:copilot:61152
finishEventHandler @ plugin:copilot:45766
batchedUpdates @ plugin:copilot:45779
dispatchEventForPluginEventSystem @ plugin:copilot:49373
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ plugin:copilot:47675
dispatchEvent @ plugin:copilot:47669
dispatchDiscreteEvent @ plugin:copilot:47646
handleMouseUp_ @ unknown
plugin:copilot:91702 Error getting embeddings API. Please check your settings.
setChain @ plugin:copilot:91702
setChain @ plugin:copilot:92409
handleChainSelection @ plugin:copilot:92658
eval @ plugin:copilot:92660
commitHookEffectListMount @ plugin:copilot:59101
commitPassiveMountOnFiber @ plugin:copilot:60354
commitPassiveMountEffects_complete @ plugin:copilot:60322
commitPassiveMountEffects_begin @ plugin:copilot:60312
commitPassiveMountEffects @ plugin:copilot:60302
flushPassiveEffectsImpl @ plugin:copilot:61683
flushPassiveEffects @ plugin:copilot:61640
commitRootImpl @ plugin:copilot:61609
commitRoot @ plugin:copilot:61470
performSyncWorkOnRoot @ plugin:copilot:61088
flushSyncCallbacks @ plugin:copilot:51332
flushSync @ plugin:copilot:61152
finishEventHandler @ plugin:copilot:45766
batchedUpdates @ plugin:copilot:45779
dispatchEventForPluginEventSystem @ plugin:copilot:49373
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ plugin:copilot:47675
dispatchEvent @ plugin:copilot:47669
dispatchDiscreteEvent @ plugin:copilot:47646
handleMouseUp_ @ unknown
plugin:copilot:87019 OpenAI API key is not provided for the embedding model.
getEmbeddingsAPI @ plugin:copilot:87019
indexVaultToVectorStore @ plugin:copilot:111697
refreshVaultContext @ plugin:copilot:101678
callCallback2 @ plugin:copilot:45871
invokeGuardedCallbackDev @ plugin:copilot:45896
invokeGuardedCallback @ plugin:copilot:45930
invokeGuardedCallbackAndCatchFirstError @ plugin:copilot:45933
executeDispatch @ plugin:copilot:49213
processDispatchQueueItemsInOrder @ plugin:copilot:49233
processDispatchQueue @ plugin:copilot:49242
dispatchEventsForPlugins @ plugin:copilot:49250
eval @ plugin:copilot:49374
batchedUpdates$1 @ plugin:copilot:61106
batchedUpdates @ plugin:copilot:45776
dispatchEventForPluginEventSystem @ plugin:copilot:49373
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ plugin:copilot:47675
dispatchEvent @ plugin:copilot:47669
dispatchDiscreteEvent @ plugin:copilot:47646
plugin:copilot:111699 Uncaught (in promise) Error: Embedding instance not found.
    at CopilotPlugin.indexVaultToVectorStore (plugin:copilot:111699:13)
    at refreshVaultContext (plugin:copilot:101678:18)
    at HTMLUnknownElement.callCallback2 (plugin:copilot:45871:22)
    at Object.invokeGuardedCallbackDev (plugin:copilot:45896:24)
    at invokeGuardedCallback (plugin:copilot:45930:39)
    at invokeGuardedCallbackAndCatchFirstError (plugin:copilot:45933:33)
    at executeDispatch (plugin:copilot:49213:11)
    at processDispatchQueueItemsInOrder (plugin:copilot:49233:15)
    at processDispatchQueue (plugin:copilot:49242:13)
    at dispatchEventsForPlugins (plugin:copilot:49250:11)

**Additional context**

**Comment by logancyang** [comment]
Answered on twitter

**Comment by Villar74** [comment]
> Answered on twitter

I can't find answer on twitter, why u can't post it here?

**Comment by l3bck** [comment]
Local embedding is not supported with LM Studio https://x.com/logancyang/status/1767354459427140036
