### ISSUE TITLE
Not showing sources in Vault QA

### ISSUE THREAD

**Issue by maxlvhao** [logancyang/obsidian-copilot#371]
**Describe the bug**

I was able to get answers but not sources.

**To Reproduce**
GPT 3.5 16K - basically just any query using VaultQA fails to give me actual sources

**Screenshots**
<img width="359" alt="Screenshot 2024-03-16 at 8 57 29 PM" src="https://github.com/logancyang/obsidian-copilot/assets/12852655/920c4bcb-18e7-48e3-a5f2-2363fff610d0">

**Additional context**
Intel Mac

**Comment by maxlvhao** [comment]
After changing the output token limit to 3000, it seems to show sources in link format, but not actually clickable.. any suggestions?

<img width="213" alt="Screenshot 2024-03-16 at 9 18 12 PM" src="https://github.com/logancyang/obsidian-copilot/assets/12852655/dd1054ea-c8f1-4da3-b3fe-02ea93186faa">

**Comment by wwjCMP** [comment]
This is a formatting error, the link can be correctly redirected to the original text through the browser.

**Comment by oscarvdrgrgrgr** [comment]
> Después de cambiar el límite del token de salida a 3000, parece mostrar las fuentes en formato de enlace, pero en realidad no se puede hacer clic en ellas. ¿Alguna sugerencia?
> 
> <img alt="Captura de pantalla 2024-03-16 a las 9 18 12 pm" width="213" src="https://private-user-images.githubusercontent.com/12852655/313439069-dd1054ea-c8f1-4da3-b3fe-02ea93186faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTU2MDAsIm5iZiI6MTcxMDY1NTMwMCwicGF0aCI6Ii8xMjg1MjY1NS8zMTM0MzkwNjktZGQxMDU0ZWEtYzhmMS00ZGEzLWIzZmUtMDJlYTkzMTg2ZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA2MDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNWExMmNhYTIzZmE3ODFhYTJkNjgxNWY0OWI2NjIzMWMxZmNkY2IxZjMyMTI1NTJhNzYyNWZlYzk0ZjhkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xx-ycb80cvA8TH1gxT_zWx2suIQqgM1QFBtGJmhI248">

ya verificaste que hayas selleccionado el modo vaul QA?. Otra es queu si tu boveda es gande a partir de 1mil tokens debes pagar 5 usd en open ai para que te de esa funcion en la api de obsidian a mi antes me ocurria lo mismo

**Comment by logancyang** [comment]
@maxlvhao Do the titles literally have `%20` in them? Is there a space in `Max's Vault` (can't tell because there's new line). Just trying to understand why your titles failed. Could you share your actual titles for me to test? Must be special characters tripping up the encoding here.

**Comment by giannisanni** [comment]
> After changing the output token limit to 3000, it seems to show sources in link format, but not actually clickable.. any suggestions?
> 
> <img alt="Screenshot 2024-03-16 at 9 18 12 PM" width="213" src="https://private-user-images.githubusercontent.com/12852655/313439069-dd1054ea-c8f1-4da3-b3fe-02ea93186faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTI1MDksIm5iZiI6MTcxMjc1MjIwOSwicGF0aCI6Ii8xMjg1MjY1NS8zMTM0MzkwNjktZGQxMDU0ZWEtYzhmMS00ZGEzLWIzZmUtMDJlYTkzMTg2ZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNzY3MGFhY2Y3ZjM0ZTQ0MThlNWI4Yjk2NjYyZDAwMWUwZWY0MzExZTNmMDE3M2JkMGY3Y2YzYTBlODBmMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKyZln2kSz0381bQR9kS-n86QdJumkj2_t0OMcxthPw">

Did you manage to fix this?

**Comment by logancyang** [comment]
Should be fixed now, closing
