### ISSUE TITLE
Option to Exclude Specific Folders from Indexing in QA Vault

### ISSUE THREAD

**Issue by pelayoarbues** [logancyang/obsidian-copilot#372]
**Is your feature request related to a problem? Please describe.**
Currently, the QA Vault indexes all folders within the project. However, there are certain folders that I would like to exclude from being indexed. This is because these folders contain files that are not relevant to the QA process and their inclusion in the index only serves to clutter the results and make the process less efficient.

**Describe the solution you'd like**
I would like a feature that allows users to specify certain folders that should be excluded from the indexing process in the QA Vault. This could be implemented as a simple list of folder paths in the settings that the QA Vault would then ignore during indexing. This would greatly improve the efficiency of the QA process by ensuring that only relevant files are included in the index.

**Additional context**
This feature would be particularly useful in large projects where there are many folders and files. It would allow users to tailor the QA process to their specific needs and ensure that the index only contains relevant information. I believe that this feature would be a valuable addition to the QA Vault and would greatly enhance its usability.

**Comment by logancyang** [comment]
hi @pelayoarbues, this is already implemented, please refer to https://github.com/logancyang/obsidian-copilot/issues/334

**Comment by pelayoarbues** [comment]
Thanks so much @logancyang . It would be great if user could check what folders are excluded in the QA Vault.

Btw, I have just started testing Obsidian Copilot and it seems a great addition to my workflow!

**Comment by logancyang** [comment]
Hi @pelayoarbues, you can check the excluded ones using the same command, they are in the field where you've put them.

Make sure to check out my youtube videos for tips!

**Comment by pelayoarbues** [comment]
Oh thanks! Sorry for not finding out. I am a man of reading not watching videos 🤦‍♂️🙄

**Comment by logancyang** [comment]
I will update the documentation soon, it's getting too outdated!
