### ISSUE TITLE
Please remove Ollama in Windows

### ISSUE THREAD

**Issue by ScribbleGhost** [logancyang/obsidian-copilot#383]
Please consider removing the Ollama option from the dropdown in Windows. I just spent an hour trying to get it to work only to realize Windows is not supported yet.

**Comment by wwjCMP** [comment]
In fact, Ollama supports Windows.

**Comment by ScribbleGhost** [comment]
How to use it? Is there any documentation for it?

**Comment by logancyang** [comment]
@ScribbleGhost it's right there in the local copilot setup guide.

**Comment by ScribbleGhost** [comment]
I tried that but I get an error when using the prompt
![image](https://github.com/logancyang/obsidian-copilot/assets/49068170/efda7f58-d4ab-4d03-85ae-5e3e5f2c912f)

**Comment by ckep1** [comment]
Hey, I just tried the command `set OLLAMA_ORIGINS=app://obsidian.md* && ollama serve` myself and it doesn't work (I thought it did, sorry about that). For this to work, I suggest you do the following as this tested works for me:

Your user environment variables should match mine for the Obsidian entry:

![image](https://github.com/logancyang/obsidian-copilot/assets/66276452/b4b90966-f21b-4509-ad70-c74468f325f9)

Then, open Command Prompt (as your user) and run `ollama serve`

![image](https://github.com/logancyang/obsidian-copilot/assets/66276452/69188ade-e0cf-4519-b0cc-bee7354505d3)

I don't have anything else set for this in Copilot settings except the model I'm using. I use the default base URL.

If the error is on the Ollama side, you may be able to determine why by watching the Command Prompt where you served Ollama. With that first incorrect command I supplied I get 403 (unauthorized) in the ollama command prompt window.
If its on the Copilot side, you should be able to see why in Obsidian Developer Tools console.
![image](https://github.com/logancyang/obsidian-copilot/assets/66276452/a202230b-e5e2-4664-8c63-b66f4fd69265)

Hey @logancyang just a suggestion- it may be helpful to add this setup for Windows somewhere, as the supplied command in Copilot settings only works on Mac and required some tinkering on Windows (really appreciate this plugin overall, thank you!)

**Comment by ScribbleGhost** [comment]
> ollama serve

That's it. It works now. Thanks!

Yes, it should probably say in the documentation somewhere.
