### ISSUE TITLE
Duplicate User Prompts in Saved Notes 

### ISSUE THREAD

**Issue by ckep1** [logancyang/obsidian-copilot#386]
**Describe the bug**
When saving the chat as a note, I get the user prompt duplicated each turn. 

**To Reproduce**
Have a chat conversation (any length) in any of the 3 modes. Happens with Ollama and Anthropic as far as I've tested.

**Expected behavior**
Output the user prompt once per turn.

**Screenshots**
![Screenshot 2024-03-24 at 9 38 32 PM](https://github.com/logancyang/obsidian-copilot/assets/66276452/f2f42a88-f543-4f1a-97e4-fc3d18006980)

![Screenshot 2024-03-24 at 9 38 43 PM](https://github.com/logancyang/obsidian-copilot/assets/66276452/da299fa6-a4ce-42f1-a915-1da49f4f4d5f)

**Additional context**
The AI output does not get duplicated, no other issues with saving as far as I can tell. I have a lot of other plugins active so it could be something that's interfering. I have a custom system prompt.

**Comment by logancyang** [comment]
Hmm interesting, will take a look
