### ISSUE TITLE
[PLUS] Support indexing of Microsoft Word docx files

### ISSUE THREAD

**Issue by etlweather** [logancyang/obsidian-copilot#389]
**Is your feature request related to a problem? Please describe.**
This plugin is awesome with the new Vault QA. I am able to use it with my local repository of knowledge which is comprised of Markdown files and PDF files. However I also have a lot of Microsoft Word document and it would be amazing if these could be indexed as well.

**Describe the solution you'd like**
The indexing of the vault includes Word documents.

**Describe alternatives you've considered**
None particularly. I have to have these files in Word and keeping a PDF version of the document everytime the documents are updated is not workable to be done manually.

**Additional context**
I might work on this and contribute a patch. I just never programmed in this language so I will have to learn that first.

**Comment by ChrisBBBB** [comment]
It can't currently access attached PDF content as context can it? [would be great if possible]

**Comment by logancyang** [comment]
Docx isn't supported in Obsidian at all if I'm not mistaken? Please let me know if this isn't the case.

**Comment by logancyang** [comment]
Closing as not planned. Reopen if enough people request it.
