### ISSUE TITLE
request: excluding folder(s) from vault QA embedding

### ISSUE THREAD

**Issue by rushikb** [logancyang/obsidian-copilot#390]
**Is your feature request related to a problem? Please describe.**
for users with large vaults, its important to manage the size of the local vector store since it can cause obsidian to crash. One way to do this is to exclude folders (eg: archive/ resources) from the list of files indexed in vault QA. 

**Describe the solution you'd like**
A way to exlude entire folders from the vault QA using QA settings. 

**Describe alternatives you've considered**
NA

**Additional context**
smart connections has a similar implementation for reference

**Comment by logancyang** [comment]
This already exists #334, closing for now.
