### ISSUE TITLE
Cors when using local ollama

### ISSUE THREAD

**Issue by UyCode** [logancyang/obsidian-copilot#394]
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

**Describe how to reproduce**
I am just using the local ollama with model llama2:13b, and the request blocked by cors policy

**Expected behavior**

**Screenshots**
![image](https://github.com/logancyang/obsidian-copilot/assets/24651136/abc5d2c3-72d6-4922-ae13-474cc82a5f9a)

**Additional context**

**Comment by zhuhaoxlj** [comment]
On mac devices, the command below works for me.
`OLLAMA_ORIGINS="*" ollama serve`
