### ISSUE TITLE
[FR] add Jan as Embedding Provider

### ISSUE THREAD

**Issue by jayma-bro** [logancyang/obsidian-copilot#397]
I tried to use my local Jan model through the Ollama (and LM Studio) config, but it didn't work,
for me, Jan.ai use to be a better Open source solution for local model. And I would be very happy to use it on my obsidian :).

But I don't have the skills to do this.
I hope I'm not the only interested,
I would be very grateful to whoever adds this !

**Comment by wwjCMP** [comment]
https://github.com/logancyang/obsidian-copilot/issues/381

**Comment by PSG2017** [comment]
As a non-technical user who wants to use a local open source model with no strings attached (now or in the future), I support this request.

**Comment by logancyang** [comment]
@PSG2017 now that custom models can be added, is this still relevant? Please open another issue if custom model doesn't address your needs, and provide details what you have tried. Closing this old one for now.
