### ISSUE TITLE
User questions are listed twice...

### ISSUE THREAD

**Issue by pedramamini** [logancyang/obsidian-copilot#398]
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

<img width="1074" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/1253573/b2a4fa67-418a-4bba-acb0-935736339fc2">

**Describe how to reproduce**
Chat with any note, ask a question, save the content and note that all user questions are duplicated.

**Comment by logancyang** [comment]
Sorry I forgot about this one, should be fixed in the coming release!
