### ISSUE TITLE
Little typo - `cotents`

### ISSUE THREAD

**Issue by luckman212** [logancyang/obsidian-copilot#4]
Super nice implementation!

Just noticed a little typo :)

<img width="391" alt="screenshot_ZJ9Cansb_gh" src="https://user-images.githubusercontent.com/1992842/236638111-644dd537-42f1-4664-9584-847354371601.png">

**Comment by logancyang** [comment]
Nice catch! Merged and will be fixed in the new release.

**Comment by logancyang** [comment]
Made the new release 1.2.1, please update the plugin.
