### ISSUE TITLE
Ollama mxbai-embed-large support

### ISSUE THREAD

**Issue by jadbox** [logancyang/obsidian-copilot#401]
Ollama [v0.1.30](https://github.com/ollama/ollama/releases/tag/v0.1.30) is out:
https://github.com/ollama/ollama/releases

It has a new embedding modal:
[mxbai-embed-large](https://ollama.com/library/mxbai-embed-large): A new state-of-the-art large embedding model

It would be aweome if we could add it to the drop down next to ollama-nomic-embed-text. Or better, have a custom input option. 

:)

**Comment by jadbox** [comment]
Perhaps a custom embedding modal option would also help solve for issue: https://github.com/logancyang/obsidian-copilot/issues/381

**Comment by mhafellner** [comment]
@jadbox if you want to try mxbai-embed-large you can do so by using LM Studio v0.2.19 as they added embedding model support there.

It's a bit of a manual process right now, but works:
1. Download LM Studio v0.2.19 for embedding model support - https://lmstudio.ai/beta-releases.html
2. Download the model GGUF from https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1/tree/main/gguf
3. Put the GGUF in the model folder of LM Studio with the correct folder structure
4. Reload LM Studio
5. You can select the mxbai model now as embedding model
6. In Obsidian in the Copilot setting page use the embedding proxy functionality
6.1 Set the URL to http://localhost:1234/v1
6.2. Set the model to whatever you want to overwrite, e.g. text-embedding-ada-002

🎉 you now have local embeddings with LM Studio using mxbai-embed-large

**Comment by HaoHoo** [comment]
I found the custom embedding “ToDo” comment in the TypeScript source code. Please just make it happen~ 😄

**Comment by jsrdcht** [comment]
ollama-nomic-embed-text sucks, it can never retrieve the true useful files.

**Comment by teddyzxcv** [comment]
@logancyang  seems add custom model features is added, we can close this issue 
<img width="799" alt="image" src="https://github.com/user-attachments/assets/504b874d-d7b2-44a2-ad45-aafee4d05ace">
