### ISSUE TITLE
WASTED ENOUGH TIME, where are the vault mode embeddings!?!!?

### ISSUE THREAD

**Issue by ReliablyAwkward** [logancyang/obsidian-copilot#402]
I tried to troubleshoot this a trillion times already, I checked and unchecked and rechecked every single hidden folder option you can think of, I've used different AI to try and help address this, 

wasted a ton of time, sent a ton of snapshots, restarted my computer a million times, and yet, even though I indexed a 2.8 million word vault, I cannot locate the embeddings and neither can a global search from windows file explorer.

 Where on earth is it!?!!?, please respond to this! It's ridiculous that it's this hidden, when I go into my obsidian folder and go to the plugins, all I see in copilot is what the attachment shows.
![No embeddings](https://github.com/logancyang/obsidian-copilot/assets/135422842/9e030a11-b99c-4109-bd6b-8fd9cf8850ac)

**Comment by logancyang** [comment]
Hey @ReliablyAwkward, the answer to your question is IndexedDB which you can see in your dev console. 

And I think you misunderstand. This is a **free** and **open-source** project, I spend my personal time working for free for the community. Users are not paid customers. Anyone is welcome to look into the code as it's completely transparent. But I do not have bandwidth to handhold every user. I will put up a comprehensive documentation on the website soon https://www.obsidiancopilot.com though.

For future reference, please refer to https://github.com/logancyang/obsidian-copilot/blob/master/CONTRIBUTING.md#your-first-code-contribution for how to write an issue. Use discussions for pure questions.
