### ISSUE TITLE
Support LM Studio /v1/embeddings endpoint

### ISSUE THREAD

**Issue by mhafellner** [logancyang/obsidian-copilot#408]
**Is your feature request related to a problem? Please describe.**
I tried to set up the new mxbai-embed-large model using the new LM Studio 0.2.19 beta which supports /v1/embeddings but was not able to get it to work. Even with the embedding model which already works with Ollama (nomic embed text v1.5), it was very slow and quite buggy when using it as LM Studio Embedding Model.

**Describe the solution you'd like**
Ideally a workflow as below would work
> I want to try mxbai-embed-large by using LM Studio v0.2.19 as they added embedding model support there.
> 
> It's a bit of a manual process right now, but works:
> 
> 1. Download LM Studio v0.2.19 for embedding model support - [https://lmstudio.ai/beta-releases.html](https://lmstudio.ai/beta-releases.html)
> 2. Download the model GGUF from [https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1/tree/main/gguf](https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1/tree/main/gguf)
> 3. Put the GGUF in the model folder of LM Studio with the correct folder structure
> 4. Reload LM Studio
> 5. You can select the mxbai model now as embedding model
> 6. In Obsidian in the Copilot setting page use the embedding proxy functionality  
>     6.1 Set the URL to [http://localhost:1234/v1](http://localhost:1234/v1)  
>     6.2. Set the model to "mixedbread-ai/mxbai-embed-large-v1" and use "text-embedding-ada-002" in the embedding model selection
> 
> 🎉 you now have local embeddings with LM Studio using mxbai-embed-large

**Describe alternatives you've considered**
Using Ollama as they added mxbai-embed-large recently. But this again is not supported yet in Copilot, as mentioned in #401 

**Additional context**

**Comment by jadbox** [comment]
Thank you for sharing, I believe this would be a huge improvement for editor plugins! I can help review and test if someone has the knowledge to take this on :)

**Comment by sadaisystems** [comment]
+1, would be awesome

**Comment by lzhgus** [comment]
please

**Comment by logancyang** [comment]
Does LM Studio support spinning up two local servers at the same time? One chat, one embedding?

**Comment by mhafellner** [comment]
@logancyang It's not 2 local servers strictly speaking, but yes, `/completions` and `/embeddings` endpoints can be used at the same time by loading one model for each purpose. Please see [LM Studio docs](https://lmstudio.ai/docs/local-server#supported-endpoints) for details.

**Comment by logancyang** [comment]
@mhafellner That's interesting, didn't know that! But from a glance it seems it won't work. The real question is can it load 2 models at the same time? There's no single model that does `/completions` and `/embeddings` well enough for RAG.

**Comment by jonashaefele** [comment]
It does Indeed load two separate models.

**Comment by logancyang** [comment]
<img width="755" alt="SCR-20240814-svmm" src="https://github.com/user-attachments/assets/afe0bfe7-a2f2-48ce-86cc-b6cf4a025be4">
<img width="757" alt="SCR-20240814-svrf" src="https://github.com/user-attachments/assets/c940c1cf-bb77-4cc2-b2a9-4f3bcc50eab2">

Does anybody know what the context length is here, is it 512 or 2048, I'm confused

**Comment by shwanton** [comment]
I'm trying to local a local embedding model from LM Studio in v2.6.1

Here is the LM Studio setup:
![CleanShot 2024-09-04 at 09 48 44@2x](https://github.com/user-attachments/assets/5c934fcd-7e07-4b22-a361-e8beec66f842)

These are the options for the custom model w/ LM Studio listed (The custom model **worked**!)
![CleanShot 2024-09-04 at 09 40 26@2x](https://github.com/user-attachments/assets/455b3711-9b6d-4a7f-bbec-986c09c97822)

These are the options for the custom Embeddings w/o LM Studio - The custom Embeddings model did **not** work
![CleanShot 2024-09-04 at 09 32 24@2x](https://github.com/user-attachments/assets/dca9e34a-4223-48d9-a80e-288ae650fd90)

I tried using the "openai-format" and used the embeddings url from LM Studio.
![CleanShot 2024-09-04 at 09 32 50@2x](https://github.com/user-attachments/assets/cb68751f-50bb-45b1-956e-1fd0a332e8d7)
![CleanShot 2024-09-04 at 09 45 32@2x](https://github.com/user-attachments/assets/b9e58052-2095-448e-bde5-af5a0f350302)

I received this error when reloading
![CleanShot 2024-09-04 at 09 33 41@2x](https://github.com/user-attachments/assets/16daeee1-5187-4d13-a6cd-febe320f06dc)

![CleanShot 2024-09-04 at 09 33 02@2x](https://github.com/user-attachments/assets/319acf38-52ed-4e9f-9787-bda328ed9972)

**Comment by logancyang** [comment]
@shwanton I noticed you have "serve on local network" on, then you must use `3rd party openai format` as provider instead of lm-studio. And you must **provide the correct base url**, it is not localhost since you serve on local network, you can find the correct IP address and port in LM Studio. Also don't have `embedding` in the custom URL, it should be up to `/v1` and nothing after it.  

The next version will skip the API key for custom embedding model, in the meantime just put any string in the API key.

**Comment by shwanton** [comment]
**Thank you, this worked!**
![CleanShot 2024-09-04 at 11 03 09@2x](https://github.com/user-attachments/assets/6ece4d69-29f0-4893-939f-f55f555ba716)

I turned off "serve on local network" and used the local address
![CleanShot 2024-09-04 at 11 03 49@2x](https://github.com/user-attachments/assets/8779f416-8a74-4f63-b647-77cc32d7f10e)

I re-added the embeddings model and used an empty space for api key
![CleanShot 2024-09-04 at 11 12 45@2x](https://github.com/user-attachments/assets/26ec12c2-15d5-4fe8-956e-3853427752d2)

> Also, some models in LM Studio may not have proper context length, so it might mess up the QA. 

It looks like LM Studio added the ability to change the Evaluation Batch size:
![CleanShot 2024-09-04 at 11 08 02@2x](https://github.com/user-attachments/assets/e53002ef-a820-4a9e-9c27-2d581b48db3b)

I'm assuming this should match the embedding model batch size?

**Comment by logancyang** [comment]
@shwanton glad it worked! Not sure about Evaluation Batch Size, is it embedding model specific? Let me know what you find out about it, I'll take a look soon as well.
