### ISSUE TITLE
Question about the parameter num_ctx setttings for Ollama models

### ISSUE THREAD

**Issue by luc99hen** [logancyang/obsidian-copilot#409]
As the doc explains "AFAIK ollama serve doesn't have a consolidated way to configure context window for all the models at a single place. The current best way is to run ollama run <modelname> and then /set parameter num_ctx 32768 (this is the max for Mistral, set it based on your model requirement), and don't forget to /save <modelname> for each model individually."

32768 works perfectly for Mistral, but not for other models like Qwen and llama. I want to know how can I find a proper num_ctx for other models.

**Comment by logancyang** [comment]
@luc99hen you can find the model specifications online from their providers, e.g. huggingface model card or whatever platform they publish them.

For future reference, pure questions are better posted in the discussion section. Thanks!
