### ISSUE TITLE
Save as Note Creates two **user**:  entries in the saved note.

### ISSUE THREAD

**Issue by cdonohoe** [logancyang/obsidian-copilot#410]
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**
![image](https://github.com/logancyang/obsidian-copilot/assets/43006634/dae37fec-0059-4a85-ad19-bdcfed6e5930)

**Describe how to reproduce**
A clear and concise description of what the bug is. Clear steps to reproduce the behavior
Simply save a note

**Expected behavior**
Only one user line entry per user prompt, otherwise it needs to be cleaned up or takes up space, or duplicates in searches when returned.

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary. 

**Additional context**
This is from a Windows 11 install of obsidian and copilot.

**Comment by logancyang** [comment]
Yes this is a known bug, will be addressed in the next update!

**Comment by logancyang** [comment]
Ah dang it I forget about this, sorry, will fix next
