### ISSUE TITLE
Copilot not switching back to Chat mode after using Vault QA mode?

### ISSUE THREAD

**Issue by Fffrankoo** [logancyang/obsidian-copilot#415]
After using Vault QA mode and then switching back to Chat mode, Copilot appears to be querying the local vector store and not the default model. I was using local Ollama Mistral as default model and asked it "How old is Joe Biden" The response was that this could not be established from the available context or a similar message. After Save and Reload in Copilot Settings, Copilot did find Biden's birthday in the default model, so the information should have been available first time around.

I run Obsidian and Ollama on Windows 64-bits

I expect Copilot to switch back to using the default model and ignore the local vector store when I switch from Vault QA to Chat in the Copilot pane.

Great stuff, though, this plugin!! Thank you for developing it!

**Comment by logancyang** [comment]
Hi @Fffrankoo, thanks for reporting. Could you follow the bug report guide and provide some relevant screenshots of the chat and console?

**Comment by Fffrankoo** [comment]
Hi Logan,
Sorry for the delay in answering. I tried to reproduce what I saw time around with Dev Console switched on, but did not succeed. Hence I have closed the bug report.
