### ISSUE TITLE
Can't save chat to note because "folder already exists"

### ISSUE THREAD

**Issue by aseyedia** [logancyang/obsidian-copilot#427]
![image](https://github.com/logancyang/obsidian-copilot/assets/43455034/7365ef19-5b30-4e4b-ae26-489a73c2fe4d)

Hello,

First of all, thank you so much for making this app. I avoided trying it because I didn't want to pay OpenAI even more money but given amount of data in my vault, if I avoid accidentally sending my entire work folder as a note from now on (haha - don't forget to clear your context before sending your note, folks), I can query for less than a dollar a day. Huge. 

I would like to save my threads sometimes, to occasionally reflect on and process. I have done it once. However, now, the button completely doesn't work. It does nothing when I click it. The console revealed that the error is that Obsidian expects to create a new folder each time, but can't because I already have a folder. 

My chat conversations folder is the default, `copilot-conversations/`. What I would like it to do is save a note with the full thread, timestamped for the file name.

Otherwise amazing app, especially the vault conversation. Thank you so much.

**Comment by aseyedia** [comment]
I had to remove the `/` from `copilot-conversations/`, which I don't think was already there.

**Comment by jeffkimbrel** [comment]
FYI, I also got this error, but for a different reason. If the case is different in copilot settings than the actual folder name, this error will pop up. Just change the settings to match the correct case. 

For example, my folder name was `Sources/Copilot`, but I had `Sources/copilot` in the settings (lower case "c"). This led to an error.
