### ISSUE TITLE
Cors when using local ollama 

### ISSUE THREAD

**Issue by wp-jackliu** [logancyang/obsidian-copilot#428]
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**
![image](https://github.com/logancyang/obsidian-copilot/assets/3220935/c7dca842-f079-444f-a50d-73bd0eaec80f)

Now, start the local server with OLLAMA_ORIGINS=app://obsidian.md* ollama serve, this will allow the Obsidian app to access the local server without CORS issues.

Again, OLLAMA_ORIGINS=app://obsidian.md* is required!

Yeah, I follow this doc. but also not work .please help me.

**Comment by wp-jackliu** [comment]
Oh  the fish shell's issue .... 

!!!! Please note that when using the command line, please exit ‘fish’ before exec  OLLAMA_ORIGINS=app://obsidian.md* ollama serve

**Comment by 0atman** [comment]
OMG this kicked my ass lol

here's the fish workaround:

```sh
OLLAMA_ORIGINS="app://obsidian.md*" ollama serve
```

you have to QUOTE the env body!
