### ISSUE TITLE
Suggest to support config frequency_penalty parameters in plugin settings

### ISSUE THREAD

**Issue by qinshulei** [logancyang/obsidian-copilot#431]
**Is your feature request related to a problem? Please describe.**
Yes. 

I use https://docs.perplexity.ai/reference/post_chat_completions for chat api.
I find perlexity api don't support frequency_penalty=0 . 

for example:
```
{"temperature":0.3,"top_p":1,"presence_penalty":0,"frequency_penalty":0,"n":1,"model":"sonar-medium-online","messages":[{"role":"user","content":"hello"}],"stream":true}
```

error:
```
{"error":{"message":"Frequency penalty must satisfy p > 0.","type":"invalid_parameter","code":400}}
```

**Describe the solution you'd like**
Support config frequency_penalty parameters in plugin settings.

**Describe alternatives you've considered**
Or don't set frequency_penalty in default request.

**Additional context**
None

**Comment by logancyang** [comment]
PR merged. Perplexity API will work in the next release, don't forget to turn on CORS. We will not add more settings at this time.
