### ISSUE TITLE
LM studio: Internal Elements Leak into Chat Pane During Usage-solved

### ISSUE THREAD

**Issue by daizhengxue** [logancyang/obsidian-copilot#438]
While using the Obsidian Copilot plugin, internal elements of the conversation are inadvertently displayed in the chat pane, which detracts from the visual appearance of the interface. This occurs during regular usage of the plugin where the chat pane is expected to show only user and AI dialogues.
![image](https://github.com/logancyang/obsidian-copilot/assets/47060721/211ada18-10d7-478c-95eb-f1502266ca59)

Steps to reproduce:

Open Obsidian with the Copilot plugin enabled.
Start a conversation in the Copilot chat pane with **LM studio**
Observe as internal script or debugging information appears in the chat pane alongside the conversation.
Expected behavior
The chat pane should display only the dialogues between the user and the AI without any internal scripts or debug information. This ensures a clean and distraction-free user interface.

Additional context
No additional plugins were active during the occurrence of this issue. This problem seems to persist across multiple sessions, affecting the usability and aesthetic of the Copilot plugin.

**Comment by Salamantopo** [comment]
I have the same issue. It's actually very annoying, but it started to appear recently. I think it began after the last update of LMstudio to its latest version, 0.2.22.

**Comment by forfai** [comment]
I have reinstalled LM Studio version 0.2.21, and this version is displaying normally.
