### ISSUE TITLE
Support for GPT-4o

### ISSUE THREAD

**Issue by Gnopps** [logancyang/obsidian-copilot#447]
Thanks for developing this plugin! Would it be possible to add support for OpenAI's newly released model GPT-4o?

https://openai.com/index/gpt-4o-and-more-tools-to-chatgpt-free/

**Comment by emssik** [comment]
Yes, please :))

**Comment by peko-dot** [comment]
A corresponding PR has already been created!

https://github.com/logancyang/obsidian-copilot/pull/446

**Comment by loerzi** [comment]
I would also love to see this 👍

**Comment by Fusion** [comment]
Guys, in the meantime if you're as impatient as I am, you can install this fork using BRAT: https://github.com/Fusion/obsidian-copilot

You can inspect the changes here: https://github.com/Fusion/obsidian-copilot/commit/34142f4e1da0be8a3d7be602d3ac4074af615b61

It's basically GPT-4o and while I was at it I also merged Groq support.

Hopefully Logan returns soon and I'll retire the fork 😺

**Comment by VOOM108** [comment]
> Guys, in the meantime if you're as impatient as I am, you can install this fork using BRAT: https://github.com/Fusion/obsidian-copilot
I did that, now I can't figure out, how to actually open a note or sidebar-tab to use it. I deactivated the official version, the commands for CFRCopilot do not show up, and I can't seem to be able to add hotkeys like the ones I am using with the official version.

**Comment by jeansordes** [comment]
> > Guys, in the meantime if you're as impatient as I am, you can install this fork using BRAT: https://github.com/Fusion/obsidian-copilot
> 
> I did that, now I can't figure out, how to actually open a note or sidebar-tab to use it. I deactivated the official version, the commands for CFRCopilot do not show up, and I can't seem to be able to add hotkeys like the ones I am using with the official version.

Don't forget to reload the app so that the UI updates

**Comment by macnversion** [comment]
yes, please

**Comment by rubenssoto** [comment]
@Fusion Hey man, do you have any updates on this? :)

**Comment by SyndicatedPillbug** [comment]
OOoh, I want this too. And also, please add Groq!

**Comment by Fusion** [comment]
> @Fusion Hey man, do you have any updates on this? :)

Not quite sure at this point. I was expecting Logan to resurface within the last couple months, especially since it appears a lot of work went into this extension.
I guess I could work on the existing fork, with a name like "stopgap-copilot" and release it to the official plugin list? I understand that two months is getting to be a long time...

**Comment by Fusion** [comment]
# UPDATE

It looks like Logan merged the code in version 2.5.3 yesterday:

https://github.com/logancyang/obsidian-copilot/commit/0a35a496fd23efd982a18e2bc506c4c29c3942be

**Comment by solaSell** [comment]
I have a valid API Copilot key. In attempting a chat, or QA or whatever, Copilot lists all requests logged in. However, for each of those it provides no responsive feedback. Has anyone experienced this?

**Comment by logancyang** [comment]
@solaSell could you open a separate issue with screenshots of your setting and dev console? This is not enough info to answer your question.
