### ISSUE TITLE
I cannot find command like "Copilot: add custom prompt". Then I cannot do prompt to selection

### ISSUE THREAD

**Issue by homeway999q** [logancyang/obsidian-copilot#455]
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

**Describe how to reproduce**
A clear and concise description of what the bug is. Clear steps to reproduce the behavior

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary. 

**Additional context**

**Comment by logancyang** [comment]
Missing commands when note not in focus bug
