### ISSUE TITLE
Edit custom prompt - not working

### ISSUE THREAD

**Issue by jritsema** [logancyang/obsidian-copilot#458]
**Describe how to reproduce**
I just starting using this awesome plugin.  However, when I select the command, `Copilot: Edit custom prompt` it just says, "No results found".

**Expected behavior**
I'm not sure if this is officially supported or not.  I'm expecting the ability to specify a user prompt template, something like this.

```
{context}
Please read the user's question supplied within the tags. Then, using only the contextual information provided above within the tags, generate an answer to the question.
{question} 
```

I'm finding that in `Long Note QA` mode, the LLM is using a lot of its own knowledge in its responses.  I'm wanting to constrain it more to using just the information contained in the note.

**Screenshots**

<img width="851" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/934927/e50e20c8-f558-4e34-ace4-ce382505c8b7">

<img width="853" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/934927/d1444b0f-be00-4904-a9f1-8977a333c163">

**Comment by brunompicinini** [comment]
You gotta create a prompt first (add custom prompt)

**Comment by jritsema** [comment]
I don't have that command for some reason? only Edit/Delete (in screenshot).

**Comment by brunompicinini** [comment]
oh sorry misunderstood. My bad! Have you tried searching for "add custom prompt". Search inside hotkeys in settings as well. See if it's there

**Comment by logancyang** [comment]
Yeah this is an issue when you don't have the note window in focus. Will need to fix this.
