### ISSUE TITLE
cannot use qwen model created by alibaba

### ISSUE THREAD

**Issue by wangzhankun** [logancyang/obsidian-copilot#461]
# bug

I'm using the API of Tongyi Qianwen in proxy mode. I've successfully experimented with it on Lobechat, but I'm encountering network errors with this plugin.
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/4f9bd665-7400-48e2-a7eb-2d7d79f9a2f2)

qwen for openai: https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope/

# settings for copilot
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/54a2ea91-9e10-4de4-9229-045557bd5a7f)
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/204e8c65-cde0-4215-ab50-ebb7b856027b)
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/a55973b4-913c-47af-b711-c30fed52ca15)
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/76be4bf5-2d3c-4baf-820f-6ee4ff1d00c0)
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/9768246d-be8d-4d06-b90a-18097c7b6f59)
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/44a89269-b017-4341-adc4-ca8d2af52bbc)
![image](https://github.com/logancyang/obsidian-copilot/assets/35724924/39c1246b-6cfe-4046-8d64-166132f33a7f)

**Comment by KaiyoungYu** [comment]
for users in mainland china, providers domestic are better options. I also wait for an update on this.

**Comment by logancyang** [comment]
This https://github.com/logancyang/obsidian-copilot/pull/495 should have fixed this, just enable the local proxy when you see CORS issue with an OpenAI replacement provider.
