### ISSUE TITLE
部分命令丢失，影响使用。

### ISSUE THREAD

**Issue by Wooden-Gear** [logancyang/obsidian-copilot#469]
部分命令丢失，但在快捷键设置界面还能找到，就是不起作用。
上面图中Copilot:  Add  custom  prompt命令就丢失了。
但在下图的快捷键设置界面还能看到，也能设置快捷键，但快捷键不起作用。

![Quicker_20240615_120216](https://github.com/logancyang/obsidian-copilot/assets/143693404/b5d3e09b-4f3d-4ed3-93b0-ead3a829cf45)
![Quicker_20240615_120942](https://github.com/logancyang/obsidian-copilot/assets/143693404/ba1c54d9-856a-4089-a58d-3ed969cddb21)

**Comment by logancyang** [comment]
这是一个known bug, 因为光标没有在主窗口，那几个command有些需要选中文字，所以主窗口没有focus的时候那几个command就被disable了。下面的版本会修复。
