### ISSUE TITLE
Add Support for Cloudflare Worker AI

### ISSUE THREAD

**Issue by minhtringuyennn** [logancyang/obsidian-copilot#476]
**Is your feature request related to a problem? Please describe.**
Obsidian Copilot currently does not integrate with Cloudflare Worker AI. Utilizing Cloudflare's generous free tier and serverless architecture would reduce dependency on local computer resources, unlike solutions such as Ollama.

**Describe the solution you'd like**
Integrate Cloudflare Worker AI with Obsidian Copilot. Cloudflare provides intuitive API documentation, allowing users to set up a Worker AI that exposes an API endpoint and specify the necessary parameters for the computation.

**Comment by o-mikhailovskii** [comment]
I've managed to add a Cloudflare Worker AI as a 3rd party OpenAI-format model. You could use the following URL for more info on the setup: [https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/](https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/).

**Comment by minhtringuyennn** [comment]
Cool! Thanks for your sharing

**Comment by nemokaul** [comment]
> I've managed to add a Cloudflare Worker AI as a 3rd party OpenAI-format model. You could use the following URL for more info on the setup: https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/.

Hi, I couldn't understand how to use the **Workers AI** model. How do I specify which model to use?  

From the documentation, it seems like the model can be specified as follows:  

```json
{
  "model": "@cf/meta/llama-3.1-8b-instruct",
  ...
}
```

How do I specify this in the **Options** within the extension?  

![Image](https://github.com/user-attachments/assets/51da2bed-34f7-4f16-b2ca-7cf89495d8b3)
