### ISSUE TITLE
Add ability to add new OpenAI Models to the model selection dropdown via settings

### ISSUE THREAD

**Issue by FinickySpider** [logancyang/obsidian-copilot#484]
**Is your feature request related to a problem? Please describe.**

Add option to add new OpenAI Models in the settings page as they come available, to be able to be used and selected in the model selection drop-down.

**Describe the solution you'd like**

Would be great to have a input field to enter the model name and a button to apply, that adds it to the select-able drop-down list.

**Describe alternatives you've considered**

Currently I've just been going through the plugin source and copying a new line for each area where the models are defined and/or used, which works great. But it's a bit of a pain to do every time I'd like a new one added. Not to mention when the plugin updates, I have to go back through and re-add all my non-listed models.

**Additional context**

I wouldn't even mind if there's no error handling for adding models and it's just a free form edit box to write the model name. Really anything would be great for now. Thanks!

**Comment by kreibaum** [comment]
See also https://github.com/logancyang/obsidian-copilot/issues/447

You may need to check if you are using the correct tokenizer.
