### ISSUE TITLE
System Prompt doesn't work fine in valut QA mode

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#488]
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

**Describe how to reproduce**

By modifying the System Prompt, I require that the LLM can only respond in Chinese. In chat mode, the LLM answers in Chinese, and the quality is quite good. However, in the valut QA mode, even if most of my vault is  content in Chinese and I ask questions in Chinese, the LLM usually answers in English, and the quality is very poor. Only when the LLM itself is a Chinese-specific model will it output in Chinese and the quality of the answer is improved.

**Expected behavior**

Under valut QA, let the system prompt really work  to make sure  the LLM  answers in Chinese, improving the quality of the answers base on non-English vault.

**Comment by logancyang** [comment]
This is partially because the RAG prompts are in English. And as you mentioned it also depends on the model you use.

Will need to experiment with this.

**Comment by wwjCMP** [comment]
> This is partially because the RAG prompts are in English. And as you mentioned it also depends on the model you use.
> 
> Will need to experiment with this.

Whether adding a requirement for the language of the answer to the RAG prompts is a solution.

**Comment by logancyang** [comment]
Actually this was a bug. Sorry about that, can you try again.
