### ISSUE TITLE
Option to open Chat window in a new pane instead of the right sidebar?

### ISSUE THREAD

**Issue by luckman212** [logancyang/obsidian-copilot#5]
My right sidebar is a little narrow, and so when I open the Copilot chat feature, it's too small to be comfortable. Then I have to reach for the mouse to resize it, and when done, drag it back to its original size. Little thing, but...

It would be really nice if an option existed to open the Chat window in a larger full size pane e.g. 50-50 split screen view with the note on the left and the Chat on the right...

**Comment by logancyang** [comment]
Hmm, I don't quite follow, can you give an example where another Obsidian plugin works in this "full panel" view?

Personally, I already use it with 50-50 split screen with the note on the left and the chat on the right, shown below:

<img width="2549" alt="Screenshot 2023-05-10 at 4 23 12 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/91c89f7b-8dec-4e70-b230-42859b71650a">

**Comment by luckman212** [comment]
I don't really have any other plugins that operate in a large pane, but I suppose things like Excalidraw or others that render their own view would be examples.

My workspace is typically a split-pane view with editor mode on the left and preview on the right, so my right sidebar is what I would consider a "standard" width, just enough for most plugins, but not ideal for large amounts of text like what is produced by Copilot.

![screenshot_oqgwGoOh](https://github.com/logancyang/obsidian-copilot/assets/1992842/ef3725fc-9557-4888-9e3d-e4197e64c181)

**Comment by logancyang** [comment]
I see, thanks for the suggestion. Will think a bit about the best way to do this.

**Comment by logancyang** [comment]
Added a new command to toggle in the note area, release v2.3.5.

**Comment by luckman212** [comment]
Nice, thank you 🙏
