### ISSUE TITLE
[FR] Better suited for long conversation needs

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#504]
**Is your feature request related to a problem? Please describe.**

The current conversation mode is only suitable for simple, brief exchanges; it retains only one conversation at a time. It is hoped that improvements can be made to better accommodate the needs of longer conversations.

Including the retention of dialogue, the modification of dialogue, context, and model parameters.

**Describe the solution you'd like**

Below is an implementation of excellent operational logic that is worth referencing.

https://github.com/Bin-Huang/chatbox

**Comment by logancyang** [comment]
Thanks for the suggestion! The referenced project is a good one. My plan for this project is to be lightweight since its a plugin for Obsidian. I plan to build a standalone app that has both text and voice interfaces, with the voice interface as the focus. Those features will be available in that standalone app.

**Comment by wwjCMP** [comment]
I understand, and I hope at least to achieve multi-conversation saving, so it's convenient to continue a conversation at any time.

**Comment by logancyang** [comment]
So loading a previously saved convo is the first step. Will prioritize!

**Comment by logancyang** [comment]
Closing this as conversation history loading is supported now.

**Comment by wwjCMP** [comment]
> Closing this as conversation history loading is supported now.

![image](https://github.com/user-attachments/assets/1571b95b-f0e3-42b0-a769-a3154c3e9baf)
Please cancel automatic saving of conversations and use manual saving.

**Comment by logancyang** [comment]
> > Closing this as conversation history loading is supported now.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/1571b95b-f0e3-42b0-a769-a3154c3e9baf)
> 
> Please cancel automatic saving of conversations and use manual saving.

Just turn it off in settings

**Comment by wwjCMP** [comment]
After loading chat, the location of chat box will change.

**Comment by logancyang** [comment]
@wwjCMP hmm, I haven't seen that. Can you open a new issue with screenshots?
