### ISSUE TITLE
Copilot not working with Google Gemini

### ISSUE THREAD

**Issue by ronaldstg** [logancyang/obsidian-copilot#505]
- [x] <img width="1149" alt="Screenshot 2024-08-13 at 14 06 00" src="https://github.com/user-attachments/assets/ac7a276b-943b-466d-bdd4-212e40a42228">

**Describe how to reproduce**
Just select Gemini Flash or Pro and ask something 

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary. 

**Additional context**

**Comment by logancyang** [comment]
Works for me. Did it say anything about your API key? Try resetting the settings and reentering the Google API key.
