### ISSUE TITLE
Default cursor location is chat-input-container

### ISSUE THREAD

**Issue by frarinha** [logancyang/obsidian-copilot#510]
**Is your feature request related to a problem? Please describe.**
The need to move the mouse and select the chatbox.

**Describe the solution you'd like**
Upon the toggle of the right window on obsidian, where the `copilot-chat-view` is, the default cursor location would be the `chat-input-container`. You could just toggle the window and immediately start interacting with the LLM.

**Comment by Emt-lin** [comment]
@logancyang I try to fixed this bug, pls check it. thanks

**Comment by logancyang** [comment]
@Emt-lin You are welcome to create a PR and I can take a look.

**Comment by logancyang** [comment]
@frarinha @Emt-lin why do we have this issue again? When I toggle the chat window, the cursor is in the chatbox.

**Comment by Emt-lin** [comment]
@logancyang 
- [x] case 1：When I click on the chat icon in the left sidebar, the cursor appears in the chat box.
- [ ] case 2：When I switch from the chat area to the notes area(or others) and then back to the chat area, the cursor isn't in the chat box.
- [ ] case 3：When I switch items in the right sidebar(eg: outline item and chat item), it's the same as in Case 2.

I'm guessing @frarinha's idea is these unfinished case above.

**Comment by logancyang** [comment]
@Emt-lin how do you switch areas in case 2 and 3?

**Comment by frarinha** [comment]
It's when you toggle (to expand and collapse) the obsidian's right side pane. The cursor is not on the chat input box. 
We can now add an hotkey to **Copilot: Toggle Copilot Chat Window**, but if the right side pane is in the collapsed state, you have toggle it twice, off and back on, and it will open the copilot chat window and the cursor will be there.

**Comment by Emt-lin** [comment]
@frarinha because When you toggle **Copilot: Toggle Copilot Chat Window** , the chat window will be closed at first  if  **a chat window** exist.

```ts
  toggleView() {
    const leaves = this.app.workspace.getLeavesOfType(CHAT_VIEWTYPE);
    // here
    leaves.length > 0 ? this.deactivateView() : this.activateView();
  }
```

@logancyang

**Comment by Emt-lin** [comment]
@logancyang sorry,something happened last weekend.
case 1、2、3 in order

![Kapture 2024-09-09 at 10 37 54](https://github.com/user-attachments/assets/f8f36db5-d4a7-4949-82b8-39ae7e7ac589)

**Comment by logancyang** [comment]
@Emt-lin that's for the recording, I added some comments on your PR, let me know if they make sense.
