### ISSUE TITLE
Show the default system prompt in the system prompt field

### ISSUE THREAD

**Issue by stankovictab** [logancyang/obsidian-copilot#511]
**Is your feature request related to a problem? Please describe.**
There's no way to know the default system prompt the plugin uses unless you enable debug mode and see it in the console. 
For anyone wondering it's `You are Obsidian Copilot, a helpful assistant that integrates AI to Obsidian note-taking.`. 

**Describe the solution you'd like**
I'd like to have a toggle in the settings to turn off the default user system prompt, 
as well as have the default system prompt already in the input field as placeholder, to know what it is. 

For now setting it to ` ` (space) does the job. 
Thanks in advance! :)

**Comment by logancyang** [comment]
A toggle just for switching off the default prompt seems a bit weird. It should be updated in the text field. 

Showing the current default prompt in the system prompt field is needed though, I agree.

**Comment by i13-ctflora** [comment]
@logancyang - The user system prompt field no longer shows the default system prompt when blank as of the latest release (v2.8.0).  It simply shows "Enter your system prompt here..." for the placeholder.

**Comment by logancyang** [comment]
@i13-ctflora right now user system prompt is appended to the default, not overriding anymore. This is because some features rely on the default prompt, so it's better not to show or override it. Advanced users can still see it via debug mode or code.

**Comment by i13-ctflora** [comment]
Gotcha, and thank you!

**Comment by mpetruc** [comment]
Some models (like gemma-2-27b) do not accept system role and produce this error:
```
Connection error.
more message: "TemplateError: System role not supported"
```  
would be useful to enable/disable the system prompt per model.
