### ISSUE TITLE
希望能够保存多个模型，方便根据需求切换。

### ISSUE THREAD

**Issue by Wooden-Gear** [logancyang/obsidian-copilot#512]
希望加入保存多个不同公司的模型和API的功能，方便根据需求切换。

**Comment by logancyang** [comment]
我想到的是类似于cursor，可以toggle自己定义的模型，只要给出名字API和key就保存，类似于custom prompt目前的保存方式。欢迎补充

**Comment by wwjCMP** [comment]
> 我想到的是类似于cursor，可以toggle自己定义的模型，只要给出名字API和key就保存，类似于custom prompt目前的保存方式。欢迎补充

可以参考text generator 插件的做法

**Comment by logancyang** [comment]
Closing as 2.6.0 is out.
