### ISSUE TITLE
[FR] Implement Cursor style model setting

### ISSUE THREAD

**Issue by logancyang** [logancyang/obsidian-copilot#524]
<img width="872" alt="SCR-20240822-phpb" src="https://github.com/user-attachments/assets/63db27a6-3772-40e1-af17-0cb912d94a5b">

It should look something like the above, but with more options

```
actual model name | provider | toggle |
Optional API endpoint URL (OpenAI format) <-- this is 3rd party API, provider can be set to OpenAI as a placeholder with this URL filled |
Add button
```

- toggle builtin models on and off, show model provider column next to the name
- allow adding more custom models, they can choose an existing provider or set a custom endpoint url with provider as OpenAI (since it's a replacement)
- all models added appear in the model picker in chat UI
- (LM Studio just updated to 0.3.0 and it broke Copilot, need to get this in sooner)

**Comment by shwanton** [comment]
> (LM Studio just updated to 0.3.0 and it broke Copilot, need to get this in sooner)

Tried to get Copilot working w/ LM Studio and ran into this. The model Copilot uses is `check_model_in_lm_studio_ui` and there doesn't seem to be a way to configure it in Obsidian.

**Comment by logancyang** [comment]
@shwanton yeah because LM studio has updated to use an explicit model name for the API call. It will start working again when this PR is merged.
