### ISSUE TITLE
CORS policy blocks embedding models for QA

### ISSUE THREAD

**Issue by unicorn-kp** [logancyang/obsidian-copilot#528]
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

This bug report is for using OpenAI embedding. Upon indexing, CORS policy blocks a POST. However, Vault QA indexing seems to recover after an attempt. 

The CORS issue has popped up now for Long Note and Vault QA when using both an OpenAI embedding model as well as a self-hosted OpenAI API clone. The self-hosted clone is not able to index any file within the vault due to the CORS policy block.

**Describe how to reproduce**
- Reset settings
- Add OpenAI secret
- Keep default `text-embedding-3-small`
- Test chat (works)
- Switch to Vault QA
- Select `Refresh Index for Vault`

**Expected behavior**
Vault begins to index all pages

**Screenshots**

<img width="453" alt="image" src="https://github.com/user-attachments/assets/4b2317a5-e0d5-4cb9-ae97-ba51d9726ce7">

![image](https://github.com/user-attachments/assets/ce6c557d-0433-4d8e-918a-b6e572230b7b)

**Additional context**
#495 seems to have resolved the CORS issue for chat with a self-hosted OpenAI API clone, but I don't believe the proxy was integrated for Long Note QA or Vault QA.

**Comment by logancyang** [comment]
@unicorn-kp For your self-hosted clone, were you able to Allow CORS on the server side? That is the way to go.

**Comment by unicorn-kp** [comment]
I'll see if we can explicitly allow traffic from Obsidian.

**Comment by logancyang** [comment]
This should be good from 2.6.0.
