### ISSUE TITLE
[FR] Add a customizable prompt for "send notes to prompt" button

### ISSUE THREAD

**Issue by h4c5** [logancyang/obsidian-copilot#568]
**Is your feature request related to a problem? Please describe.**
It would be great to allow the user to customize the prompt used by the "send notes to prompt" button.
It is particularly useful to use a different language in this prompt.

**Describe the solution you'd like**
Add a customizable prompt in the settings and use it in the `sendNotesContentPrompt` function.

**Describe alternatives you've considered**
One can rely on custom prompt template but is much less handy than "send notes to prompt" button.

**Additional context**

- Send Notes Prompt Configuration
  ![image](https://github.com/user-attachments/assets/d411f9c9-653c-45db-8a08-ead953686345)

- Debug view of the custom prompt
  ![image](https://github.com/user-attachments/assets/62b27eb3-5799-4d1a-9122-2a79b675f6f9)

**Comment by logancyang** [comment]
As discussed, closing this one now. Thanks for the PR though.
