### ISSUE TITLE
Can't generate answer

### ISSUE THREAD

**Issue by Cocodinghk** [logancyang/obsidian-copilot#570]
Hi, I am a new user of obsidian-copilot. I set my API key and then put my question into the prompt, but there was no response. I searched through the web while not found an answer. Why was that? 

<img width="502" alt="image" src="https://github.com/user-attachments/assets/b8f405d4-c3b9-41db-bb2b-ceecac3fcf5b">

**Comment by logancyang** [comment]
Can you turn on debug mode and provide screenshot of your dev console for messages as the issue instruction suggests.

**Comment by Cocodinghk** [comment]
Sure and here it is. Maybe that I do not have access to it? The other image shows where I copied my API key.

<img width="559" alt="image" src="https://github.com/user-attachments/assets/8e721a6e-d30d-4384-8c8f-94bbde99a457">
<img width="904" alt="image" src="https://github.com/user-attachments/assets/560a8636-0369-4877-90df-c0198fa51895">

**Comment by logancyang** [comment]
Do you have a payment method on record with OpenAI? That's the first thing to do. Second, go to their playground and test is you can use gpt-4o correctly. Then there should be no issue here.

**Comment by jeremyjdodd** [comment]
I have the same issue. To clarify, is there an additional step I need to perform on OpenAI even if I'm a Plus subscriber?

**Comment by logancyang** [comment]
Please check the doc for how to get started https://www.obsidiancopilot.com/en/docs/
