### ISSUE TITLE
Gemini 1.5 Pro is error while Gemini 1.5 Flash is working perfectly

### ISSUE THREAD

**Issue by antonsapt4** [logancyang/obsidian-copilot#571]
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/05832f44-5588-4861-9397-efb4cb20945a">

**Describe how to reproduce**
Click model provider from chat and choose "Gemini 1.5 Pro"

**Expected behavior**
Gemini provide answer when prompted

**Additional context**
I think there are new model coming out from Gemini, and the Gemini 1.5 Pro either change name or I dont know what went wrong.
The 1.5 Flash is working perfectly.

**Comment by logancyang** [comment]
500 is server side, not a Copilot issue. Is 1.5 Pro paid or rate limited? You can reach out to Google support.

**Comment by antonsapt4** [comment]
Ah yes, I'm using the free tier, sometime it works but sometime it doesnt. Will close this issues. Thanks @logancyang
