### ISSUE TITLE
Hope to support openai  compatible LLM API and Model

### ISSUE THREAD

**Issue by brucevoin** [logancyang/obsidian-copilot#573]
Good Job.

But I hope User can set the model name and API  base url  not select.
for example , I want to set Model with  'gemma' and the API base url with 'https://api.xxx.com' , now  I can set API proxy, but can not set the model, because it not exist in dropdown list.

**Comment by logancyang** [comment]
Right now you override openai, meaning when you set the proxy you choose any openai model in the dropdown.

But that changes soon: #567
