### ISSUE TITLE
Reference active note directly in custom prompt

### ISSUE THREAD

**Issue by Emt-lin** [logancyang/obsidian-copilot#574]
**Is your feature request related to a problem? Please describe.**

When i'd like to setup custom prompt, i want to select `active note` in this custom prompt. So what should i do?

![CleanShot 2024-08-30 at 18 28 20|500](https://github.com/user-attachments/assets/09aedcb1-37be-4c16-b9e0-0049d4c8cd0a)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by logancyang** [comment]
You can set `{}` and select everything in that note. But next we can just add `[[title]]` in the custom prompt, it's a good first issue for anyone who wants to contribute.

**Comment by Emt-lin** [comment]
@logancyang When i use `{}` option, it already selected  all content in this `active note`. i don't select anything content in that note.

**Comment by logancyang** [comment]
@Emt-lin Oh yes you are right! Then this issue can be closed? Just need to let people know in the documentation.

**Comment by Vadych** [comment]
I would like to return to this issue. 
There is really not enough opportunity to transfer note title to the promt. If possible, the contents of child notes and notes referring to the current note

**Comment by Emt-lin** [comment]
@Vadych ok. 
@logancyang what do you think?

**Comment by logancyang** [comment]
@Vadych this issue is about referencing active note. Are you requesting referencing connected notes? That's a difference issue somewhere it exists.

**Comment by Vadych** [comment]
@logancyang let's focus on the current note. 
I would suggest doing {{ActiveNoteTitle}} и {{ActiveNote}}. 
There may be cases when it is necessary to distinguish between {{ActiveNote}} and {{select}}
About related notes, I have already developed the idea. Although if there is a {{#tag}}, then using a link between notes looks logical

**Comment by logancyang** [comment]
@Vadych Distinguishing between active vs. selection is definitely needed. For related notes by link, there was a FR before. I'll rename this one to address active note then.

**Comment by logancyang** [comment]
#626 merged, {activeNote} added along with `/` triggering of custom prompt in chat.
