### ISSUE TITLE
Really long context notes results incomplete prompt to Ollama, consider add `num_ctx` for context length on the settings

### ISSUE THREAD

**Issue by antonsapt4** [logancyang/obsidian-copilot#576]
**Is your feature request related to a problem? Please describe.**
- For a really long notes or add several pages of notes results the prompt got cut off

**Describe the solution you'd like**
- Consider Add "num_ctx" on the settings for Ollama

**Additional context**
- I used `Open Web UI` with same identical prompt, with the same context taken from the notes and change the `context_length` to 8000 and it gives satisfactory results
- On Copilot I tried `Token Limit` and increase it to 8000 but the output is not addressing the instructions, look like the prompt got truncated only passed the end of the prompt and the instructions is cut off because its on the very top if I look at the console.
- Cross checked with at Ollama [API documentations](https://github.com/ollama/ollama/blob/main/docs/api.md#chat-request-with-tools) there are `num_ctx` to increase the context length 

Hope this help to give feedback about Ollama, since with Copilot we can really go fully local not to passed our sensitive notes to external provider.

**Comment by logancyang** [comment]
I didn't realize you can set `num_ctx` in the request. I knew you could set it by saving params per model. Once asked for this and their response was that it doesn't make sense to set in a request because each model is different, only saving model params makes sense. I agreed. But then it seems available now 😅

**Comment by antonsapt4** [comment]
Yeah, I guess there are lot of request to add `num_ctx` due to using it with API will always have this kind of issues 😅

But I found the solutions, and for anyone have the same issues can change the modelfiles following their [Modelfiles Documantations](https://github.com/ollama/ollama/blob/main/docs/modelfile.md)

Just create or edit the model and add `PARAMETER num_ctx "8000"` and it will fix the context issues.

You can close or keep it as `Feature Request` @logancyang, because creating new modelfiles is kinda the same with add new model and use another storage 🙏
