### ISSUE TITLE
Ignore certain folder or file in vault QA mode

### ISSUE THREAD

**Issue by teddyzxcv** [logancyang/obsidian-copilot#580]
**Is your feature request related to a problem? Please describe.**
So I have some template saved in my vault for easy access. When I use vault qa mode, embedded model seems little confused about these templates.

**Describe the solution you'd like** 
Add a ignore list where use can choose whatever folder or file that will not be indexed to embedded model.

**Describe alternatives you've considered**
Or maybe a "gitignore-like" file that we can configure which can ignore file or folder by some certain rule. Not user friendly for non developer target group(

**Additional context**

**Comment by logancyang** [comment]
see https://github.com/logancyang/obsidian-copilot/pull/572#issuecomment-2319161283
