### ISSUE TITLE
GPT-4o doesn't work, but GPT-4o-mini does

### ISSUE THREAD

**Issue by SugarMask** [logancyang/obsidian-copilot#584]
A few days ago GPT-4o stopped working with Copilot, but GPT-4o-mini continues to work without problems. I have already tried to change the API several times, but when I ask a question GPT-4o does not respond, although it appears recognized by Copilot. Other models such as llama-3.1 or Claude work fine.

![Obsidian_4wCGzU7At7](https://github.com/user-attachments/assets/e63d63e3-2fcd-4c1d-bfca-a31af8510e0b)

**Comment by logancyang** [comment]
Do you have payment with OpenAI? Pls check the FAQ

> You need to **have access to the model APIs** to use them. Usually they require an API key and a payment method.
> A common misunderstanding I see is that some think they have access to GPT-4 API when they get ChatGPT Plus subscription. It's not always true (depending on when you signed up). _You need to have access to GPT-4 API to use the model in this plugin_. Please check if you have payment available on your OpenAI account. Then check OpenAI playground if you can use that particular model https://platform.openai.com/playground?mode=chat. Again, API access and ChatGPT Plus are two different things! You can use the API without the ChatGPT Plus subscription.

And why it replied in Spanish when you said hello? Interesting

**Comment by Megagoth1702** [comment]
In addition to the above comment, I looked into the console output and realized that my Output Token Number was too high. Set it back to 4000, works. 

![image](https://github.com/user-attachments/assets/2c75b713-d193-4aa5-9cf3-4a0b49da5003)

**Comment by SugarMask** [comment]
> In addition to the above comment, I looked into the console output and realized that my Output Token Number was set too high. Set it back to 4000, works.
> 
> ![image](https://private-user-images.githubusercontent.com/15914075/363907551-2c75b713-d193-4aa5-9cf3-4a0b49da5003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzOTI4NjIsIm5iZiI6MTcyNTM5MjU2MiwicGF0aCI6Ii8xNTkxNDA3NS8zNjM5MDc1NTEtMmM3NWI3MTMtZDE5My00YWE1LTljZjMtNGEwYjQ5ZGE1MDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE5NDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTBjYTI2MWZjYTUzYWJiY2MwYmQ3ZDVhNDEyNTgwNWJkZWU2NDJjOWVmZTlkMjJjZWYwYWZmZWQyMWYzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d4yKyoFqQA8sCZ4VBJMIcx98EGn-ZHGytYy0qJaY6sA)

Si era exactamente la solución muchísimas gracias 🙏🏻
<img width="804" alt="Obsidian_0YI5xnNnGY" src="https://github.com/user-attachments/assets/e408a97b-5ba5-414a-b3d9-9f63d2d2464d">
