### ISSUE TITLE
Alternative method for interacting with custom prompts

### ISSUE THREAD

**Issue by pedramamini** [logancyang/obsidian-copilot#590]
I've kicked the tires on various GenAI implementation plug-ins in Obsidian. One of the better patterns for managing custom prompts is to configure a folder containing them. This allows for a single source of prompts to be used across multiple GenAI integrations (including outside of Obsidian via the .md files on disk). 

Perhaps should be a separate issue,  but then being able to interface with the prompts, through the copilot chat, via tab-completable @PROMPTNAME. So when you're chatting with CoPilot directly, you can invoke a prompt easily.

**Comment by logancyang** [comment]
I'm actually moving custom prompts to markdown out of pouchdb to support Obsidian Sync next, since mobile support is out now. So this is coming.

Will think about how tab completion for prompts should work. Copilot prompts are **templates** with selection, note titles, paths and tags, and not just some "Act like x" sort of pure text prompt. Most likely I'll have `/prompt` show a list of prompts, selecting one puts the custom prompt in the chat input. Then Copilot knows how to render the template because it's a `/prompt` command.

**Comment by logancyang** [comment]
@pedramamini btw what's your favorite plugin among your tested ones? Not sure if there can be a unified pattern using markdown for custom prompts.

For now I'm thinking one custom prompt per md file under a specified folder. Any specific suggestion is welcome.

**Comment by pedramamini** [comment]
Yes, one prompt per MD is probably the best way. I've played with:

- Ayanite

- Caret

- Smart Connections

- Text Generator

Ayanite is the cleanest, here are some screen grabs:

/ (Search chat commands)

' (Search message history)

@ (Search models and profiles)

; (Search recent chats)

. (Search prompts)

Some settings grabs:

**Comment by pedramamini** [comment]
Bleh not sure what happened there with email response or comment editing, but the screen grabs should be accessible now.

**Comment by logancyang** [comment]
@pedramamini nice thanks! Haven't seen Ayanite, looks pretty good, and I didn't know you can have it closed-sourced at still distribute in the Obsidian plugin store. My plan for copilot is quite similar. For chat experience, the inspiration I'm looking at is mostly https://github.com/mckaywrigley/chatbot-ui.

**Comment by logancyang** [comment]
- [x] Custom prompt in folder done, don't forget to use the new command `Dump custom prompts to markdown files` for existing prompts.
- [ ] Prompt trigger in chat

**Comment by pedramamini** [comment]
Nice work on the folder usage. Love it!
