### ISSUE TITLE
Delete and edit both user and AI messages

### ISSUE THREAD

**Issue by Wooden-Gear** [logancyang/obsidian-copilot#596]
新功能很好用，希望用户和AI内容都能编辑和删除

**Comment by neojinmingli** [comment]
translate: 

The new features are great to use, and hopefully both the user and the AI content can be edited and deleted

发英文，开源开发者没有义务翻译你的 issues，打开浏览器翻译一下就几秒的事

**Comment by Wooden-Gear** [comment]
> translate:
> 
> The new features are great to use, and hopefully both the user and the AI content can be edited and deleted
> 
> 发英文，开源开发者没有义务翻译你的 issues，打开浏览器翻译一下就几秒的事

开发者不是中国人吗？我发英文他还得脑子里过一遍

**Comment by logancyang** [comment]
English is better since most people can follow what's going on.

The reason I was hesitant editing/deleting chat history was that you can have a list of only user messages, or a sequence that does not make sense at all. It could make regeneration look wrong and buggy. Chatgpt UI doesn't have this, for example.

But I get the appeal. Whoever wants this please thumbs up this issue.

**Comment by Wooden-Gear** [comment]
> English is better since most people can follow what's going on.英语更好，因为大多数人能理解发生了什么。
> 
> The reason I was hesitant editing/deleting chat history was that you can have a list of only user messages, or a sequence that does not make sense at all. It could make regeneration look wrong and buggy. Chatgpt UI doesn't have this, for example.我犹豫编辑/删除聊天记录的原因是，你可能会有一个只包含用户消息的列表，或者一个完全没有意义的序列。这可能会使重新生成看起来错误和有 bug。例如，Chatgpt UI 就没有这个问题。
> 
> But I get the appeal. Whoever wants this please thumbs up this issue.但我能理解。如果有人需要这个，请为这个问题点赞。

Alright, I will translate it later, but it's certain that pure machine translation won't be as accurate as Chinese.

**Comment by logancyang** [comment]
Delete button is added. I don't plan to add the edit button to AI message at this point, if you really need to do that, you can save the chat to note and edit there, and then load it.
