### ISSUE TITLE
Focus input textarea when activating Chat

### ISSUE THREAD

**Issue by luckman212** [logancyang/obsidian-copilot#6]
Since cursor focus is lost from the current note editor anyway when invoking the hotkey, you might as well activate/focus the _Enter your message here_ field:

<img width="325" alt="screenshot_Go9kQ5gG_gh" src="https://user-images.githubusercontent.com/1992842/236638449-47da6c1e-2894-40bd-b521-05a826c12fe7.png">

**Comment by logancyang** [comment]
@luckman212 Thank you for the suggestion, will look into this!

**Comment by logancyang** [comment]
This is implemented in the latest release 1.2.3. Closing for now, please let me know if there's unexpected behavior!

**Comment by luckman212** [comment]
Works for me!
