### ISSUE TITLE
Discord channel link broken

### ISSUE THREAD

**Issue by agu3rra** [logancyang/obsidian-copilot#601]
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

**Describe how to reproduce**
I am trying to join the linked Discord invite on [Contributing.md](https://github.com/logancyang/obsidian-copilot/blob/master/CONTRIBUTING.md#getting-help), but it appears to no longer be valid.

**Expected behavior**
I am allowed into the Discord channel upon clicking the invite.

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary.
![Screenshot_20240905_210157_Samsung Internet](https://github.com/user-attachments/assets/31b44d3e-3290-4d63-b318-9d910e95cab4)

**Additional context**
None.

**Comment by logancyang** [comment]
Thanks for letting me know! Recreated a new link.
