### ISSUE TITLE
Why is there no local model setting in my interface?

### ISSUE THREAD

**Issue by Elonyiwang** [logancyang/obsidian-copilot#606]
! [image](https://github.com/user-attachments/assets/5df2d4c8-0571-4197-9d53-2d45aea031df)
Can you please tell me how to set up Local model in this case?I tried to create LM Studio and Ollama in Custom model and the chat fails!

**Comment by logancyang** [comment]
Don't you guys watch my release video 😢

**Comment by Elonyiwang** [comment]
> Don't you guys watch my release video 😢
>
> https://youtu.be/l-x_QwSNghE?si=cwn9UL1pkecN3IAH

Thanks, it worked!

**Comment by chiangs** [comment]
Running Ollama and phi3:14b was working before the update and with the update, even adding the model, I am getting a 404 on my query. I have tried re pulling both the model and embedding model and reloading

[GIN] 2024/09/06 - 12:03:07 | 404 |     580.375µs |       127.0.0.1 | POST     "/api/chat"
