### ISSUE TITLE
After new update Ollama with phi3:14b getting 404

### ISSUE THREAD

**Issue by chiangs** [logancyang/obsidian-copilot#609]
Running Ollama and phi3:14b was working before the update and with the update, even after adding the model, I am getting a 404 on my query. I have tried re pulling both the model and embedding model and reloading.

Indexing works, and I am on zsh.

using `OLLAMA_ORIGINS=app://obsidian.md* ollama serve`

`[GIN] 2024/09/06 - 12:03:07 | 404 |     580.375µs |       127.0.0.1 | POST     "/api/chat"`

From the console it looks like it's trying to query llama3 model instead, i have tried other models and the error is the same, it always says "llama3" not found.

This is happening **both** on my Windows PC and Mac M1.

when I use `ollama run phi3:14b or any other model` the query works fine in the terminal.

I tried pulled Llama3 and now it works in Obsidian, even though the model is set to `phi3:14b`, i have also tried setting it to `phi3-14b`... any idea what is going on here?

![Screenshot 2024-09-06 at 12 24 50](https://github.com/user-attachments/assets/152c91f8-5db1-455c-a5a8-2da3ee6d24e3)

Here is the list of my models before pulling llama3.

<img width="445" alt="Screenshot 2024-09-06 at 12 26 40" src="https://github.com/user-attachments/assets/ecda8c2a-2e7a-4106-af9e-4c0d054401df">

![Screenshot 2024-09-06 at 12 43 46](https://github.com/user-attachments/assets/8a87c757-f09c-443b-9d25-fec4780cd98f)

**Comment by logancyang** [comment]
This is addressed by #607. Will push a new release.

**Comment by logancyang** [comment]
2.6.4 out. If it's still not working pls reopen

**Comment by chiangs** [comment]
The update fixed it, thanks!
