### ISSUE TITLE
[BUG] After loading chat, the location of chat box will change.

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#615]
![image](https://github.com/user-attachments/assets/a9bcfbeb-97ed-4afb-9fc3-523647b0be75)
![image](https://github.com/user-attachments/assets/a8d5bbc8-dd1d-4d49-9dce-72e0952c5cee)

**Comment by logancyang** [comment]
What device is this? Can't really see what's going on.

**Comment by wwjCMP** [comment]
> What device is this? Can't really see what's going on.

PC

**Comment by wwjCMP** [comment]
> What device is this? Can't really see what's going on.

the chat box change from the bottom to the  top

**Comment by logancyang** [comment]
That's interesting, I personally haven't seen this. Do you still see it when all other plugins are disabled?

**Comment by logancyang** [comment]
Ok I see the issue, fix coming.

**Comment by logancyang** [comment]
#620. It also avoids opening the saved convo on autosave, to be less intrusive.
