### ISSUE TITLE
After mobile update, chat interface is not responding. 

### ISSUE THREAD

**Issue by dvl00** [logancyang/obsidian-copilot#616]
Hi there. 

This obsidian extension is awesome. Way better than other ones I have tried. My vault is quite large, and it worked well! It stopped working, after the mobile update was released. 

Does not work in my computer or on my phone. 

It says 

![image](https://github.com/user-attachments/assets/c6912a67-cba5-4f48-a0bb-b941ee347bb2)

My settings have not changed since I installed this extension. Gpt-4 turbo, 4000 token output, 0.1 temp, 10 file reference, encrypt key. 

Please let me know what im doing wrong! would really appreciate.

**Comment by logancyang** [comment]
@dvl00 thanks for reporting. Can you try resetting copilot settings, set the embedding models again. The new version has a different way of model setting. If that still doesn't work, can you take a screenshot of your dev console with only Copilot enabled, debug mode on.

**Comment by dvl00** [comment]
thank you for your response! I have uninstalled and reinstalled the application. This time, I did not change any settings, I litterally just plugged in my open ai api key and saved it. 

Here is a screenshot of my console: 

![image](https://github.com/user-attachments/assets/5746c8f3-cc92-48e9-88b6-669f24c58315)

**Comment by dvl00** [comment]
thank you! problem fixed
