### ISSUE TITLE
Not loading on iPad or iPhone v2.6.4

### ISSUE THREAD

**Issue by stephenhowells** [logancyang/obsidian-copilot#617]
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

**Describe how to reproduce**
Install the plugin as normal and let everything sync. Add in API keys and then pull up Obsidian on mobile.

**Expected behavior**
The Copilot pane should be available in the right sidebar and in the command palette.

**Screenshots**
<img width="542" alt="Screenshot 2024-09-07 at 1 44 39 PM jpeg" src="https://github.com/user-attachments/assets/e255d709-92ec-4d96-8fa2-3d1d948de951">

**Additional context**
I ensured the plugin was installed on the iPad and even force closed and reopened the app. Disabling and reenabling the plugin has no effect.

**Comment by logancyang** [comment]
Hmm, I can use 2.6.4 on my ipad. Not sure what's going on here, anyone else seeing this?

**Comment by jbreyc** [comment]
Same here:
- Obsidian v1.6.7
- Copilot v2.6.6 installed in desktop, iphone and ipad.
- Plugin active and working in desktop.
- Plugin active but not working in iphone nor ipad.

**Comment by gputrain** [comment]
> Same here:
> 
> - Obsidian v1.6.7
> 
> - Copilot v2.6.6 installed in desktop, iphone and ipad.
> 
> - Plugin active and working in desktop.
> 
> - Plugin active but not working in iphone nor ipad (not displayed in command ribbon or right side menu)
> 
> 

same issue on iOS devices

**Comment by Menschomat** [comment]
Same here with Copilot-Version 2.6.9 on IOS 18 with latestes Obsidian-Version
