### ISSUE TITLE
Screen Blackout

### ISSUE THREAD

**Issue by dvl00** [logancyang/obsidian-copilot#622]
Hi there! Thank you for your assistance. 

I've noticed that many times, when I run copilot, my obsidian will blackout. I know I have about 15k notes, but sometimes it just runs fine with no problem. 

Would you be able to help me? When there is a blackout, I cannot do anything. I have to close and restart Obsidian, so I can't even see the console. 

Thnk you!

**Comment by dvl00** [comment]
Actually, I have notice it always does that when I input a difference system prompt.

**Comment by logancyang** [comment]
Hi @dvl00, do you have other plugins enabled? was this happening with only Copilot enabled?

Without the dev console it's impossible to debug. You can open it whenever it is responsive and refresh using cmd R or manually reloading the plugin.

15k notes shouldn't be a problem, Copilot doesn't do indexing or anything at start up.

**Comment by logancyang** [comment]
Please reopen if this happens with v2.7+
