### ISSUE TITLE
Duplication of Sonnet model

### ISSUE THREAD

**Issue by o-mikhailovskii** [logancyang/obsidian-copilot#623]
There seems to be a duplication of Anthropic's Sonnet model in the `constants.ts`.

Here are the lines:
https://github.com/logancyang/obsidian-copilot/blob/8a4bd04b6680ca6dae2a77148f7343a2eeab59df/src/constants.ts#L57C1-L67C5

**Expected behavior**
 Shouldn't one of the models be Haiku?

**Comment by logancyang** [comment]
oh yes thanks for the catch! Updating now.
