### ISSUE TITLE
Custom prompt suggestion

### ISSUE THREAD

**Issue by fareslassoued** [logancyang/obsidian-copilot#624]
**Is your feature request related to a problem? Please describe.**
I want to refer to custom prompts in chat and not on file level

**Describe the solution you'd like**
I want to save custom prompts in a markdown file and refer to them in chat using @ symbol for example

**Describe alternatives you've considered**
using already existing custom prompt, but every time I have to copy the text in a temporary note and run custom prompt on selection.

**Additional context**
given I have a saved custom prompt in markdown for example `create_summary` I want to refer to it in chat using @create_summary of [[note]] or copied text

**Comment by logancyang** [comment]
Related to #590.

I plan to add this to the next release. My idea was to use `/` instead and reserve `@` for future AI agents.
