### ISSUE TITLE
Some buttons are obscured when the sidebar is not wide enough

### ISSUE THREAD

**Issue by ChenZhao44** [logancyang/obsidian-copilot#63]
Hello there,

I am pleased to know that you are enjoying the Copilot extension. However, I have noticed that when the sidebar is not wide enough, some buttons become obscured and inaccessible. This can be troublesome, especially when trying to use the extension on a smaller screen or in split-screen mode.

Would you please investigate this issue and find a solution to make these buttons more accessible? One effective solution would be to place these buttons on multiple lines. It would be highly appreciated if you could address this matter in a future update.

Thank you for considering my concern.

Best regards,
Chen

<img width="471" alt="Screenshot 2023-06-09 at 10 57 27" src="https://github.com/logancyang/obsidian-copilot/assets/50411747/2f79459f-3cf4-4b89-a417-ed5d2f70a2f8">

**Comment by logancyang** [comment]
@ChenZhao44 thanks for reporting. Will post a fix in a future release. Do you mind sharing what device and screen size you are using?

**Comment by ChenZhao44** [comment]
Thanks. I am using a MacBook Air with a 13.3-inch screen. The resolution is 2560 × 1600.

**Comment by logancyang** [comment]
Should be fixed after 2.3.0. Pls reopen if it's not working for you.
