### ISSUE TITLE
Copilot indexing taking a loooooong time

### ISSUE THREAD

**Issue by Luke2791** [logancyang/obsidian-copilot#643]
"Copilot is indexing your vault... 783/875 files processed"
Is it usual for indexing to take 1+ hours? I don't think my vault is the biggest obsidian vault out there... not by a long shot. I have an M2 MacBook Air with 16G of ram. I choose Ollama mistral as the default under "QA Settings". Is this normal, or have I done something wrong?

**Comment by logancyang** [comment]
Please follow the instructions and add screenshot of dev console. 

There's no ollama mistral under QA setting though, which Copilot version are you on? If you have a local ollama server running you can debug using ollama server log.

**Comment by Luke2791** [comment]
I am still having this issue - but I found another solution I am currently pursuing. So it is no longer needed. I may reopen / ask later if I need to. Thanks for all your hard work on the plug in!
