### ISSUE TITLE
在Version 2.6.6中如何使用第三方转发API/How to use the third-party forwarding API in Version 2.6.6

### ISSUE THREAD

**Issue by Euler23333** [logancyang/obsidian-copilot#649]
在先前的版本中（大致是2个月前的版本中）可以设置第三方转发API，但是就在我今天更新了之后发现无法设置（准确来说是现在的界面相较于之前改变，导致我不知道如何设置第三方转发API）
---
 In the previous version (about 2 months ago) you could set up the third-party forwarding API, but after I updated it today, I found that I couldn't set it up (to be precise, the current interface has changed compared to the previous one, so I don't know how to set up the third-party forwarding API)

**Comment by logancyang** [comment]
I recommend subscribing to my channel and watching my release videos

https://youtu.be/l-x_QwSNghE?si=8FI6W-5i0v6ByIiP

I'll have a documentation site soon.

**Comment by Emt-lin** [comment]
There is a simple example. more recommend: https://youtu.be/l-x_QwSNghE?si=8FI6W-5i0v6ByIiP

demo:

![Kapture 2024-09-18 at 10 36 54](https://github.com/user-attachments/assets/4c58ea70-bea4-4cc1-9f57-449f9fc70816)

**Comment by Euler23333** [comment]
Thank you for your assistance!
