### ISSUE TITLE
Sort saved conversations by time / customize filenames in settings

### ISSUE THREAD

**Issue by ngokevin** [logancyang/obsidian-copilot#653]
**Is your feature request related to a problem? Please describe.**

I'd like the customize the format of the saved note filename. 

Mainly, I'd like to at least sort the filenames by datetime.

**Describe the solution you'd like**

I'd like templating options for the time. Or simpler, sort filenames by datetime.

Like personally I want to customize it like: `<% YYYY %>-<%M%>-<%D%>: <% title %>`

The templating also allows me adjusting the separators, like I don't like the mass underscores.

**Describe alternatives you've considered**

Would have to manually rename each chat.

Thank you!

**Comment by logancyang** [comment]
You need to have legal characters in the file name though, `:` is not legal.

**Comment by logancyang** [comment]
Saved conversations are now sorted by time, and the mass underscores in date time have been removed. 

I don't plan to add a setting just for datetime format at the moment though, if you still would like that feel free to submit a PR.

The next thing I have in mind is to name the saved conversation with an LLM call. Closing this for now.

**Comment by ngokevin** [comment]
Thanks! I Appreciate it
