### ISSUE TITLE
[PLUS] Cursor-like context menu with image and PDF support

### ISSUE THREAD

**Issue by Wooden-Gear** [logancyang/obsidian-copilot#671]
中文：
用 “send note to prompt” 功能跟笔记聊天时，笔记中途更改后，读取的还是原来的内容。
希望参考cursor的“add context”功能，每次发送一段新的信息，都读取一遍笔记，以便能读取到更改后的内容。
我个人使用的时候，这样的需求还是很多的。
比如：
我让AI根据笔记内容写一段话，插入笔记中。
因为这时候笔记已经更改，所以之后对笔记整体的修改或者扩写，需要考虑更改之后整体的上下文。
如果AI读取的内容不变的话，就不能很好的联系更改之后的上下文了。
English: 
When using the "send note to prompt" feature to chat with notes, if the note is changed midway, the content read is still the original. I hope to refer to the cursor's "add context" feature, so that each time a new piece of information is sent, the note is read again to capture the updated content. Personally, I have a lot of such needs when using it. For example: I ask the AI to write a paragraph based on the note's content and insert it into the note. Since the note has been changed by then, any subsequent modifications or expansions to the overall note need to consider the updated context. If the content the AI reads does not change, it won't be able to connect well with the updated context.

-- EDIT by @logancyang --

I'm commandeering this issue to be the master task of Cursor-like context menu. It should

- show which files are in "context menu" explicitly, and they should be passed to the model with their most up-to-date version
- PDFs and embedded PDFs can also be added to the "context menu"
- option to add an image with a new "add image" button
- new send button "cmd + enter" for `@vault` query

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/88d9e890-2654-40c9-822f-2605e53524b6">

**Comment by logancyang** [comment]
Yes, this is coming soon.
