### ISSUE TITLE
Anthropic API Code Needs Change in Copilot

### ISSUE THREAD

**Issue by jhmonroe** [logancyang/obsidian-copilot#677]
See attached error when trying to use Copilot with a paid-with-balance Anthropic API Key

"CORS requests must set 'anthropic-dangerous-direct-browser-access' header"

According to this https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5429 the API was changed in the last month and perhaps Copilot needs to have this line of code added?

This person also details the update: https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/

I'm guessing this isn't something I can fix myself? I tried adding "anthropic-dangerous-direct-browser-access": true, to the data.json file or main.js but this isn't enough to avoid the error...

Thanks!
![Screen Shot 2024-09-26 at 1 00 33 PM](https://github.com/user-attachments/assets/966ceb86-f96c-4252-a134-94e4e5809432)

**Comment by logancyang** [comment]
@jhmonroe what version of the plugin do you have? We have it for a while now.
<img width="889" alt="SCR-20240926-kust" src="https://github.com/user-attachments/assets/44d32e43-e518-4bba-bac3-6789d917d5fb">

**Comment by jhmonroe** [comment]
You're the best!! I guess I didn't realize Obsidian doesn't autoupdate plugins. Just switched from 2.5.2 to 2.6.8

WORKING! :-)

Thanks so much for the quick reply and for your plugin! Just bought you a coffee!

**Comment by logancyang** [comment]
@jhmonroe thanks for the support!
