### ISSUE TITLE
editable url for local llama models

### ISSUE THREAD

**Issue by Hafer0** [logancyang/obsidian-copilot#681]
**Is your feature request related to a problem? Please describe.**
I use Obsidian on several machines of quite different power. Using llama requires the installation of the ollama server on each machine. Problem: The power (amount of RAM, availability of GPU etc) on most machines is insufficient.

**Describe the solution you'd like**
The Plugin connects with the local server via `http://localhost:11434`
Make this URL editable in copilot. That way, on all machines (within my local network) I wish to use llama  I replace <localhost> with the local name of a capable server within my local network. 
That allows the _whimsical-but-pretty-windows-machine_ to connect to the _mighty-linux-bolide-I-ve-hidden-under-the-attic_ (and probably even the mobile devices currently connected via vpn to my local network) and utilize its ollama server.

**Describe alternatives you've considered**
I'm not aware of alternatives.

**Comment by logancyang** [comment]
Adding a custom model doesn't address your need?

<img width="781" alt="SCR-20240927-safw" src="https://github.com/user-attachments/assets/a8f4e3bb-aff6-4ea0-9a01-
20a37146d1ae">

**Comment by Hafer0** [comment]
Thanks for your quick response! 
In fact, adding a custom model is exactly what I did. Problem was the connection. 
After resolving that, setting the base url to `http://<server-ip>:1234/v1` did the trick.

Thanks!
