### ISSUE TITLE
Doesn't finish

### ISSUE THREAD

**Issue by ronilaukkarinen** [logancyang/obsidian-copilot#689]
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

![image](https://github.com/user-attachments/assets/82a07b3b-5cc9-42fb-8e45-d18b34f45e1b)

**Describe how to reproduce**

Use any model with any long-ish note and add prompt: "Add markdown formatting to [[something]]"

**Expected behavior**

It should finish through, now it stops mid-sentence.

**Comment by logancyang** [comment]
Are you expecting it to output the super long note (exceeding context window of your picked model) entirely formatted with this query? Not sure if I understand your use case correctly.

**Comment by ronilaukkarinen** [comment]
Yeah, I have some files in text format and the query is "can you add markdown formatting to this note". Some are not even super long and the reply just stops mid-word... never finishes to the end.

**Comment by ronilaukkarinen** [comment]
But it works, it just never finishes.

**Comment by logancyang** [comment]
As the top message mentioned when you switch to that mode, RAG relies on retrieval, the model gets the most relevant chunks to your query, it doesn't see the entire thing. "Doesn't finish" is expected.

**Comment by logancyang** [comment]
This is due to lack of documentation. And actually, Long Note QA is going to be deprecated soon and replaced by new modes. Closing for now.
