### ISSUE TITLE
Support local ai, to ensure privacy

### ISSUE THREAD

**Issue by mdopp** [logancyang/obsidian-copilot#69]
I saw that there is a goal to ensure privacy for this plugin. For me this would mean "it works without sending my notes around the globe and use openai".

On the other hand, there are projects that try to mimic the openai interface, and host LLM locally.

Supporting https://localai.io/ could end up in a simple solution for this. 

Extend options to "OpenAI, HuggingFace, LocalAI", and allow to enter a local URL

**Comment by logancyang** [comment]
I'm looking at this exact thing right now. Stay tuned!

**Comment by logancyang** [comment]
Pushed v2.4.0 with localai support. Feel free to share feedback here or over at LocalAI's repo! Closing this one for now.

**Comment by mdopp** [comment]
Just some feedback: I think this solutioin is overcomplicated from a users perspective. Also it lags the posibility to use an own server with localai.

A perfect enough solution for me would have been:
- enter the URL to an alternative openai-api implementatioin (you already had this)
- retrive the models from the server, instead of hard-code them

this would keep the interface clean and easy for the user, while reducing the amount of code needed.

An alternative could be to enable a list of URLs to openai-api implementations, retrive the available models from all of them, and then show all models+domain/url in the dropbox for model selection.

**Comment by logancyang** [comment]
> Just some feedback: I think this solutioin is overcomplicated from a users perspective. Also it lags the posibility to use an own server with localai.
> 
> A perfect enough solution for me would have been:
> 
> * enter the URL to an alternative openai-api implementatioin (you already had this)
> * retrive the models from the server, instead of hard-code them
> 
> this would keep the interface clean and easy for the user, while reducing the amount of code needed.
> 
> An alternative could be to enable a list of URLs to openai-api implementations, retrive the available models from all of them, and then show all models+domain/url in the dropbox for model selection.

What do you mean by "lacks the possibility to use user's own server with localai"? It IS using the user's own localai server now. If you mean setting it to call any local server as an OpenAI drop-in replacement, you can do that too. But you need to ensure that server is correctly setup with CORS, or Obsidian can't get the response properly. Actually, the "Local Copilot" mode runs a local proxy server to avoid CORS issues. For any non-local OpenAI drop-in, just use the 3rd party URL setting and it should work.

As for the dropdown to retrieve all available models, yes it can be implemented to replace the current text input for model name.

**Comment by AMGMNPLK** [comment]
How can we run this on a MacBook Pro Intel version? I saw that LocalAI has instructions just for M1/M2.

**Comment by AMGMNPLK** [comment]
Thank you @Sokole1 .

I followed the instructions and I got some answers, but not sure in what mode. I'm doing some testing now:

- Test 1: OpenAI Embedding, GPT3.5 16K, conversational: After ask and waiting for 10 minutes it doesn't respond. 

- Test 2: Local Embedding, GPT3.5 16K, conversational: After ask and waiting for 10 minutes it doesn't respond:
<img width="483" alt="Screenshot 2023-08-26 at 12 16 33 PM" src="https://github.com/logancyang/obsidian-copilot/assets/19272675/b52cb62c-3021-4336-9e51-0dbc8b240188">

- Test 3: Local Embedding, LocalAI, Q&A: More than 30 min with no answer
<img width="495" alt="Screenshot 2023-08-26 at 1 06 14 PM" src="https://github.com/logancyang/obsidian-copilot/assets/19272675/6d19bf50-122d-44f8-9be3-a5de74f893cd">

**Comment by Sokole1** [comment]
Hi @AMGMNPLK can you turn on debug mode for Copilot (make sure to reload plugin after). Then screenshot the Copilot logs again?  
Also for your LocalAI setup, can you set `DEBUG=true` in the `.env` file as shown on this page https://localai.io/howtos/easy-setup-docker-cpu/index.html? Then screenshot your debug logs (example screenshot of LocalAI debug log below).
<img width="680" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/68660379/260ecf5a-2727-4124-b1c1-a96e5c970378">
<img width="1267" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/68660379/d389404b-385e-4864-aa40-b1ec06e9e9ac">

Here are logs for a successful request using gpt3.5-turbo.
<img width="1441" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/68660379/4a5f828c-325e-4950-8b76-7213fefb10d0">
