### ISSUE TITLE
LangChain error

### ISSUE THREAD

**Issue by menglei125** [logancyang/obsidian-copilot#70]
Dear Development Team,

Thank you for creating this plugin. I have followed the user guide closely, but unfortunately, I am unable to utilize it successfully. Whenever I attempt to use it, an error message is displayed: "LangChain error: AxiosError: Request failed with status code 429 and body {"error": {"message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null}}".

I would like to know whether this error indicates that I need to upgrade to the ChatGPT Plus subscription in order to use the plugin effectively, or if it is simply not compatible with Obsidian. What can I should do to fix it?

I am eagerly awaiting your response. Thank you for your attention.

Best regards,
Mengelei

**Comment by logancyang** [comment]
Hi @menglei125 , this error usually means that you don't have a payment setup with OpenAI. This plugin is free to use but you still need to pay OpenAI for the API usage. That is different from ChatGPT Plus subscription. You don't need the subscription to use this plugin.

Please take a look at the FAQ section, there's an item about this exact issue.

**Comment by menglei125** [comment]
Thanks a lot for the quick reply!
