### ISSUE TITLE
I am using the qwen2.5:7b local model through Ollama，Error: Model request failed: 404 page not found

### ISSUE THREAD

**Issue by tyf2018** [logancyang/obsidian-copilot#700]
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

I am using the qwen2.5:7b local model through Ollama, which works fine in version 2.6.0 of the Copilot plugin. However, I have been encountering errors in the subsequent plugin versions. For example, in version 2.6.11, it reports an error: "Error: Model request failed: 404 page not found."
![image](https://github.com/user-attachments/assets/c65c37d5-dd27-40d2-b4cf-214735826ec2)

**Describe how to reproduce**
Start any conversation.

**Expected behavior**
I hope to be able to use the qwen2.5:7b local model smoothly through Ollama in Copilot.

**Screenshots**
![image](https://github.com/user-attachments/assets/c8c83146-b737-41f6-b0da-d249b6c9882d)

**Comment by logancyang** [comment]
I tried with 2.6.11 and it works for me. 

<img width="974" alt="SCR-20241003-slva" src="https://github.com/user-attachments/assets/cc5587b5-e21c-4531-a1e4-d6fa2a9b1b82">

1. What's your `ollama list` result?
2. How did you add this custom model to the plugin, can you show me a screenshot

**Comment by tyf2018** [comment]
> 1. What's your `ollama list` result?您的`ollama list`结果是什么？
![image](https://github.com/user-attachments/assets/ef829554-b2fc-4637-8b0d-386f2c1258a3)

> 2. How did you add this custom model to the plugin, can you show me a screenshot你是如何将这个自定义模型添加到插件中的，你能给我截图吗
![image](https://github.com/user-attachments/assets/33ab5619-855d-4469-aac6-214ca4a42c06)

Best regards.

**Comment by logancyang** [comment]
Hmm, this should work 🤔

Just to be sure, can you try without the Base URL? When you pick Ollama as provider you can omit it unless your ollama server is not at localhost.

**Comment by tyf2018** [comment]
Not running normally without the basic URL, it's working now, thanks.
