### ISSUE TITLE
Unable to set up local embedding model for QA function

### ISSUE THREAD

**Issue by stephen-ondyr** [logancyang/obsidian-copilot#703]
- [ x] Screenshot of note + Copilot chat pane + dev console added **(required)**

**Describe how to reproduce**
I am trying to use QA functionality but having issues setting up local embedding. I am using lm studio for chat fine but I keep getting embedding errors. Here's is what I have done

- Downloaded the Windows preview version of ollama
- Pulled the nomic (and llama 3.2) models
- In powershell have run:  $env:OLLAMA_ORIGINS="app://obsidian.md*"; ollama serve
- In the QA settings added nomic-embed-text as the model and ollama as the provider
- Saved settings

This is the console error I get in Obsidian:

Uncaught (in promise) Error: No embedding model found for: nomic-embed-text|ollama
    at EmbeddingManager.getEmbeddingsAPI (VM236 plugin:copilot:133693:13)
    at _ChainManager.setChain (VM236 plugin:copilot:138004:54)

I am able to load the note using Chat mode. But it's not recognizing the active note in long note QA. And eventually I want to set up Vault QA so will need embedding for that.

**Expected behavior**
Long Note QA to recognize active note so I can interact with the content

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary.

![image](https://github.com/user-attachments/assets/aba6f918-661d-423a-badd-8836230aee87)

![image](https://github.com/user-attachments/assets/99283d90-1a5c-43ee-8531-c468823e038e)

![image](https://github.com/user-attachments/assets/f78738f6-11a6-4dcf-8546-1b670bf12124)

**Additional context**

I've tried a million other things and seemingly every possible combination including Open AI and Cohere embedding models as well as nomic using LM studio as an open model but I must be doing something wrong. Any help appreciated.

**Comment by stephen-ondyr** [comment]
Nevermind it seems to be working now. No idea why!

**Comment by logancyang** [comment]
Hmm interesting, something might be wrong and the error seems flaky.
