### ISSUE TITLE
Error indexing vault: API key is not provided

### ISSUE THREAD

**Issue by Jiang-Li** [logancyang/obsidian-copilot#705]
I use LM Studio with Model lmstudio-community/Llama-3.2-3B-Instruct-GGUF, and referenced the setting in #618. The Chat and Long Note QA are okay, but Vault QA cannot apply the indexing. 

**Screenshots**
<img width="398" alt="Screenshot 2024-10-05 at 10 41 21 PM" src="https://github.com/user-attachments/assets/7aec803e-eb35-4802-acc9-f65419eec660">

Could you let me know how to fix it?

**Comment by logancyang** [comment]
hmm, this shouldn't happen. In the meantime, can you try putting a random string in the API key when adding this custom model, let me know if it works.

**Comment by Jiang-Li** [comment]
Thank you, I changed to Ollama and set up the embedding model. It works.
