### ISSUE TITLE
[PLUS] Integrate websearch tool

### ISSUE THREAD

**Issue by suizideFloat** [logancyang/obsidian-copilot#708]
It would be very handy to be able to make web searches by the AI chat and get the model to take that searches as context for their answers.

Something like that is possible in OpenWebUI, where you give the prompt a URL with "#" sign up front and the model requests the website.
As well as omni-engineer (https://github.com/Doriandarko/omni-engineer) that has the /search command feature, which lets you make a search request with duckduckgo and have the result in memory.

Would be nice to maybe make that search via a searxNG instance.

Thank you.

**Comment by logancyang** [comment]
AI agent and tool calling is under development, I will make an announcement soon. Stay tuned!
