### ISSUE TITLE
Integrate Perplexity.ai API

### ISSUE THREAD

**Issue by suizideFloat** [logancyang/obsidian-copilot#709]
Would be handy to have Copilot support Perplexity as a API provider in the settings.

May be helpful with feature request #708 as well, to use perplexity as provider to get the information, then switch back to local model or else.

Thanks for the great project mate.

**Comment by logancyang** [comment]
You can add Perplexity models via Custom Models now, don't forget to enable CORS for it. I probably won't add a separate provider for it for now. I'll have native websearch as a tool for AI agent via Tavily.

**Comment by logancyang** [comment]
Please refer to the doc for how to add perplexity models: https://www.obsidiancopilot.com/en/docs/settings#adding-custom-models
