### ISSUE TITLE
Please add GPT-4o and GPT-4o-mini

### ISSUE THREAD

**Issue by bgrayburn** [logancyang/obsidian-copilot#710]
**Is your feature request related to a problem? Please describe.**
Now that there is the extremely cheap to use GPT-4o-mini I'd love to be able to use this with obsidian copilot

**Additional context**
Because 4o is good at complex event and 4o-mini is so cheap these make ideal models for use with obsidian copilot

**Comment by tom-cd** [comment]
I'm already using GPT-4o and GPT-4o-mini with Copilot. Is your plugin up to date?

**Comment by logancyang** [comment]
You must be on some months old version, please update your plugin.

**Comment by bgrayburn** [comment]
oh wow sorry about that, would have sworn I checked it was update before writing this, but definitely see an update. Thank you for letting me know and writing this super useful plugin!
