### ISSUE TITLE
Privacy Concern: Ensuring My Data Stays Local with Ollama

### ISSUE THREAD

**Issue by kilmarnock** [logancyang/obsidian-copilot#713]
Hi there,

I'm facing an issue regarding my privacy. I use Ollama to host LLMs on my server, but I’ve noticed that **even when my server is down, the Obsidian Copilot continues to function** and still answers questions about my private data quite effectively.

This leads me to believe that **my private data might be leaving my computer**, possibly being sent as part of the context for my questions.

**Is there a way to prevent this?** I want to ensure that Ollama (or nothing else) is handling my data.

Thanks for your help!

**Comment by logancyang** [comment]
> even when my server is down, the Obsidian Copilot continues to function

Using someone's LLM for free, it's the dream 😂

Ok jokes aside, I wonder what configuration you have. Pls turn on debug mode and show the screenshot of your dev console at least as instructed by the issue template.

**Comment by logancyang** [comment]
There's one very quick and easy way. Reset your settings so it wipes out your API keys. There's no way in a million years that you can still use any nonlocal chat model.

**Comment by logancyang** [comment]
Hey @kilmarnock, I'm starting to think you are trolling here. This notice is from Smart Connections. 

If you really would like help on this forum, please 

1. Follow the instructions for starting an issue based on the template.
2. Disable all other plugins except Copilot, turn on debug mode and post screenshots.
