### ISSUE TITLE
How to Sync Local Vector Data Using obsidian-git

### ISSUE THREAD

**Issue by gjhhust** [logancyang/obsidian-copilot#714]
### Description:
Hello,

I am using the Copilot plugin for Obsidian and the `obsidian-git` plugin to synchronize my Obsidian vault across multiple machines. While `obsidian-git` effectively syncs my notes and files, I also need to sync the local vector data (embeddings) stored in the indexedDB.

Could you please provide guidance on how to sync the local vector data between different machines using `obsidian-git`? Specifically, I would like to know:

1. How to export the local vector data to a file format (e.g., JSON).
2. How to import the exported data back into the indexedDB.
3. Any best practices or considerations for ensuring data integrity and security during the sync process.

Thank you for your help!

### Environment:
- **Obsidian Version**: lastest
- **Copilot Plugin Version**: lastest

### Additional Information:
- I am currently using `obsidian-git` to sync my Obsidian vault, but it does not sync the indexedDB data.
- I would like to ensure that my vector data is consistent across multiple machines.

Thank you for your time and assistance!

Best regards

**Comment by logancyang** [comment]
Thanks for your question. The coming release is a migration from pouchdb (that uses indexdb) to Orama. And your index will be a json file in your .obsidian folder that gets synced automatically.

**Comment by logancyang** [comment]
Please refer to the announcement in readme, you can find the index file in `.obsidian/` now
