### ISSUE TITLE
Applying prompts to selected text no longer works

### ISSUE THREAD

**Issue by tmsbn** [logancyang/obsidian-copilot#729]
- [x] Disable all other plugins besides Copilot **(required)**

Copilot version: 2.6.11
Obsidian 1.7.4

**Describe how to reproduce**
To apply a custom prompt to selected text, I usually add a `{}` before the prompt as per the instructions in the ad-hoc custom prompt dialog. For example, one of my custom prompt templates look like this
```
{} 
rewrite text to fix grammer mistakes and typos
```

This used to work as expected before. However, since the last update, the prompt is applied to the whole note instead of just the selected text regardless of whether `{}` is specified. This seems like a regression unless I am mistaken in my understanding of how to apply prompts to selected text.

**Expected behavior**
If the prompt includes `{}`, please apply the prompt only to the selected text

**Comment by Emt-lin** [comment]
@tmsbn It's working fine on my mac.

`note:` If you don't selected any text, this default behavior will selected the active note.

![CleanShot 2024-10-21 at 10 07 08](https://github.com/user-attachments/assets/3b2e98c1-d887-43b8-a061-486e8d1b2387)

**Comment by logancyang** [comment]
I also tried and it's working correctly for me. Are you sure you have the text correctly selected and applied the ad-hoc prompt with the command?

**Comment by tmsbn** [comment]
I did a restart and reloaded the plugin and now I can no longer reproduce the bug. Feel free to close this issue for now, and I will reopen it again if the bug occurs again with more details and logs
