### ISSUE TITLE
Q&A模式，建立索引后对话一直提示Langchain Content_length_exceeed 

### ISSUE THREAD

**Issue by joeseesun** [logancyang/obsidian-copilot#73]
Obsidian Developer Console
plugin:quickadd:18499 Loading QuickAdd
plugin:quickadd:16735 QuickAdd: (LOG) No migrations to run.
plugin:oz-image-plugin:188 Image in Editor Plugin is loaded
plugin:obsidian-pandoc:10084 Loading Pandoc plugin
plugin:dataview:19532 Dataview: version 0.5.56 (requires obsidian 0.13.11)
plugin:table-editor-obsidian:23712 loading markdown-table-editor plugin
plugin:shortcuts-extender:83 e
plugin:obsidian-tasks-plugin:224 loading plugin "tasks"
plugin:search-on-internet:580 loading search-on-internet
plugin:obsidian-day-planner:7214 Loading Day Planner plugin
plugin:obsidian-outliner:3294 Loading obsidian-outliner
plugin:recent-files-obsidian:223 Recent Files: Loading plugin v1.3.6
plugin:recent-files-obsidian:261 Recent Files: maxLength is not set, using default (50)
plugin:hotkeysplus-obsidian:43 Loading Hotkeys++ plugin
plugin:obsidian-local-rest-api:47287 REST API listening on https://127.0.0.1:27124/
plugin:obsidian-local-rest-api:47295 REST API listening on http://127.0.0.1:27123/
plugin:media-extended:28 loading media-extended
plugin:obsidian42-brat:23 loading Obsidian42 - BRAT
plugin:homepage:2 Homepage: Home (method: Replace all open notes, view: Default view, kind: File)
plugin:vantage-obsidian:81 Loading the Vantage plugin.
plugin:text-snippets-obsidian:39 Loading snippets plugin
plugin:obsidian-weread-plugin:2 load weread plugin
plugin:obsidian-weread-plugin:2 --------init cookie------ Array(9)
plugin:obsidian-weread-plugin:2 [weread plugin] setting user vid=> 17000040
plugin:obsidian-weread-plugin:2 [weread plugin] setting user name=> 向阳乔木
plugin:obsidian-hypothesis-plugin:2 loading plugin 2023/6/14 14:34:29
plugin:obsidian-hypothesis-plugin:2 Start syncing...
plugin:obsidian-to-anki-plugin:30969 loading Obsidian_to_Anki...
plugin:obsidian-wordpress:92533 loading obsidian-wordpress plugin
plugin:obsidian-wordpress:80149 Object '2'
plugin:copilot:52453 New chain created:  llm_chain
3plugin:copilot:54064 Set chain: llm_chain
plugin:dataview:12575 Dataview: all 1390 files have been indexed in 0.876s (1390 cached, 0 skipped).
plugin:obsidian-hypothesis-plugin:2 StartAutoSync: this.timeoutIDAutoSync 138 with 2 minutes
plugin:copilot:54113 Creating vector store...
plugin:copilot:8921 Refused to set unsafe header "User-Agent"
setRequestHeader @ plugin:copilot:8921
plugin:copilot:54120 Vector store created successfully.
plugin:copilot:54095 New retrieval qa chain with contextual compression created for document hash:  8579a750b8c5b8f2cc9228cf50b20ecf
plugin:copilot:54101 Set chain: retrieval_qa
plugin:copilot:54064 Set chain: llm_chain
plugin:copilot:54113 Creating vector store...

**Comment by joeseesun** [comment]
![image](https://github.com/logancyang/obsidian-copilot/assets/3236682/7c8837cc-4318-463f-bbb7-a0f9de4500cf)

**Comment by logancyang** [comment]
你的maxTokens设置的是多少？

**Comment by joeseesun** [comment]
果然是这个问题，搞定

**Comment by mevinlei** [comment]
我也遇到了同样的问题，但是我问题表现为，在我已经设置token limit在1000的前提下：1，先提出一个A问题，能够正常回答；2，再提出出一个B问题，提示【Langchain Content_length_exceeed】；3，反复调整都失败；4，返回来重新尝试提问一次A问题，还是能正常回答。真的很让人困惑啊

**Comment by logancyang** [comment]
> 我也遇到了同样的问题，但是我问题表现为，在我已经设置token limit在1000的前提下：1，先提出一个A问题，能够正常回答；2，再提出出一个B问题，提示【Langchain Content_length_exceeed】；3，反复调整都失败；4，返回来重新尝试提问一次A问题，还是能正常回答。真的很让人困惑啊

@mevinlei 首先看下max tokens的定义: The maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the chat completion. https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens

如果你的prompt很长，你的max tokens就需要降低才能不超过context window。

不过没有关系，现在16K的window已经所有人可用了。今天release。

**Comment by mevinlei** [comment]
> > 我也遇到了同样的问题，但是我问题表现为，在我已经设置token limit在1000的前提下：1，先提出一个A问题，能够正常回答；2，再提出出一个B问题，提示【Langchain Content_length_exceeed】；3，反复调整都失败；4，返回来重新尝试提问一次A问题，还是能正常回答。真的很让人困惑啊
> 
> @mevinlei 首先看下max tokens的定义: The maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the chat completion. https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens
> 
> 如果你的prompt很长，你的max tokens就需要降低才能不超过context window。
> 
> 不过没有关系，现在16K的window已经所有人可用了。今天release。

哈哈，是的，刚刚更新了，可以用得很顺利了。
原谅作为电脑小白的不求甚解，确实还是没看懂max tokens的定义😃😃😃
