### ISSUE TITLE
The button for contextual conversations with copilot is missing..

### ISSUE THREAD

**Issue by henryperkins** [logancyang/obsidian-copilot#734]
I'm constantly using the send note feature! There might be other options, but this one is my absolute favorite.... How do I use the tool for conversing over a note in the meantime?

**Comment by logancyang** [comment]
Please refer to https://github.com/logancyang/obsidian-copilot/discussions/733#discussioncomment-11008202 in discussion.

You can use custom prompt templating to send notes. Let me know if it can't address your use case while the button could.
