### ISSUE TITLE
[FR] List all the notes with embedded error

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#737]
**Is your feature request related to a problem? Please describe.**

In the new version of plugin, embedded errors have become common even using embedding model with large length. 

**Describe the solution you'd like**

So, keeping the notes with embedded errors in a list is convenient for users to review.

**Comment by logancyang** [comment]
Please show your dev console as the issue template suggests, otherwise it will be treated as a question and the issue will be closed.

Feel free to ask questions in Discord.
