### ISSUE TITLE
[FR] Token count command

### ISSUE THREAD

**Issue by ALE-ARME** [logancyang/obsidian-copilot#740]
**Is your feature request related to a problem? Please describe.**
The count is on the entire vault even if I have folder exceptions

**Describe the solution you'd like**
Count the token only for the folders that are not in the blacklist

**Additional context**
It's pointless to have the count for the while vault if I don't intend to do the embedding for all the notes

**Comment by logancyang** [comment]
@Emt-lin do you want to take this one on?
