### ISSUE TITLE
Files with long contexts cannot be embedded.

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#741]
After reviewing the files  that failled to be embedded, I found most of them have long contexts. I wonder whether the content of files will not be devided to be embedded now.

**Comment by logancyang** [comment]
Please follow the issue template to provide necessary info such as version of your plugin and dev console.

Right now you can directly verify what's embedded with the index file in v2.7.0.

If you are more comfortable in Chinese we can chat in Discord inside the Chinese channel. You are in our Discord right?
