### ISSUE TITLE
Keep getting "Error initializing Orama database: Error: Connection error"

### ISSUE THREAD

**Issue by rusi** [logancyang/obsidian-copilot#745]
- [x] Disable all other plugins besides Copilot **(required)**
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.0

(Bug report without the above will be closed)

**Describe how to reproduce**
After opening Obsidian, copilot is unable to initialize the Orama DB (see screenshot)

**Expected behavior**
Obsidian opens and Copilot is able to initialize the Orama DB.

**Screenshots**

 <img width="1505" alt="image" src="https://github.com/user-attachments/assets/8233cfe8-8628-4b2f-abbf-b3b96e12100a">

**Additional context**
Using Obsidian v1.7.4. I am also using Obsidian sync.
For some reason I do not get this message on my other machine and Copilot is able to create the copilot-index file.
I tried copying the file from my other instance, and Copilot is able to "initialize" and load the file, however, it is not able to use it (gives other errors).

**Comment by logancyang** [comment]
@rusi seems you are using an OpenAI embedding model? Do you have OpenAI API key set? I sometimes see connection errors caused by network issues but not reproducible. Yours seems consistent?

**Comment by rusi** [comment]
@logancyang, I am using a local embedding model via LM Studio and I have set a dummy API key. This is working fine on one of my machines (running the same versions but the vault is in a different folder). However, on my other machine (where the vault is my home folder, under "/Users/rusi/Notes"), I am always getting this connection error. I cannot understand if this is related to permissions issue or something else. If I copy the index file from my other machine, it seems that the Orama DB gets initialized, but then I get other "connection" errors when copilot tries to use it. 
And yes, the issue is persistent. 
Btw, I tried the same setup in a different vault (still in my home folder), and that works fine. I am wondering if there's some permissions issue, or something related to sync...

**Comment by logancyang** [comment]
> I tried the same setup in a different vault (still in my home folder), and that works fine

This is where I'm lost. What's the variable here between this vault and the faulty vault?

**Comment by rusi** [comment]
That's exactly what I cannot figure out... 
I added some log messages to see where it's failing, and this is the trace from the working instance:
![image](https://github.com/user-attachments/assets/e4675123-6fc4-4adc-8d9f-e8022f5bfba4)
and the following is from the failing instance:
![image](https://github.com/user-attachments/assets/353530f1-5fcb-4996-8047-29449901f826)

It seems that the call to `const sampleEmbedding = await embeddingInstance.embedQuery(sampleText);` is failing in the `getVectorLength` function. I will continue exploring...

**Comment by rusi** [comment]
ok... this is stupid, but it turned out that I had loaded two embedding models with the same "API identifier" in LM Studio, which was causing the timeout... After unloading one of the models everything works fine.
So the difference was in the models I had loaded in LM Studio (which was different on the two machines).
Thanks for looking into this.

**Comment by logancyang** [comment]
Glad you figured it out!
