### ISSUE TITLE
Long articles can't be embedded

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#748]
- [x] Disable all other plugins besides Copilot **(required)**
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.0

(Bug report without the above will be closed)

**Describe how to reproduce**

Copy the long article in the log and embed it using Ollama.

**Expected behavior**

 Divide the article into several pieces and then embed these pieces.

**Screenshots**

[obsidian.md-1729952405628.log](https://github.com/user-attachments/files/17530922/obsidian.md-1729952405628.log)

**Comment by logancyang** [comment]
I see your error is `input length exceeds maximum context length`, so the embedding model you are using doesn't have enough context length. **My suggestion is to use another embedding model that has longer context**.

The current chunking logic has a constant chunk size. I've thought of making chunk size a setting for user to set, but the implication is that every time the user change the chunk size, the entire vault must be re-indexed. That is expensive and time-consuming for people who use paid embedding models. And my general preference is to avoid complicating the settings more, because the more you can tune the more expert knowledge it requires the user to have, and the harder for me to debug because I don't have the full picture how the user tweaks their settings.

**Comment by wwjCMP** [comment]
> I see your error is `input length exceeds maximum context length`, so the embedding model you are using doesn't have enough context length. **My suggestion is to use another embedding model that has longer context**.
> 
> The current chunking logic has a constant chunk size. I've thought of making chunk size a setting for user to set, but the implication is that every time the user change the chunk size, the entire vault must be re-indexed. That is expensive and time-consuming for people who use paid embedding models. And my general preference is to avoid complicating the settings more, because the more you can tune the more expert knowledge it requires the user to have, and the harder for me to debug because I don't have the full picture how the user tweaks their settings.

What is the current chunk size? As shown in the log, the article attempts to be embedded as a whole. So, the context length of my embedding model must be larger than the lengths of all my articles?

**Comment by logancyang** [comment]
> > I see your error is `input length exceeds maximum context length`, so the embedding model you are using doesn't have enough context length. **My suggestion is to use another embedding model that has longer context**.
> > The current chunking logic has a constant chunk size. I've thought of making chunk size a setting for user to set, but the implication is that every time the user change the chunk size, the entire vault must be re-indexed. That is expensive and time-consuming for people who use paid embedding models. And my general preference is to avoid complicating the settings more, because the more you can tune the more expert knowledge it requires the user to have, and the harder for me to debug because I don't have the full picture how the user tweaks their settings.
> 
> What is the current chunk size? As shown in the log, the article attempts to be embedded as a whole. So, the context length of my embedding model must be larger than the lengths of all my articles?

The chunking size right now is 4000 chars, that's around 1000 tokens per chunk if we have 4 chars per token on avg. A lot of the older embedding models have 512-token context window. Most better embedding models right now can handle much more than 1000 tokens.

**Comment by wwjCMP** [comment]
> > > I see your error is `input length exceeds maximum context length`, so the embedding model you are using doesn't have enough context length. **My suggestion is to use another embedding model that has longer context**.
> > > The current chunking logic has a constant chunk size. I've thought of making chunk size a setting for user to set, but the implication is that every time the user change the chunk size, the entire vault must be re-indexed. That is expensive and time-consuming for people who use paid embedding models. And my general preference is to avoid complicating the settings more, because the more you can tune the more expert knowledge it requires the user to have, and the harder for me to debug because I don't have the full picture how the user tweaks their settings.
> > 
> > 
> > What is the current chunk size? As shown in the log, the article attempts to be embedded as a whole. So, the context length of my embedding model must be larger than the lengths of all my articles?
> 
> The chunking size right now is 4000 chars, that's around 1000 tokens per chunk if we have 4 chars per token on avg. A lot of the older embedding models have 512-token context window. Most better embedding models right now can handle much more than 1000 tokens.

However, the context length of my embedding model is 8192, which is larger than 1000 tokens and even the length of this article. Now, the question is what causes this error?

**Comment by logancyang** [comment]
@wwjCMP I don't have access to your embedding model so I can't test, I can only make educated guesses. 

The code is open source. Feel free to dive in deeper to get more signals.

**Comment by wwjCMP** [comment]
https://ollama.com/library/bge-m3:latest
I use the embedding model offered by Ollama.
Ok, I will test it myself.
