### ISSUE TITLE
openrouter ai :  400 ministral-3b is not a valid model ID

### ISSUE THREAD

**Issue by mattseason** [logancyang/obsidian-copilot#755]
hi, i 'm having trouble getting openrouter.ai to work.

I've set my openrouter ai api key in API Settings.

Then i add a custom model:
name of the model: ministral-3b
provider: openrouterai
base URL: (i've tried blank, or mistralai/ministral-3b or https://openrouter.ai/mistralai/ministral-3b )
API key: (i've tried blank or with my openrouter ai API key)

thanks for tour help

**Comment by logancyang** [comment]
Please make sure you use the correct model name
<img width="825" alt="SCR-20241028-nrbd" src="https://github.com/user-attachments/assets/891b954c-66e8-48b4-8b3d-885584fd5e99">

Blank base URL is fine. Works for me.

**Comment by mattseason** [comment]
It works, thanks for your help.
