### ISSUE TITLE
Also exclude files that are excluded by Obsidian's settings

### ISSUE THREAD

**Issue by TroySigX** [logancyang/obsidian-copilot#756]
**Is your feature request related to a problem? Please describe.**
When I want to exclude a file from being indexed, I have to exclude it twice in Obsidian setting tab (Files and links tab) and in Copilot.

**Describe the solution you'd like**
I'd like Copilot to exclude all the files that are already excluded by Obsidian settings.

**Describe alternatives you've considered**
Make a button to let users decide whether to also exclude the files excluded by Obsidian settings

**Additional context**
![image](https://github.com/user-attachments/assets/6eb8c85c-32e2-4ec6-b50b-1d9f31866b33)
![image](https://github.com/user-attachments/assets/063ff5a7-6b81-4c41-b8eb-9b868db3465a)

**Comment by logancyang** [comment]
Ok we can get the user setting with `app.vault.getConfig('userIgnoreFilters')` (not documented in Obsidian API but I got this answer from Obsidian's discord)

**Comment by Emt-lin** [comment]
@TroySigX If you want to prevent files to be indexed, you only set exclude files option in Copilot setting. Why you need to set it in the Obsidian setting.

**Comment by TroySigX** [comment]
Because I also don't want those files to appear in Obsidian search as well. Those notes are mainly drafts.

**Comment by logancyang** [comment]
@Emt-lin It may be better UX to inherit from the Obsidian "master exclusion" setting, since the user explicitly excluded these files from Obsidian overall, all the plugins should operate within the "master setting". If we inherit it, the user doesn't need to repeat themselves in Copilot settings.

**Comment by Emt-lin** [comment]
@logancyang pls assign me
