### ISSUE TITLE
Embedding error: please check your embedding model context length

### ISSUE THREAD

**Issue by jarodise** [logancyang/obsidian-copilot#758]
I've tried switching between several different models, this error persists, please enlighten me how I can solve this issue, thanks! 

The full error message goes :

Embedding error: please check your embedding model context length, and consider switching to a model with a larger context length: input length exceeds maximum context length

- [ ] Disable all other plugins besides Copilot **(required)**
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version:

(Bug report without the above will be closed)

**Describe how to reproduce**
A clear and concise description of what the bug is. Clear steps to reproduce the behavior

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary.

**Additional context**

**Comment by Emt-lin** [comment]
@jarodise What embedding Model are you using? 

if you use local embedding Model, you can read this [guide](https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md).

**Comment by bnabled** [comment]
I'm having the same issue, both with nomic-embed-text as well as with mxbai-embed-large. This didn't happen in an earlier version of Copilot.

**Comment by bibendi** [comment]
I'm experiencing this issue as well. Tried nomic and mxbai

**Comment by logancyang** [comment]
I can reproduce this. Filed a bug in langchainjs https://github.com/langchain-ai/langchainjs/issues/7148 and https://github.com/langchain-ai/langchainjs/issues/7161

Related: #769

**Comment by logancyang** [comment]
Closing this one now as I applied truncation in overflowing cases so you won't see this error again. But Ollama client in LangchainJS still needs to be fixed.
