### ISSUE TITLE
Support third-party API Key and API Host

### ISSUE THREAD

**Issue by alfoil** [logancyang/obsidian-copilot#76]
Support third-party API Key and API Host, like Forward Key from https://api2d.com/

**Comment by logancyang** [comment]
This is currently not possible because this plugin is using LangchainJS for a lot of functionalities, and LangchainJS needs to support them first.

I do have other ways to interact with chat models before I integrated with langchain. But that would mean lost of much functionality on the QA side. 

Will first add local models and circle back to this ask.

**Comment by i-iooi-i** [comment]
Support third-party API Key and API Host，really need this~ 🤤

**Comment by logancyang** [comment]
@i-iooi-i @alfoil  Just to understand it better, is this a China-specific thing because OpenAI direct access is blocked in China? Not sure why https://api2d.com/ was created.

**Comment by alfoil** [comment]
> @i-iooi-i @alfoil Just to understand it better, is this a China-specific thing because OpenAI direct access is blocked in China? Not sure why https://api2d.com/ was created.

Yes. That's what I mean.

**Comment by i-iooi-i** [comment]
> @i-iooi-i @alfoil Just to understand it better, is this a China-specific thing because OpenAI direct access is blocked in China? Not sure why https://api2d.com/ was created.

Yes, OpenAi has denied access to certain countries and can only use ChatGPT accessible through third-party API hosts. 😂😂😂

**Comment by springtian1982** [comment]
I tried to replace the endpoint base url in main.js with my own one. And it **WORKS.**

**Comment by logancyang** [comment]
> I replace the endpoint base url in main.js with my own one. And it **WORKS.**
> 
> @logancyang Would you please make it possible to have new parameter for setting the Endpoint URL? Thank you for this great plugin!

Wow nice!! Can you show me what you changed to make it work in more detail?

**Comment by Chandler-Lu** [comment]
In fact, the third-party api is the reverse proxy of the official api, and the interfaces are all the same. Replace the url of the official website api and it works. In other words, just need to make `BASE_PATH` customizable in GUI.

Original: `exports.BASE_PATH = "https://api.openai.com/v1".replace(/\/+$/, "");`
New: `exports.BASE_PATH = "https://api.example.com/v1".replace(/\/+$/, "");`

**Comment by springtian1982** [comment]
> In fact, the third-party api is the reverse proxy of the official api, and the interfaces are all the same. Replace the url of the official api and it works. In other words, just need to make `BASE_PATH` customizable in GUI.
> 
> Original: `exports.BASE_PATH = "https://api.openai.com/v1".replace(/\/+$/, "");`
> New: `exports.BASE_PATH = "https://api.example.com/v1".replace(/\/+$/, "");`

Right.

**Comment by springtian1982** [comment]
> > I replace the endpoint base url in main.js with my own one. And it **WORKS.**
> > @logancyang Would you please make it possible to have new parameter for setting the Endpoint URL? Thank you for this great plugin!
> 
> Wow nice!! Can you show me what you changed to make it work in more detail?

@logancyang 
As @Chandler-Lu said, just making `BASE_PATH` customizable in GUI will work.
And thanks again for creating and improving this plugin! 👍

**Comment by logancyang** [comment]
> > > I replace the endpoint base url in main.js with my own one. And it **WORKS.**
> > > @logancyang Would you please make it possible to have new parameter for setting the Endpoint URL? Thank you for this great plugin!
> > 
> > 
> > Wow nice!! Can you show me what you changed to make it work in more detail?
> 
> @logancyang As @Chandler-Lu said, just making `BASE_PATH` customizable in GUI will work. And thanks again for creating and improving this plugin! 👍

@springtian1982 Just to understand better, what API key is being used in this case? Is it the key to the 3rd party API or the official API? A concrete example of the exact 3rd party API and your setting would be helpful. 

Since the main.js you modified is a compiled version of my code and contains stuff from LangchainJS, to actually change the base path of the OpenAI ChatModel, I probably need to 

1. Create a wrapper class for LangchainJS's ChatOpenAI class to enable setting a custom OpenAI base path
2. Enable setting this base path in the plugin settings
3. Have a separate model in the model dropdown with a name like "Custom OpenAI" to let the user call this 3rd party proxy of OpenAI.

This could actually also work with another initiative I have - the local version of OpenAI models enabled by https://github.com/go-skynet/LocalAI 🧐

**Comment by logancyang** [comment]
Published v2.3.6 with the new setting: 

<img width="792" alt="Screenshot 2023-07-19 at 6 13 24 PM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/7a7857d4-52e7-4c38-86d7-c304867ec2ee">

I don't have access to your 3rd party APIs, could you test it and let me know if it works?

**Comment by Chandler-Lu** [comment]
Great, it works! Thank you for your effort. And if you need further test, I can provide you with a 3rd party key.

**Comment by springtian1982** [comment]
🥂 Thanks everyone to make this happen.

**Comment by i-iooi-i** [comment]
![Snipaste_2023-07-20_11-29-50](https://github.com/logancyang/obsidian-copilot/assets/1827701/7a263466-ca2a-4e15-b9f3-f2f892c298d5)
It's starting to work again, thank you. 🍻

**Comment by Chandler-Lu** [comment]
> ![Snipaste_2023-07-20_11-29-50](https://user-images.githubusercontent.com/1827701/254763338-7a263466-ca2a-4e15-b9f3-f2f892c298d5.png) It's starting to work again, thank you. 🍻

方便问一下这是什么主题嘛，感觉蛮好看的，谢谢

**Comment by i-iooi-i** [comment]
> > ![Snipaste_2023-07-20_11-29-50](https://user-images.githubusercontent.com/1827701/254763338-7a263466-ca2a-4e15-b9f3-f2f892c298d5.png) It's starting to work again, thank you. 🍻
> 
> 方便问一下这是什么主题嘛，感觉蛮好看的，谢谢

我用的是这个主题：https://github.com/Bluemoondragon07/obsidian-big-and-bold
主题商店里搜索： Big & Bold
一直很喜欢√ 推荐~

**Comment by logancyang** [comment]
Closing this one for now.
