### ISSUE TITLE
[Bug] Alibaba Qwen-Max And KiMi Model Connection error

### ISSUE THREAD

**Issue by PennHui666** [logancyang/obsidian-copilot#783]
- [√] Disable all other plugins besides Copilot **(required)**
- [√] Screenshot of note + Copilot chat pane + dev console added **(required)**

**Copilot version**: 2.7.0

**issue**
The following error occurred while attempting to have a conversation with the third-party model `qwen-max` that has CORS enabled.

**Screenshots**
![Snipaste_2024-11-06_08-03-00](https://github.com/user-attachments/assets/653c1dfa-fa45-42d2-9c5a-9165f1bed556)
![Snipaste_2024-11-06_08-00-24](https://github.com/user-attachments/assets/8fb369bb-4233-4cf6-8da1-a1e7a72db3e1)

**Additional context**
base_url：`https://dashscope.aliyuncs.com/compatible-mode/v1`

**Comment by logancyang** [comment]
Is their API openai compatible? Have you tried `curl` if so please share it too.

**Comment by PennHui666** [comment]
> Is their API openai compatible? Have you tried `curl` if so please share it too.

@logancyang 
This API is compatible with the OpenAI format and I have tested it with another plugin called `Text Generator`, and it can respond normally. In addition, I also tested Kimi's API in Obsidian Copilot and the same problem occurred. Finally, I found that the console report `Ensure CORS response header values are valid`, and I am not sure if it is related to this issue.

**Comment by logancyang** [comment]
@PennHui666 I thought you mentioned you checked CORS in your setting? Are you still seeing CORS error with it checked?

I don't have the API access to these providers so I can't test. Anyone who has please share your experience.

**Comment by PennHui666** [comment]
> I thought you mentioned you checked CORS in your setting? Are you still seeing CORS error with it checked?
> 
> I don't have the API access to these providers so I can't test. Anyone who has please share your experience.

@logancyang 
I am certain and have checked that even after enabling CORS, I can still see the error shown in the picture. In addition, in `v2.5.5`, after filling in the URL of the **kimi** API into the `OpenAI proxy basic URL` settings, I was able to connect to the conversation normally,but **qwen-max** still did not work.

**Comment by Emt-lin** [comment]
@PennHui666 @logancyang In v2.7.1, it's working fine.

![Obsidian 2024-11-06 10 39 46](https://github.com/user-attachments/assets/d861fbbb-596e-4d4a-8ec0-ae2fd1faaf6b)

![CleanShot 2024-11-06 at 10 44 46](https://github.com/user-attachments/assets/cd64991b-1598-4100-ba0a-ff13eeccb0a3)


![Google Chrome 2024-11-06 10 39 08|100](https://github.com/user-attachments/assets/b03b4d56-74d0-426d-92c7-00820ff3fe8e)

**Comment by PennHui666** [comment]
@Emt-lin Thanks for the reminder, after upgrading to v2.7.1, it is really ready to use.

**Comment by PennHui666** [comment]
@Emt-lin I tested it and found that QWEN worked, but Kimi didn't. What about you? Friend, do you use Kimi's Api?

**Comment by PennHui666** [comment]
![image](https://github.com/user-attachments/assets/ec5f0fae-cfbe-42a0-ab44-e7e54a920c2b)
To solve this problem, upgrade the copilot plugin version to `v2.7.1`, Fill in the correct model name and base _ url when adding a third-party provider. particular attention to the kimi's model need to open CORS.

解决此问题，请将 copilot 插件版本升级到 `v2.7.1`，添加第三方提供商时填写正确的模型名称和 base _ url。特别注意 Kimi 的模型需要打开 CORS。
