### ISSUE TITLE
Unexpected error indexing vault to vector store: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by IHB4L** [logancyang/obsidian-copilot#787]
I am using text-embedding-3-large within a 3rd party openai format provider, the chatbot works with this provider.
![image](https://github.com/user-attachments/assets/812c0559-5d9a-475b-ba53-3fdb98816c41)
and also this error which i don't know if it affects anything:
![image](https://github.com/user-attachments/assets/73d93ab4-7533-4bbb-aecb-ddd1d92b0f5e)

**Comment by logancyang** [comment]
Need more info on how to repro.

**Comment by logancyang** [comment]
Please try the new Verify Connection button (v2.7.10) before you add your model.
