### ISSUE TITLE
[Help] Indexing inclusions

### ISSUE THREAD

**Issue by ALE-ARME** [logancyang/obsidian-copilot#788]
I have 2 main folders.
In each folder I have folders with the subject name.
Each of these folders contains a folder in the name format "subject NOTES".
I want to index only the files under this type of folders.
I thought that `*/*/*NOTES` would work, but it actually starts to index the entire vault

**Comment by logancyang** [comment]
This kind of pattern is not currently supported in inclusion, exclusion, or custom prompting right now. The setting description shows all supported patterns.
