### ISSUE TITLE
Feature Request: Configure note save location

### ISSUE THREAD

**Issue by samtowers** [logancyang/obsidian-copilot#79]
Currently "Save as Note" stores notes to the root of your obsidian vault.

For myself I'd like to save them to my media/attachments folder, or some other place so saved chats are grouped together.

Cheers!

**Comment by logancyang** [comment]
Thanks for the suggestion, yes that would be more convenient. Adding this to the roadmap. In the meantime, renaming and moving it will need to be done manually.

**Comment by writtenfool** [comment]
If a folder property could be assigned, we can automate the running of a template when a chat is saved to this folder, may even make issue #98 moot.

**Comment by logancyang** [comment]
Added this setting in v2.4.3

**Comment by writtenfool** [comment]
Awesome. Many thank yous!
