### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by tensorcopy** [logancyang/obsidian-copilot#8]
Great plugin! Just noticed that this plugin is not supported in mobile app. Is there a plan to support it? Thanks!

**Comment by logancyang** [comment]
@np-22 Thank you for the suggestion! Will need to do more research and testing to see what the best mobile experience looks like, but mobile support is definitely in the next steps! Please stay tuned!

**Comment by Ryonez** [comment]
Also going to leave my interest for this here.

**Comment by logancyang** [comment]
Please refer to #532 to follow along. Closing this as duplicate.
