### ISSUE TITLE
Default model: Azure is not being respected

### ISSUE THREAD

**Issue by logancyang** [logancyang/obsidian-copilot#80]
As reported in https://github.com/logancyang/obsidian-copilot/issues/68, need to find out why

**Comment by logancyang** [comment]
@cl1107 Pushed v2.3.2, now default model should be respected. Please reopen if it's still not working after updating.

**Comment by cl1107** [comment]
> @cl1107 Pushed v2.3.2, now default model should be respected. Please reopen if it's still not working after updating.

it works now
