### ISSUE TITLE
Suggested prompt not responsive

### ISSUE THREAD

**Issue by Evantix** [logancyang/obsidian-copilot#803]
- [x] Disable all other plugins besides Copilot **(required)**

Copilot version: 2.7.1

(Bug report without the above will be closed)

**Describe how to reproduce**
A clear and concise description of what the bug is. Clear steps to reproduce the behavior
Change the size of the sidebar.

**Expected behavior**
The suggested prompt should be responsive.

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary.
![image](https://github.com/user-attachments/assets/05a51b58-a3d6-42d7-b4c0-c6b742e3934e)

**Additional context**
N/A

**Comment by logancyang** [comment]
@Evantix Thanks for the bug report! The fix is merged and will be resolved in the next release.

**Comment by Evantix** [comment]
@logancyang Perfect! Thanks for the quick fix! If I can suggest, it would be helpful to have the option to replace the suggested prompts with ones we frequently use. I personally love the {activenote} function and would like to predifine full prompt and have this in one click away from using.

**Comment by logancyang** [comment]
@Evantix Not sure if you know that you can define custom prompts and bring them up just by `/` in the chat, and the list is sorted by recency.

But yeah I think frequently used user custom prompts can be added to "Suggested Prompts". cc @zeroliu

**Comment by Evantix** [comment]
@logancyang Yes, I'm aware of option / prompt, but "suggested prompts" are much faster, especially since I have hundreds saved for different use cases, but I use about 5 almost every day.

Just a suggestion, if it can't be done in future updates I was thinking about changing the text in the plugin files already :)

**Comment by ilvetz** [comment]
Also, it would be useful an option to disable suggested prompts.

**Comment by logancyang** [comment]
@ilvetz could you share why? It only shows when the chat is empty, I thought it wasn't introducing a bad experience.

**Comment by ilvetz** [comment]
@logancyang Adding an option to hide suggested prompts can reduce information overload and distractions, decreasing visual clutter. It facilitates inclusivity and allows for more effective personalization of the user experience.

**Comment by logancyang** [comment]
> @logancyang Adding an option to hide suggested prompts can reduce information overload and distractions, decreasing visual clutter. It facilitates inclusivity and allows for more effective personalization of the user experience.

cc @zeroliu 

Closing this one because responsiveness is fixed in 2.7.2.

**Comment by Joolyan** [comment]
> @ilvetz could you share why? It only shows when the chat is empty, I thought it wasn't introducing a bad experience.

"bad experience" - Unfortunately for some users (including myself) it's not a good experience. If 'suggested prompts' can't be hidden in settings, may be they could be hidden using custom CSS?

**Comment by Joolyan** [comment]
@zeroliu Thank you!
