### ISSUE TITLE
[FR] Quick switch for System prompts 

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#814]
**Is your feature request related to a problem? Please describe.**

The format and style of the response are influenced by the system prompts, and different tasks generally require different system prompts. This is especially noticeable when advanced prompts are needed. Currently, system prompts only serve a general purpose, and the plugin needs to be reloaded every time they are changed.

**Describe the solution you'd like**

Allow users to keep multiple sets of system prompts and switch them at any time in the conversation interface. If interface simplicity needs to be maintained, it can be triggered to switch the interface with special symbols, similar to custom prompts.

**Comment by logancyang** [comment]
This will be addressed by #459. Closing as dupe.
