### ISSUE TITLE
Gemini experimental model not working

### ISSUE THREAD

**Issue by this-is-sebs** [logancyang/obsidian-copilot#819]
<img width="913" alt="image" src="https://github.com/user-attachments/assets/9212bcaf-692d-41c3-a8cb-27d872d3d1ca">

Copilot version: 2.7.1

(Bug report without the above will be closed)

**Describe how to reproduce**
The Gemini experimental model (gemini-exp-1114) was added via the settings in obsidian copilot. Google API key is working. Error message is shown in the photo attached above. 

**Expected behavior**
Anticipating a message back from the model. Except received an API call error. 

**Screenshots**
N/A only screenshot is already shown above.

**Additional context**
N/A

**Comment by logancyang** [comment]
It's working for me

<img width="703" alt="SCR-20241115-lnxm" src="https://github.com/user-attachments/assets/5114c25b-07ca-4ac7-b13c-3f5c87d03a6b">
<img width="610" alt="SCR-20241115-lnua" src="https://github.com/user-attachments/assets/f581c027-f8c1-43e2-bf6d-bf19f64f6133">

**Comment by this-is-sebs** [comment]
Yes, this thread can be closed. I believe they just coded in support of the model for the API.
