### ISSUE TITLE
Obsidian on Android crashes on plugin startup when loading large index file

### ISSUE THREAD

**Issue by jack5github** [logancyang/obsidian-copilot#822]
- [x] Disable all other plugins besides Copilot **(required)**
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**
(Screenshot of index file information provided, please instruct on how to get Obsidian Android logs or any other needed screenshots if required)

Copilot version: 2.7.2
Obsidian Android version: 1.7.6
Android version: 14

(Bug report without the above will be closed)

**Describe how to reproduce**
Obsidian on Android crashes when attempting to load Copilot plugin with a 70MB index file.

**Expected behavior**
The app should open without issues.

**Screenshots**
![image](https://github.com/user-attachments/assets/b37d5741-3017-4ce3-8cbe-b41c6882554c)

**Additional context**
If it is not possible to prevent this bug from occurring due to a potential memory overflow, could there be a setting so that the index file is not automatically loaded?

**Comment by logancyang** [comment]
#825 will set this setting to true by default

**Comment by logancyang** [comment]
Now the setting is default to disable index on mobile, and there's an inclusion filter to avoid large index. Closing this one for now.
