### ISSUE TITLE
Cache for Anthopic

### ISSUE THREAD

**Issue by calimbrasti94** [logancyang/obsidian-copilot#827]
I'm writing here because I couldn't find anything about it. 

Regarding Anthropic, is caching provided or not ? and if yes, has it already been implemented or still has to be ? Thank you very much ! And TOP plugin !!!

**Comment by logancyang** [comment]
Prompt caching will be added for Copilot Plus!

**Comment by logancyang** [comment]
@calimbrasti94 There will be a one-time purchase plan called "believer". The details will be up on the website at launch, stay tuned!

**Comment by logancyang** [comment]
Dupe #868
