### ISSUE TITLE
Adding Custom Model (o1-mini) error: Error: Model request failed: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pboiii** [logancyang/obsidian-copilot#828]
Receive error when trying to add o1-mini custom model:
`Error: Model request failed: Maximum call stack size exceeded`

![Image 11-17-24 at 12 20 PM](https://github.com/user-attachments/assets/54fbc0e3-3e96-4205-ae23-2527ff7f9fb2)

**Comment by logancyang** [comment]
Ok I see the issue, `o1-preview` and `o1-mini` do not support streaming at the moment.

One way to modify is to add a field `stream: bool` to `CustomModel`, default to true but let the user decide when filling the form.

Might be related to the part you are changing @Emt-lin.

**Comment by TheBigFudge** [comment]
Hey @pboiii, @logancyang,

I now have access to o1-preview and o1-mini as well. Could you help clarify the correct way to integrate these models into Obsidian Copilot?

Should I go with @logancyang’s suggestion of adding a stream: bool field to CustomModel (defaulting to true)? Can you explain this any further? Or is there a preferred alternative that has already been tested?

Thanks in advance! 🙌
