### ISSUE TITLE
Scroll chat window as response is generating

### ISSUE THREAD

**Issue by myeewyee** [logancyang/obsidian-copilot#829]
Issue: Chat window position stays fixed while the response is generating below the screen. Then once the response has competely generated, it scrolls to the bottom.

Solution: Would be better if it scrolls as it is generating, keeping the most recently generated line on screen, as chatGPT does.

**Comment by logancyang** [comment]
It used to do that but I decided not to do that anymore. It's constantly shifting and makes it very hard to select things as it generates.
