### ISSUE TITLE
In vault QA, copilot cannot get the current date, making calculations/retrievals wrong.

### ISSUE THREAD

**Issue by lstep** [logancyang/obsidian-copilot#830]
In vault QA, copilot cannot get the current date, making calculations/retrievals wrong.

![image](https://github.com/user-attachments/assets/31546e9b-9c31-4957-b70a-fe68b2ee9820)

**Comment by logancyang** [comment]
Current time is a tool in Copilot Plus. It's not available in Vault QA.
