### ISSUE TITLE
officially support o1-prevew and o1-mini model

### ISSUE THREAD

**Issue by jzhao62** [logancyang/obsidian-copilot#833]
**Is your feature request related to a problem? Please describe.**
the o1 series model are better at reasoning and can potentially increase user experience in the vault QA session

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by logancyang** [comment]
Dupe #828. The solution is to disable streaming for these two -> have `stream: true/false` on every CustomModel interface and let the user choose.
