### ISSUE TITLE
Support for Longer documents

### ISSUE THREAD

**Issue by matthew-boyens** [logancyang/obsidian-copilot#84]
Hey @logancyang love the plugin 

QA is working great for short notes however long notes are returning "not enough context" .

![image](https://github.com/logancyang/obsidian-copilot/assets/48612311/7cca71a9-427b-4a8f-9bb3-baa9ff35a30f)

Is there a way around this? 

Regardless if it's the 16k model vs GPT-4 it seems the context length (26k characters, ~6300 tokens) is the same. Same if I increase the token count (from 1000 to 8000 which is the current max)

I've attached a long file which hopefully helps in investigation
[384  Matthew McConaughey   Freedom Truth Family Hardship and Love.md](https://github.com/logancyang/obsidian-copilot/files/11780356/384.Matthew.McConaughey.Freedom.Truth.Family.Hardship.and.Love.md)

**Comment by logancyang** [comment]
Hi @matthew-boyens , I should have added this one into the Note or FAQ section of the readme. QA mode is actually for specific questions, how it works is that it turns the query into an embedding, use that embedding to find the most relevant embedding from the document side, and then form an answer. For summarization, it won't work. You can use the "Summarize selection" command with the 16k model, it's the easiest way.

Here's the tweet where I also mentioned this: https://twitter.com/logancyang/status/1669476208604766210

For more tips, don't forget to subscribe to my youtube channel and follow my twitter account. I will post release updates, tips and tricks regularly.

**Comment by matthew-boyens** [comment]
Thanks for the prompt reply @logancyang! 

My pleasure, it's a great plugin! 

That makes lots of sense, I'll use that instead going forward :)

When it comes to max length of a document for QA, or will it just work with any arbitrary length?

**Comment by logancyang** [comment]
> When it comes to max length of a document for QA, or will it just work with any arbitrary length via the vector store?

It should work with any arbitrary length via the vector store. For super long notes it may take a while to do the indexing, if you don't see the "Vector store created successfully" notice pop up, there's a chance it may have failed. In that case, just open the console with cmd (or ctrl) + alt + i, check if there's any error. If it's 429 it means it hits some kind of rate limiting from the embedding API, just try again using the Rebuild Index button. If that consistently fails, please open an issue here and I can take a look!

**Comment by matthew-boyens** [comment]
Ok awesome, thanks so much for your support! Excited to see what you will do with the plugin next!
