### ISSUE TITLE
[PLUS] Note in context menu disappears if referenced earlier through [[]] in chat

### ISSUE THREAD

**Issue by JiaruiYu-Consilium** [logancyang/obsidian-copilot#847]
Copilot version: 2.7.4

**Describe how to reproduce**

Step to reproduce the issue: 

1. Reference a note using [[]] in the chat window
2. Add the referenced note to the context menu using + button
3. Begin typing and the referenced note in the context menu disappears
4. Even if you start a new chat, the note referenced in the context menu would disappear again if begin typing, unless you restart the Obsidian app

**Expected behavior**

Reference notes through [[]] and + button should work together. After referencing a note with [[]], it should remain visible in the menu content, serving as a reminder of the current context for bot responses until we deliberately remove it. Furthermore, starting a new chat, rather than restarting the entire application, should resolve any conflicts between these features.

**Comment by logancyang** [comment]
@JiaruiYu-Consilium Thanks for reporting! I can reproduce. The fix is in #846, should be working in the next release.
