### ISSUE TITLE
More clean UI

### ISSUE THREAD

**Issue by dxcore35** [logancyang/obsidian-copilot#85]
![Screenshot 2023-06-18 at 13 22 13](https://github.com/logancyang/obsidian-copilot/assets/7279156/a2d951ed-e39e-405b-9c3e-936c98c3762a).

This is with Minimal theme.

For example:
**- MODEL SELECTION:** I dont want to see model of ChatGPT (hide in under one icon setting)
**- STOP GENERATING:** Show it only when it is generating something
 **- NEW CHAT:** Put it on top. And add icon that represent something new like new file etc.... this looks like icon to regenerate prompt....
 etc....
 
 Plugin is amazing tho! Really cannot wait for offline model!

**Comment by logancyang** [comment]
Thanks for the suggestion! The discussion board is a better place for UI suggestions, people can upvote there. Issues are more for feature enhancements and bugs. Closing here but feel free to open a discussion.
