### ISSUE TITLE
Let's change the position and icon of the "new chat" button; it's too easy to accidentally press it.

### ISSUE THREAD

**Issue by Wooden-Gear** [logancyang/obsidian-copilot#856]
"new chat" 键改一下位置和图标吧，不然很容易按错。
我好几次要按“Regenerate”键，错按了"new chat" 键，导致之前的聊天内容全部丢失了。

![20241126_215047_573_copy](https://github.com/user-attachments/assets/790d7da3-b4b0-4657-b4dd-1ce4c69fed68)

Please move and change the icon of the "new chat" button; otherwise, it's easy to press it by mistake.  I've accidentally pressed the "new chat" button several times when I meant to press "Regenerate," losing all my previous chat history.

**Comment by i13-ctflora** [comment]
Agreed!  At least a confirmation popup would be great.
