### ISSUE TITLE
Vault is not indexed, get 'Indexing is disabled on mobile devices' notification

### ISSUE THREAD

**Issue by rikark** [logancyang/obsidian-copilot#864]
- [X] Disable all other plugins besides Copilot **(required)**
- [X] Screenshot of note + Copilot chat pane + dev console added **(required)**
![Scherm­afbeelding 2024-11-27 om 14 13 29](https://github.com/user-attachments/assets/49043ec0-4fb1-4f5c-bcc5-998608a151af)

Copilot version: 2.7.4

(Bug report without the above will be closed)

**Describe how to reproduce**
1. Install fresh Copilot plugin
2. Add Anthropic API key
3. Reload
4. Notification 'Indexing is disabled on mobile devices'
5. Retry with Disable index loading on mobile disabled
6. Same result

**Expected behavior**
Should index on desktop

**Screenshots**
![Scherm­afbeelding 2024-11-27 om 14 09 51](https://github.com/user-attachments/assets/9890164b-0e5f-429a-94ca-5ea8df4f2229)

**Additional context**
NA

**Comment by logancyang** [comment]
Have you tried triggering indexing though? What does it say?

(I mentioned Anthropic API key only, so none of the embedding models would work at this point. You need to set up embedding API for indexing.)

**Comment by rikark** [comment]
Not sure how I can do that, it seems 'indexing is disabled on mobile devices' blocks it from indexing.

I have reinstalled the plugin and entered both my OpenAI and Anthropic Api keys and saved and reloaded but still no luck.

**Comment by BarryYangi** [comment]
I'm having the same problem, there seems to be a setting that prevents indexing.

**Comment by logancyang** [comment]
@BarryYangi what happens if you run copilot command with cmd(ctrl) + P : "index (refresh) vault for QA"?

**Comment by BarryYangi** [comment]
> @BarryYangi what happens if you run copilot command with cmd(ctrl) + P : "index (refresh) vault for QA"?

![image](https://github.com/user-attachments/assets/827f6150-5133-4444-9309-168260a1ed56)
also this  notification,and I am using an arm series mac.

**Comment by logancyang** [comment]
Does the mode selection show "indexed not loaded" for vault QA and plus mode? Try opening the dev console and hit cmd + R to refresh, and then let me know if there's any difference. @BarryYangi

**Comment by BarryYangi** [comment]
> Does the mode selection show "indexed not loaded" for vault QA and plus mode? Try opening the dev console and hit cmd + R to refresh, and then let me know if there's any difference. @BarryYangi
> 
> Please also share screenshot of dev console message with debug mode on.

![image](https://github.com/user-attachments/assets/4491a23d-d0ed-4455-8881-c0b4e4105120)

that's all when I reindex it

**Comment by BarryYangi** [comment]
> Does the mode selection show "indexed not loaded" for vault QA and plus mode? Try opening the dev console and hit cmd + R to refresh, and then let me know if there's any difference. @BarryYangi
> 
> Please also share screenshot of dev console message with debug mode on.

![image](https://github.com/user-attachments/assets/e83a25c5-332f-494c-bc16-1bd381e77551)
that's all when I reindex

**Comment by BarryYangi** [comment]
I konw why, my config is wong...

**Comment by kobyalex** [comment]
What was your fix for the config? Having the same issue as you've described.
