### ISSUE TITLE
Bug cannot read active note

### ISSUE THREAD

**Issue by dxcore35** [logancyang/obsidian-copilot#87]
![Screenshot 2023-06-18 at 13 34 29](https://github.com/logancyang/obsidian-copilot/assets/7279156/38f04fcf-5638-4b50-b832-4d9819b123f2)

Plugin: v2.3.2
And I have switched to QA mode in setting.

**Comment by logancyang** [comment]
It's showing you are in Conversation mode. Can you refer to the FAQ in the readme?
