### ISSUE TITLE
[PLUS] Partitioning for indexing

### ISSUE THREAD

**Issue by logancyang** [logancyang/obsidian-copilot#870]
Large vaults are seeing #834.

What we need

1. #869 
2. This issue: have partitions and save to multiple json files to avoid overflowing.

**Comment by ottsch** [comment]
@logancyang Would having more than one partition also help with slow startup times in bigger vaults?

**Comment by logancyang** [comment]
@ottsch What's the cause of the slow startup time? Can you check your performance tab in the dev console to pinpoint the cause? This partitioning logic is mainly to avoid indexing error, it shouldn't be relevant to startup time but you can try and let me know.
