### ISSUE TITLE
 Cannot read properties of null (reading 'temperature') 

### ISSUE THREAD

**Issue by CodeCY9** [logancyang/obsidian-copilot#892]
- [ X ] Disable all other plugins besides Copilot **(required)**
- [ X ] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.5
Obsidian version: 1.7.7

**Describe how to reproduce**
When I start the plugin, an error occurs: Plugin loading error. I tried creating a new vault and enabling Copilot, but the same error still occurred.
**Expected behavior**
I hope to enable this plugin properly.

**Screenshots**
![image](https://github.com/user-attachments/assets/ab4e7397-0bad-4e69-807d-a24ea76c73c1)

**Additional context**
 Cannot read properties of null (reading 'temperature')

**Comment by haandol** [comment]
same here.

**Comment by johnvoorhees** [comment]
Seeing the same thing here

**Comment by Arhorn** [comment]
Seeing the same thing here

**Comment by FortilloNL** [comment]
Same here.

Plugin failure: copilot TypeError: Cannot read properties of null (reading 'temperature')
    at sanitizeSettings (plugin:copilot:115769:39)
    at CopilotPlugin.loadSettings (plugin:copilot:162303:31)
    at async CopilotPlugin.onload (plugin:copilot:161932:5)

**Comment by logancyang** [comment]
Sorry about this! Please install 2.7.6 and let me know if there are any issues.
