### ISSUE TITLE
OpenRouter Models no longer working

### ISSUE THREAD

**Issue by MTGMAD** [logancyang/obsidian-copilot#895]
- [X] Disable all other plugins besides Copilot **(required)**
- [X] Screenshot of note + Copilot chat pane + dev console added **(required)**
- 
![Screenshot 2024-12-03 220342](https://github.com/user-attachments/assets/8f5b0cac-1649-4c57-84a3-f643babdf6ea)

Copilot version: 2.7.5 and 2.7.6

**Describe how to reproduce**
I think this is with Openrouter only. After the 2.7.5 update no matter what I do, I cannot get models with Open Router to work. I have removed and reapplied my API key and deleted and readded my custom models. All that I get is TypeError: Failed to construct 'URL': Invalid URL

**Expected behavior**
older versions work just fine, and I get a response from openrouter modles.

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot ssettings and turn off other plugins to leave only Copilot dev messages as necessary.

**Additional context**
I disabled all modes except Copilot.

**Comment by logancyang** [comment]
I'm on 2.7.6 and openrouter is working for me. Can you try resetting your setting to default and add the openrouter API key and model again? 

<img width="605" alt="SCR-20241203-rwgw" src="https://github.com/user-attachments/assets/6ad43514-edc0-41de-b80e-e21bd5f726ec">

cc @Emt-lin

**Comment by MTGMAD** [comment]
Fixed
