### ISSUE TITLE
Copilot doesnt start after adding correct API

### ISSUE THREAD

**Issue by dr-abraham74** [logancyang/obsidian-copilot#897]
- [ ] Disable all other plugins besides Copilot **(required)**
- [ ] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.6

(Bug report without the above will be closed)

**Describe how to reproduce**
Clicking on copilot , it doesn't not open anything, API keys were correct and added. 

**Expected behavior**
I expect a chat to start 
![Screenshot 2024-12-04 at 11 58 04 pm](https://github.com/user-attachments/assets/4f0906da-02c7-4dcb-941a-3e3214199886)

**Screenshots**
Add screenshots to help explain your problem. Please turn on debug mode in Copilot settings, turn off other plugins to leave only Copilot dev messages as necessary.

**Additional context**

**Comment by logancyang** [comment]
hi @dr-abraham74, what OS is this, I can't see if your right side pane is open. Please follow the bug report instructions.

**Comment by dr-abraham74** [comment]
I think I fixed it. It was having a bad interaction with the other plugins. Make.MD to be specific

**Comment by logancyang** [comment]
An old version of Make.MD was conflicting with Copilot, they have fixed it in the new version afaik.
