### ISSUE TITLE
Note title in the chat context exceeds the available space in Obsidian iOS app

### ISSUE THREAD

**Issue by wenzhengjiang** [logancyang/obsidian-copilot#899]
- [*] Disable all other plugins besides Copilot **(required)**
- [*] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.4

(Bug report without the above will be closed)

**Describe how to reproduce**
For added notes in the chat context, if the note title is long, the title will exceed the available space.

**Expected behavior**
The easiest way to improve this is to truncate the title with an ellipsis (...) For example, the title in the screenshot can become "Building ..."

**Screenshots**
![IMG_3914](https://github.com/user-attachments/assets/df7210e9-7480-4f62-bc6c-2faee8cf4e9b)

**Additional context**

**Comment by logancyang** [comment]
Looks like you are on 2.7.4, this should be fixed in the latest version 2.7.6. Let me know if it's not.

**Comment by wenzhengjiang** [comment]
Oh, thanks! The bug has been fixed in the latest version. Didn't realized I need to update my copilot plugin...

**Comment by logancyang** [comment]
@wenzhengjiang right I added a version check and a notice in 2.7.6, in the future people on older versions will get a notice to let them update.
