### ISSUE TITLE
Relocate Copilot Index to avoid consuming all sync space.

### ISSUE THREAD

**Issue by pedramamini** [logancyang/obsidian-copilot#901]
We should move the copilot index storage to a custom folder that we can then exclude from sync:

![image](https://github.com/user-attachments/assets/54c77506-fbb0-4c54-999f-3ae56e6820e7)

Currently, every change to this file results in a sync to the cloud. My 1.5GB vault consumed all 10GB because of this file:

![image](https://github.com/user-attachments/assets/2bad642d-f984-4339-888e-9ff9e9d1c84d)

**Comment by logancyang** [comment]
In Copilot v2.7.7, when you disable this toggle in copilot, the index will be saved in `vaultRoot/.copilot-index`. There are some kinks to be worked out for settings without the "save and reload" button in general. Please turn the plugin off and on to make sure it works.

**Comment by pedramamini** [comment]
Thanks. I can confirm that the exclusion is working now. Apparently, it'll just take 2 weeks for the historic files to be removed from Obsidian Sync!
