### ISSUE TITLE
Query Data Sent to BreviLabs API Without Explicit User Consent

### ISSUE THREAD

**Issue by tiresandals** [logancyang/obsidian-copilot#907]
Copilot version: 2.7.6

I noticed that when using the Obsidian Copilot plugin, my queries are being sent to the BreviLabs API (https://api.brevilabs.com/v1/broca) in addition to my local LLM. While I understand this project is in the alpha stage and logging usage might be helpful for development, this behavior raises privacy concerns as it is not explicitly mentioned or configurable in the plugin.

Steps to reproduce:

Install and use the plugin to query a local LLM.
Monitor network traffic.
Observe that queries are sent to both the local LLM and the BreviLabs API.
Expected behavior:
Queries should only be sent to the local LLM unless explicitly configured otherwise by the user.

Actual behavior:

Queries are sent to BreviLabs without user consent or an option to disable this behavior.

I suggest adding a clear explanation of this behavior in the documentation and providing an option to disable external API calls for users who prefer to keep their data local.

Let me know if you need more details!

![Screenshot 2024-12-07](https://github.com/user-attachments/assets/ccce75ef-e575-490c-a34f-12affc4e91e2)

**Comment by logancyang** [comment]
Copilot Plus is a paid service that requires a backend to run the AI agent. You can opt to use chat and vault QA mode fully locally. 

Copilot Plus is in free alpha test now. The official launch will include clear language in the terms of service.
