### ISSUE TITLE
CORS issue on API calls leads to license key invalid message

### ISSUE THREAD

**Issue by gluecode** [logancyang/obsidian-copilot#910]
- [X] Disable all other plugins besides Copilot **(required)**
- [X] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.6

**Describe how to reproduce**
1. Install fresh, latest version of Copilot
2. Configure with Copilot Plus and OpenAI keys
3. Switch to Copilot Plus (Alpha) as default mode
3. Do not close Obsidian
4. Use a prompt in Copilot and it returns answers as expected _(although autocomplete for @vault, @web, @YouTube does not work without Obsidian restart)_
5. Restart Obsidian
6. Use the same working prompt again
7. Copilot Plus returns the error message - **"Copilot Plus message failed. Please provide a valid license key in your Copilot setting."**

**Expected behavior**
Copilot Plus must provide answers for web, vault or Youtube prompts

**Screenshots**
Attached two screenshots of Obsidian with console and copilot visible

**Additional context**
None

![CleanShot 2024-12-08 at 17 02 46@2x](https://github.com/user-attachments/assets/dfec76e7-95a6-42c7-904f-93319caf8414)
<img width="635" alt="CleanShot 2024-12-08 at 17 03 41@2x" src="https://github.com/user-attachments/assets/005dce46-9a76-4e5a-86e6-f7ecab5c5b22">

**Comment by logancyang** [comment]
@gluecode Thanks for reporting! I understand now, will put up a fix soon!

**Comment by logancyang** [comment]
@gluecode can you try if this is still happening?

**Comment by gluecode** [comment]
@logancyang The issue is resolved. I can now restart Obsidian and see that web and vault prompts are consistently answered. A regression seems to be that @ autocomplete in the Copilot Plus prompt window is not working. So typing @ does not bring up the pop-up frame.

**Comment by logancyang** [comment]
@gluecode `@` autocomplete always works for me, haven't been able to reproduce your issue. Is it conflicting with other plugins on your end? Is copilot the only one enabled?

**Comment by gluecode** [comment]
**First issue** - @logancyang, my apologies. The first issue remains unresolved. When I tested it, with the updated plugin, I gig not turn on default mode as Copilot Plus (Alpha). Now that I set 'Copilot Plus (Alpha)' as default mode, I see the same errors in console.

![CleanShot 2024-12-10 at 09 11 36@2x](https://github.com/user-attachments/assets/381af29b-d916-4f5e-9c15-382f90f65a43)

**Comment by gluecode** [comment]
Second issue - I can create a separate issue for this if you like. Seems like a regression with the updated plugin 2.7.7. The autocomplete stopped. It was working before this update.

**Comment by logancyang** [comment]
@gluecode OK I see I need another solution for the first issue, will put out a quick 2.7.8 for that soon. 

Could you please open a separate issue for the 2nd one? I'm having trouble reproducing it. Other people who have the same problem may be able to share some ideas.

**Comment by logancyang** [comment]
@gluecode Please update to 2.7.8, let me know if this is still an issue.

**Comment by gluecode** [comment]
@logancyang Thanks. There is a different error in the console now regarding intent analysis. Attached screenshot. The error message in the UI remains same - _"Copilot Plus message failed. Please provide a valid license key in your Copilot setting."_

![CleanShot 2024-12-11 at 06 06 36@2x](https://github.com/user-attachments/assets/40b01986-c2f3-4ec3-a69b-d9cdc8e51145)

**Comment by logancyang** [comment]
@gluecode 403 is the real code for invalid license key. Can you make sure your key is correct in data.json again?

**Comment by gluecode** [comment]
I reinstalled Copilot (after deleting the plugin) and set the correct license key. I have visually verified the license key in data.json.

**Comment by logancyang** [comment]
@gluecode When was this request sent? I see it's 6:06am but what timezone?

**Comment by gluecode** [comment]
@logancyang I'm traveling in India today. This is IST timezone. Current time is 6:30 AM IST.

**Comment by logancyang** [comment]
@gluecode that's interesting, I checked my server log and there's no request at that time. What network are you on? It's better if we could dm in discord at this point.

**Comment by gluecode** [comment]
@logancyang - I'm on my parent's home wifi and it's a high-speed fiber. Works well for Internet access. I'm heading back to the US now and will reconnect with you on Discord after I get home.

**Comment by logancyang** [comment]
@gluecode thanks for working with me on this! I suspect that your ISP somehow didn't let your request reach my server at all, but I haven't seen a case like this before. My guess is it will work when you are back in the US and this behavior won't happen again. Let's see. Safe travels!
