### ISSUE TITLE
Add support to use settings font-size

### ISSUE THREAD

**Issue by rockmanvnx6** [logancyang/obsidian-copilot#92]
I have my font in custom size but however is not applicable to the AI chat window font. 

<img width="723" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/16440123/e5744d6c-999e-4d06-82b2-c7dd19dea0e7">

It would be great if we have an option to use this font size parameter for accessibility

**Comment by logancyang** [comment]
It should work now in v2.3.4. Feel free to reopen if it's still not working for you.

**Comment by rockmanvnx6** [comment]
Thanks, i'm using it now. Appreciate it!
