### ISSUE TITLE
Third-Party API Error After Updating to v2.7.9, Working Fine with Old v1.1.7

### ISSUE THREAD

**Issue by chriswhite5918** [logancyang/obsidian-copilot#928]
- [x] Disable all other plugins besides Copilot **(required)**
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version:
v2.7.9

**Describe how to reproduce**
Everything was working just fine. But after updating to the latest version, the chat keeps throwing errors, and restarting didn’t help. I’m using a third-party OpenAI compatible API. I tried removing the previously added API and re-adding it, but the result was the same—still getting errors.

**Expected behavior**
Under normal circumstances, it should be able to connect to the server without any errors.

**Screenshots**
<img width="769" alt="Obsidian_Xa6wAXKqOq" src="https://github.com/user-attachments/assets/fd31028b-7522-4ad8-a1fe-85c5c705267e" />

**Additional context**
I have an older version, v1.1.7 of Copilot, and it works perfectly with the same API without any errors.
<img width="682" alt="Obsidian_gUAWceG8aw" src="https://github.com/user-attachments/assets/dde0f493-1082-49c3-8c40-dbbbd9f853eb" />

**Comment by chriswhite5918** [comment]
I replaced the files in the current .obsidian/plugin/copilot folder with those from v2.7.8 to fix the issue. I really hope future versions can address this, or I might be stuck on v2.7.8

**Comment by logancyang** [comment]
I need more info on your model, whether you turn on CORS for it.

**Comment by qidianlinjin1990** [comment]
When filling in the URL, omitting "v1" will resolve the issue, just use https://api.openai.com directly.

**Comment by qidianlinjin1990** [comment]
Also, do not choose CORS

**Comment by logancyang** [comment]
Fix is in, will be working again in v2.7.10 which I will release soon. https://github.com/logancyang/obsidian-copilot/pull/943
