### ISSUE TITLE
[BUG] Can't embed on 2.7.9

### ISSUE THREAD

**Issue by ALE-ARME** [logancyang/obsidian-copilot#932]
- [x] Disable all other plugins besides Copilot **(required)**
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version:2.7.9

(Bug report without the above will be closed)

**Describe how to reproduce**
I use jina-embeddings-v3 but it doesn't work on 2.7.9 (it does if I go back to 2.7.8)

**Expected behavior**
Embed the new file(s)

**Screenshots**
![console.PNG](https://github.com/user-attachments/assets/5a13d521-6e62-4c16-9bba-73c8d745c140)

![notification.PNG](https://github.com/user-attachments/assets/16443fea-a367-439b-bc5c-86dd5cca9a51)

**Comment by logancyang** [comment]
Could it be the same issue as #928. There are only a few changes in 2.7.9 and I didn't think it will affect anything like this.

What provider do you use for `jina-embeddings-v3`?

**Comment by logancyang** [comment]
Your error message shows OpenAI connection error when getting embedding vector length, which means it's using OpenAI embedding, not jina. I can see your chat model is gemini and also not OpenAI. So it must be using OpenAI embedding model.

There's no change in 2.7.9 on anything embedding model-related. Can you give me more details on how I can reproduce this.

**Comment by ALE-ARME** [comment]
I use CORS because i've read that it was needed to make things work on mobile.
The model provider is "openai-format".
API key encription is NOT enabled.
You can get a free API key from https://jina.ai/
If I download again the 3 files for v2.7.8 and replace the 2.7.9, after reloading obsidian, I'm able to index my file(s) successfully

**Comment by logancyang** [comment]
> I use CORS because i've read that it was needed to make things work on mobile. 

Are you on mobile though? That screenshot is from desktop isn't it?

Have you tried CORS off? I can reproduce that CORS on does not work for this model, but CORS off did work.

**Comment by ALE-ARME** [comment]
I use obsidian on pc, tablet and smartphone. The screen is from pc because I don't think there is the console from mobile.

I tried from my phone with CORS off and it worked. I still have to try it from pc

**Comment by logancyang** [comment]
Fix is in, should be working again in v2.7.10 which I will release soon. https://github.com/logancyang/obsidian-copilot/pull/943
