### ISSUE TITLE
No Save and Reload Button

### ISSUE THREAD

**Issue by robsondamota** [logancyang/obsidian-copilot#933]
- [ x ] Disable all other plugins besides Copilot **(required)**
- [ x ] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.9

The absence of this button prevents me from even start using the plugin. 
API key is on.

**Screenshots**
<img width="853" alt="Captura de Tela 2024-12-15 às 11 18 58" src="https://github.com/user-attachments/assets/284cbc82-ca16-44f4-9bbd-53a085ed784f" />

<img width="1512" alt="Captura de Tela 2024-12-15 às 11 26 45" src="https://github.com/user-attachments/assets/bd7fc39d-6a95-4bfb-bf63-f0def30a0907" />

**Comment by logancyang** [comment]
Save and reload button is removed and unnecessary now. Your API key is in effect. This error message means that either you don't have payment on the OpenAI API platform, or you don't have access to this model because of permission setting. Please go to platform openai to troubleshoot.
