### ISSUE TITLE
error: api key is not provided for the model

### ISSUE THREAD

**Issue by jsrdcht** [logancyang/obsidian-copilot#94]
Every model selection will triggle this error while other gpt plguins work well with the same openai key.

**Comment by logancyang** [comment]
Can you try resetting your copilot settings and entering your API keys again?

If that doesn't work please turn on debug mode, paste your settings page and console here.

**Comment by logancyang** [comment]
@Gnopps This usually means somehow your data.json where your credentials are saved got corrupted somehow. Resetting and restarting should erase it.
