### ISSUE TITLE
moonshot can't use copilot, report "Error: Connection error."

### ISSUE THREAD

**Issue by weidong** [logancyang/obsidian-copilot#941]
- [x] Disable all other plugins besides Copilot **(required)**
- [x] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: v2.7.9

Use the moonshot api ,  report "Error: Connection error."

**Screenshots**
![image](https://github.com/user-attachments/assets/27d03653-2be7-4533-a231-cf3ca46f3700)

![image](https://github.com/user-attachments/assets/9e1ed094-e9c9-4193-9602-da70997721c3)

![image](https://github.com/user-attachments/assets/da20fd51-d907-4f8e-a03c-5005cf74b596)

**Additional context**

**Comment by logancyang** [comment]
Do you have CORS on or off?

**Comment by weidong** [comment]
> Do you have CORS on or off?

I have the CORS on， the moonshot api can't connection --- Error: Connection error.
then 
I change the CORS off,  the moonshot api also can't connection.

I have try the CORS on and off

This error occurred after I upgraded to 2.7.9.

**Comment by logancyang** [comment]
@weidong Fix is in, will be working again in v2.7.10 which I will release soon. #943
