### ISSUE TITLE
In an Obsidian window, Copilot drop-downs don't work

### ISSUE THREAD

**Issue by upnix** [logancyang/obsidian-copilot#960]
- [X] Disable all other plugins besides Copilot **(required)**
- [X] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.7.10 (Linux+Wayland)

**Describe how to reproduce**
1. Copilot setting "Open plugin in Editor" is set.
2. Make sure Copilot isn't open in any tabs or side bar
3. Open a new Obsidian window (Right click a note -> Open in new window)
4. With the new window focused, use the command pallet and go "Copilot: Toggle Copilot Chat Window"
5. Attempt to use either the model drop-down or the Chat/VaultQA drop down
6. Neither should work as expected, and if your new Obsidian window is over the main Obsidian window you might see those drop downs show up in the left-hand area of the main Obsidian window.

As seen in the screenshot, clicking on a menu as described above will result in the following error in the development console:
`[Violation] Forced reflow while executing JavaScript took 35ms`

**Expected behavior**
Menus show up over where you clicked in the new Obsidian window.

**Screenshots**
![image](https://github.com/user-attachments/assets/ce50f5f5-a3bd-4ccf-9f57-0d520570bf03)

**Additional context**
As mentioned above, the drop-downs do show up, but they're over the main Obsidian window.

**Comment by logancyang** [comment]
@zeroliu @Emt-lin Is this something we can address with the new tailwind setup?

**Comment by zeroliu** [comment]
The dropdown menu is currently using Radix so the new change to adopt shadcn would not help. This is a caveat of us using a UI library that doesn't know how to handle these electron edge cases by default.

**Comment by zeroliu** [comment]
Proposed a fix here: https://github.com/logancyang/obsidian-copilot/pull/961
