### ISSUE TITLE
Allow users to disable Copilot's automatic update checks when launching Obsidian.

### ISSUE THREAD

**Issue by EnziTheViking** [logancyang/obsidian-copilot#975]
**Issue:**
The Copilot plugin performs automatic update checks when Obsidian launches, which is not ideal for users prioritizing privacy or local-only workflows. 

**Proposed Solution:**
Introduce a setting (e.g., Check for Updates on Launch) in the Copilot Settings that allows users to toggle automatic update checks. By default, this setting could be enabled to maintain current functionality, but I think that users should really have the option to disable it in favor of using Obsidian's built-in mechanism to check for updates.

**Benefits?**
1. Respect Privacy Preferences: Avoids unnecessary external calls, aligning with user expectations for a privacy-focused ecosystem. (Sorry but updates really should be checked through Obsidians built-in system, not the plugin itself)
2. Supports Local-Only Workflows: Builds confidence among users who prefer plugins that function without external connectivity - Especially when those plugins can function without those external calls.

**Additional Context:**
As a temporary workaround, I manually disabled the automatic update check by commenting out the relevant code, as shown below:
```JavaScript
async onload() {
    // await this.checkForUpdates();
    await this.loadSettings();
    this.settingsUnsubscriber = subscribeToSettingsChange(() => {
        const settings = getSettings();
        if (settings.enableEncryption) {
            this.saveData(encryptAllKeys(settings));
        } else {
            this.saveData(settings);
        }
        registerBuiltInCommands(this);
    });
    ...
}
```

_Otherwise, really enjoy this Project._

**Comment by logancyang** [comment]
Disabled the check in 2.7.12.
