### ISSUE TITLE
Azure setting issue

### ISSUE THREAD

**Issue by likemuuxi** [logancyang/obsidian-copilot#98]
Help: Can you add an example of Azure settings? I'm not sure about the corresponding relationship between the settings options

**Comment by logancyang** [comment]
Take the example I have in the [video demo](https://youtu.be/d84KWejBp30)
![image](https://github.com/logancyang/obsidian-copilot/assets/4860545/258ffa00-1d62-4174-9e14-8da013c0d4e8)

This is your **instance name**: Azure OpenAI resource
![image](https://github.com/logancyang/obsidian-copilot/assets/4860545/737ca522-ee7e-4def-b0bc-2055e7d9531a)

This is your **deployment name**: Azure AI Studio
![image](https://github.com/logancyang/obsidian-copilot/assets/4860545/6bc01724-98f1-4294-8cbd-e1e812d50308)

Let me know if this helps!

**Comment by likemuuxi** [comment]
I have followed your instructions to set up, but I'm not sure where I went wrong. I am receiving a LangChain error: 404.&nbsp;




丿ωo?&nbsp;冷丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "logancyang/obsidian-copilot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 中午11:48
***@***.***&gt;;
抄送:&nbsp;"丿ωo? ***@***.******@***.***&gt;;
主题:&nbsp;Re: [logancyang/obsidian-copilot] Azure setting issue (Issue #98)





 
Take the example I have in the video demo
 
 
This is your instance name: Azure OpenAI resource
 
 
This is your deployment name: Azure AI Studio
 
 
Let me know if this helps!

**Comment by logancyang** [comment]
@likemuuxi can you show me your Azure pages just like the ones I posted?

**Comment by likemuuxi** [comment]
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/a9fcdc0e-d225-4c32-bd19-621a33ae53a9)
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/41ac1799-22bc-4f83-b056-ffe2920c284b)
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/5a1f9059-5252-4edd-84d0-68bbf3bad062)

**Comment by likemuuxi** [comment]
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/0c22ca9a-21bf-4284-8023-736a4af37b43)
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/457fdfa3-1b9f-45a1-a42a-7d7c7a8ecd1b)
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/13805a4b-1458-45e4-9b90-c4e70d30c083)

**Comment by logancyang** [comment]
Looks alright to me. Are you able to curl it?

```
curl https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/completions?api-version=VERSION\
  -H "Content-Type: application/json" \
  -H "api-key: YOUR_API_KEY" \
  -d "{
  \"prompt\": \"Once upon a time\",
  \"max_tokens\": 5
}"
```

replace the params with yours

**Comment by likemuuxi** [comment]
https://chatgpt327-3.openai.azure.com/openai/deployments/GPT35/completions?api-version=2023-06-25\
{
    "error": {
        "code": "404",
        "message": "Resource not found"
    }
}

![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/35851f6a-66f5-4b80-9f2c-5431212e06ed)
Click on the domain name as shown in the picture, but I am still able to use the model.

**Comment by logancyang** [comment]
No you need to curl it, clicking on the link won't work. Can you show me your terminal with the curl response?

**Comment by likemuuxi** [comment]
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/bc8c2eeb-eb9a-427f-b661-2fe3a60f52b7)

**Comment by logancyang** [comment]
Ok curl doesn't work, means your params are not correct. Are you sure about the api-version? Can you make sure all your params are correct by testing using this curl command. Once this works, you will be able to use it properly in copilot.

**Comment by logancyang** [comment]
FYI, I saw 404 myself when I have wrong the API version. It is not the model version you see in Azure page apparently. Try "2023-05-15" like I used in the video demo?

**Comment by likemuuxi** [comment]
It's possible that the issue is related to the deployment region of the model, as it can affect the API calls.

从 Windows 版邮件发送

发件人: Logan Yang
发送时间: 2023年7月11日 9:30
收件人: logancyang/obsidian-copilot
抄送: likemuuxi; Mention
主题: Re: [logancyang/obsidian-copilot] Azure setting issue (Issue #98)

FYI, I saw 404 myself when I have wrong API version. It is not the model version you see in Azure page apparently. Try "2023-05-15" like I used in the video demo?

**Comment by likemuuxi** [comment]
> FYI, I saw 404 myself when I have wrong API version. It is not the model version you see in Azure page apparently. Try "2023-05-15" like I used in the video demo?

This doesn't work, I wonder if it could be a problem with the deployment region of the model, as it affects API calls

**Comment by likemuuxi** [comment]
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/9e1e8556-9ef4-48ec-85d9-75db4ec73c0a)
Can be changed to this parameter input format.

**Comment by logancyang** [comment]
There's not much I can do to help debug your deployment. One helpful thing I tried was Azure's support chat, they are quite helpful, just let them help you figure out the right params, make sure curl works, and you will be able to use this plugin without an issue. Closing for now since this is not a Copilot issue.

But I see Azure params can be hard to get right at first. Will put the curl command example in the FAQ.

**Comment by likemuuxi** [comment]
> There's not much I can do to help debug your deployment. One helpful thing I tried was Azure's support chat, they are quite helpful, just let them help you figure out the right params, make sure curl works, and you will be able to use this plugin without an issue. Closing for now since this is not a Copilot issue.
> 
> But I see Azure params can be hard to get right at first. Will put the curl command example in the FAQ.

Thank you for your patient answer. I received inspiration and found various versions of the API on the following page. After modification, it can be used normally
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions

**Comment by lil-i321** [comment]
> > There's not much I can do to help debug your deployment. One helpful thing I tried was Azure's support chat, they are quite helpful, just let them help you figure out the right params, make sure curl works, and you will be able to use this plugin without an issue. Closing for now since this is not a Copilot issue.
> > But I see Azure params can be hard to get right at first. Will put the curl command example in the FAQ.
> 
> Thank you for your patient answer. I received inspiration and found various versions of the API on the following page. After modification, it can be used normally https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions

你好，请问你是怎么解决这个问题的？我也遇到了同样的问题：“LangChain error: 404.”
我的终结点链接是这个：
https://chatg230808.openai.azure.com/openai/deployments/gpt313/chat/completions?api-version=2023-03-15-preview

**Comment by likemuuxi** [comment]
> > > There's not much I can do to help debug your deployment. One helpful thing I tried was Azure's support chat, they are quite helpful, just let them help you figure out the right params, make sure curl works, and you will be able to use this plugin without an issue. Closing for now since this is not a Copilot issue.
> > > But I see Azure params can be hard to get right at first. Will put the curl command example in the FAQ.
> > 
> > 
> > Thank you for your patient answer. I received inspiration and found various versions of the API on the following page. After modification, it can be used normally https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions
> 
> 你好，请问你是怎么解决这个问题的？我也遇到了同样的问题：“LangChain error: 404.” 我的终结点链接是这个： https://chatg230808.openai.azure.com/openai/deployments/gpt313/chat/completions?api-version=2023-03-15-preview

尝试修改插件中的Azure OPENAI API Version  其为下列中的一个  自行尝试
![image](https://github.com/logancyang/obsidian-copilot/assets/85612715/d97013f7-f20c-455d-aa23-45242818a0de)

**Comment by likemuuxi** [comment]
> 我用了对应的api version，并在本插件中设置了token length，完全ok了。
> BYW
> 如何修改api version 呢？我部署了3个 3.5模型 ，api version 都是[2023-03-15-preview]，不同的 api version 有什么区别吗？

可以使用即可，不用在意api version  具体区别我想应该去查阅帮助文档

**Comment by lil-i321** [comment]
> 

yes，谢谢了，在Azure 部署模型中 没有找到变更api version 的入口。

**Comment by john-crouch** [comment]
You can get all the necessary info in one fell swoop by:
1. Navigate to the [Azure OpenAI portal](https://oai.azure.com/)
2. Select "Completions"
3. Click "View Code"
4. Copy the endpoint URL (this contains all required:
> https://{Open AI Instance name}.openai.azure.com/openai/deployments/{deployment name}/completions?api-version={api version}
5. Copy the API key as well.

![image](https://github.com/logancyang/obsidian-copilot/assets/50185606/6a94d2f0-0f88-4e6f-b3c5-0b4cacc4be94)
![image](https://github.com/logancyang/obsidian-copilot/assets/50185606/dc499d65-05a6-4b8e-b578-e79a390c35cd)
![image](https://github.com/logancyang/obsidian-copilot/assets/50185606/94d39c54-b404-40ed-b4bd-e025f0113020)

**Comment by thinkthinking** [comment]
> Take the example I have in the [video demo](https://youtu.be/d84KWejBp30) ![image](https://private-user-images.githubusercontent.com/4860545/251030639-258ffa00-1d62-4174-9e14-8da013c0d4e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTgyNTMsIm5iZiI6MTcwNDg1Nzk1MywicGF0aCI6Ii80ODYwNTQ1LzI1MTAzMDYzOS0yNThmZmEwMC0xZDYyLTQxNzQtOWUxNC04ZGEwMTNjMGQ0ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDMzOTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OThiNzYxMDVhNWE3NTI1NDk4ZTM1MzUxMWEzYjQ2ZDExZGRiNDc0MjMyNzNkYzE1NzJmYWQ2ZTIxMTAzNjRjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TfKLeCeNNDV0tlUyR09YbZkNjreiv9s7y32ul2QWZpI)
> 
> This is your **instance name**: under Azure OpenAI resource see this below ![image](https://private-user-images.githubusercontent.com/4860545/251031308-737ca522-ee7e-4def-b0bc-2055e7d9531a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTgyNTMsIm5iZiI6MTcwNDg1Nzk1MywicGF0aCI6Ii80ODYwNTQ1LzI1MTAzMTMwOC03MzdjYTUyMi1lZTdlLTRkZWYtYjBiYy0yMDU1ZTdkOTUzMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDMzOTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcyZmMzOGQxZTg2Y2QwOTZhYTc4NDEwYjc4YTM4NTk4MTliMmFkMWJmYjhmNTY3MTVkZTdjNzQyNDY0MzhhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w97pnM4EIo5-gpyn94DirMnCpQelo6CafCGtUA6j-eQ)
> 
> This is your **deployment name**: under Azure AI Studio see this below ![image](https://private-user-images.githubusercontent.com/4860545/251031112-6bc01724-98f1-4294-8cbd-e1e812d50308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTgyNTMsIm5iZiI6MTcwNDg1Nzk1MywicGF0aCI6Ii80ODYwNTQ1LzI1MTAzMTExMi02YmMwMTcyNC05OGYxLTQyOTQtOGNiZC1lMWU4MTJkNTAzMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDMzOTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UwN2U3ODk4MzMzNzVhOTI5OWI1ZmJmMGRiMjBhOTk0NzZiNmRjM2M4NjZmMTdiZmEzY2UwODYyODM5MjNhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lYrzu-wZIaHo2f_UM8gP8HKAq8c9BiTMMpbDxGqOlHQ)
> 
> Let me know if this helps!

it works, thank you
@logancyang

**Comment by breakastick** [comment]
My situation is a bit different. 
My link is https://[a name].services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview
I depolied DeepSeek-R1 from ai.azure.com not from oai.azure.com
I can't find "Azure OpenAI resource", “instant name” or "deployment name".
I went to [Azure OpenAI portal](https://oai.azure.com/) completions and found nothing there
