### ISSUE TITLE
Be able to load conversations from their notes

### ISSUE THREAD

**Issue by Bugsia** [logancyang/obsidian-copilot#985]
When I am using ChatGPT, for example, I often use multiple chats to seperate different topics. Because often times, in my experience, the AI's response get's heavily influenced by the past messages and this leads to the response quality being worse, when a different topic was discussed earlier, since the AI tries to push it's response into that topic.

So I would like to have the ability to load the conversations, that have been saved to a note, back into the chat window. Thus being able to continue the conversation and have multiple consecutive chats.

Maybe the current context/messages can be parsed as json and then be stored at the end of the conversation note for simple reconstruction of the chat.

Thanks for such a great plugin!

**Comment by logancyang** [comment]
Please use "Save as Note" button along with "Load copilot chat conversation" command.
