### ISSUE TITLE
"Error: (no status code or body)" when using LM Studio - Mistral 7b

### ISSUE THREAD

**Issue by tsangha** [logancyang/obsidian-copilot#986]
- [X] Disable all other plugins besides Copilot **(required)**
- [X] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version:  v2.7.12

(Bug report without the above will be closed)

**Describe how to reproduce**
Use LM Studio
Download mistral-7b-instruct-v0.3, enable CORS
Open Copilot settings, go to add custom model
Copy model name from LM Studio, paste in model name
Change provider to LM Studio
Start a new chat

**Expected behavior**
Copilot replies successfully

**Screenshots**
<img width="1151" alt="Screenshot 2024-12-30 at 21 08 45" src="https://github.com/user-attachments/assets/30d82e6a-dacf-4ec5-ae7d-53ef948c1b18" />

**Additional context**
Please note -- the model is responding correctly in LM Studio
Also note -- Copilot is responding correctly when using llama-3.2-3b-instruct
CORS is enabled
mistral is the only LLM running on local server in LM Studio

Also note that developer console in LM Studio IS showing the requests coming from Copilot
<img width="1035" alt="Screenshot 2024-12-30 at 21 22 01" src="https://github.com/user-attachments/assets/7454a243-b4c0-4003-b8fb-009f6de3083c" />

**Comment by logancyang** [comment]
Can you show me your LM studio server tab in full?

**Comment by tsangha** [comment]
Sure, like this? 
<img width="1640" alt="Screenshot 2024-12-31 at 08 42 00" src="https://github.com/user-attachments/assets/b3f14d3c-0a9a-404a-bd6c-fc05dc7559cc" />

**Comment by logancyang** [comment]
Ok i see, this is an instruct model that only supports user and assistant but not system prompts. You have to use a chat model that supports a system role.

<img width="921" alt="SCR-20241231-mwnx" src="https://github.com/user-attachments/assets/dc71ff8a-dd4b-43ec-b51e-5c5ef6748cb7" />
